<?php $this->headTitle('Delete Option'); ?>
<?php //$this->layout()->instructions = ""; ?>
<?php
$id;
if ($request->getqueryParams('id') !== null) {
    $params = $request->getqueryParams();
    $action = $params['action'];
    $wkat_id = $params['wkat_id'];
    $this->layout()->breadcrumbs .= '<a href="' . $this->url('attributes_worktype') . '" style="float:left;color:white;"> Attributes > </a>' .
            '<a href="' . $this->url('manage_attribute_options') . '?id=' . $wkat_id . '" style="float:left;color:white;"> Attribute Options > </a>'
            . ' Delete';
}
?>
<div class="col-xs-4">
    <form method="post" action="<?=$this->url('manage_attribute_options')?><?= '?id=' . $wkat_id ?>">
        <p>Are you sure you want to delete this?</p>  
        <?php
                if ($request->getqueryParams('action') !== null)
                {
                    $params = $request->getqueryParams();
                    $action = $params['action'];
                }

                if ($request->getMethod() == 'POST') {
                    $post = $request->getParsedBody();
                    //$id      = $params['id'];
                }

                $wkAttr_Opt = [];
                if(count($post['selectWorkAttrOpt']) > 0) {
                    foreach($post['selectWorkAttrOpt'] as $workAttrOpt):
                        $wkAttr_Opt['id'] = $workAttrOpt;
                        //fetch name based on id
                        $table = new \VuBib\Db\Table\WorkAttribute_Option($adapter);
                        $row = $table->findRecordById($wkAttr_Opt['id']);
                        $title = $row['title'];
                        echo "<p>$title</p>";
                        //fetch no of works associated
                        $table = new \VuBib\Db\Table\Work_WorkAttribute($this->adapter);
                        $paginator = $table->countRecordsByAttributeOption($wkat_id, $wkAttr_Opt['id']);
                        $cnt = $paginator->getTotalItemCount();
                        echo "<p><b>There are $cnt works associated with it.</b></p>"; ?>
                        <ul>    
                        <input type="hidden" name="workattropt_id[]" value="<?=$wkAttr_Opt['id']?>">                        
                        <input type="hidden" name="action" value="<?=$action?>">
                        </ul>                        
                        <?php
                    endforeach;
                }
            ?>
        <input type="submit" name="submitt" value="Delete"> 
        <input type="submit" name="submitt" value="Cancel">
    </form>
</div>

