<?php $this->headTitle('Delete Attribute'); ?>
<?php
      $this->layout()->breadcrumbs .= '<a href="' . $this->url('attributes_worktype') . '" style="float:left;color:white;"> Attributes > </a>'
                                     . ' Delete';
 ?>
<div class="col-xs-4">
    <form method="post" action="<?=$this->url('attributes_worktype')?>">
        <p>Are you sure you want to delete this?</p>  
        <?php
                if ($request->getqueryParams('action') !== null)
                {
                    $params = $request->getqueryParams();
                    $action = $params['action'];
                }

                if ($request->getMethod() == 'POST') {
                    $post = $request->getParsedBody();
                }

                $wkType_Attr = [];
                if(count($post['selectWorkTypeAttr']) > 0) {
                    foreach($post['selectWorkTypeAttr'] as $workTypeAttr):
                        $wkType_Attr['id'] = $workTypeAttr;
                        //fetch name based on id
                        $table = new \VuBib\Db\Table\WorkAttribute($adapter);
                        $row = $table->findRecordById($wkType_Attr['id']);
                        $field = $row['field'];
                        echo "<p>$field</p>";
                        //fetch no of work types selected attribute is associated with
                        $table = new \VuBib\Db\Table\WorkType_WorkAttribute($this->adapter);
                        $rows = $table->countWorkTypesByWorkAttributes($wkType_Attr['id']);
                        echo "<p><b>This attribute is associated with " . $rows[0]['count_worktypes'] . " work types.</b></p>"; ?>
                        <ul>    
                        <input type="hidden" name="workattr_id[]" value="<?=$wkType_Attr['id']?>">                        
                        <input type="hidden" name="action" value="<?=$action?>">
                        </ul>                        
                        <?php
                    endforeach;
                }
            ?>
        <input type="submit" name="submitt" value="Delete"> 
        <input type="submit" name="submitt" value="Cancel">
    </form>
</div>