<?php $this->headTitle('Edit Option'); ?>
<?php //$this->layout()->instructions = ""; ?>
<?php
$id;
if ($request->getqueryParams('id') !== null) {
    $params  = $request->getqueryParams();
    $action  = $params['action'];
    $id      = $params['id'];
    $wkat_id = $params['wkat_id'];
	$this->layout()->breadcrumbs .= '<a href="' .  $this->url('attributes_worktype') . '" style="float:left;color:white;"> Attributes > </a>' .   
	        '<a href="' .  $this->url('manage_attribute_options') . '?id=' . $wkat_id . '" style="float:left;color:white;"> Attribute Options > </a>' 
			. ' Edit';
    //fetch name based on id
    $table   = new \VuBib\Db\Table\WorkAttribute_Option($adapter);
    $row     = $table->findRecordById($id);
    $title   = $row['title'];
    $val     = $row['value'];
}
?>
<?php $escaper = new Zend\Escaper\Escaper('utf-8'); ?>
<div class="col-md-4">
<form class="form-horizontal" method="post" action="<?=$this->url('manage_attribute_options')?><?= '?id=' . $wkat_id ?>">
	<input type="hidden" name="action" value="<?=trim($action)?>">
	<input type="hidden" name="id" value="<?=trim($id)?>">
	<div class="form-group">   
		<label class="col-xs-2 control-label">Option: </label>
		<div class="col-xs-7">
			<input type="text" class="form-control" name="edit_option" id="editoption" value="<?=$escaper->escapeHtml($title)?>" />
		</div>
		<br /> <br />
		<label class="col-xs-2 control-label">Type: </label>
		<div class="col-xs-7">
			<input type="text" class="form-control" name="edit_value" id="editvalue" value="<?=$escaper->escapeHtml($val)?>" />
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<button type="submit" class="btn btn-default" name="submitt" value="Save">Save</button> 
			<button type="submit" class="btn btn-default" name="submitt" value="Cancel">Cancel</button>
		</div>
	</div>
</form>
</div>

