<?php
$this->headTitle('Manage Sub Attributes');
?>
<?php 
      $this->layout()->breadcrumbs .= '<a href="' . $this->url('attributes_worktype') . '" style="float:left;color:white;"> Attributes > </a>'
                                    . ' Sub Attributes';
 ?>
<?php
if ($request->getqueryParams('action') !== null) {
    $params = $request->getqueryParams();
    $attr_id = isset($params['wkat_id']) ? $params['wkat_id'] : $this->wkat_id;
    //fetch attribute name based on id
    $table = new \VuBib\Db\Table\WorkAttribute($adapter);
    $attr_row = $table->findRecordById($attr_id);
    $attribute = $attr_row['field'];
}
?>
<?php
/*$q_str = "";
$sort_ord = isset($_GET['sort_ord'])?($_GET['sort_ord']=="ASC"?"DESC":"ASC"):"ASC";
if ($request->getqueryParams()!= null) {
    $params = $request->getqueryParams();
    $q_str = $_SERVER["QUERY_STRING"];
    if(preg_match('/(?P<pg>page=\d+&)?(?P<action>.*)(?P<ord>&orderBy=\w+&sort_ord=\w+)/',$q_str,$matches)) {
        $q_str = preg_replace('/(?P<pg>page=\d+&)?(?P<action>.*)(?P<ord>&orderBy=\w+&sort_ord=\w+)/', $matches['action'], $q_str);
    }
}*/
?>
<script type='text/javascript'>
$(document).ready(function () {
	//Check if records are selected for delete
	$("#delSubAttrs").on('click', function () {
		if ($("#subAttrListTable input:checkbox:checked").length > 0) {
			// any one is checked
			return true;
		} else {
			// none is checked
			alert("No sub attribute(s) selected, Please select sub attribute(s) to delete.");
			return false;
		}
	});
});
</script>
<div class="col-md-9">
	<p><b style="font-size: 10pt; padding: 20px;">Attribute: <?php echo $attribute; ?></b></p> 
	<a href="<?=$this->url('new_subattribute')?><?='?id=' . $attr_id . '&action=new'?>"><b style="text-decoration: underline;">Add Sub Attribute</b></a>
	<form action="<?=$this->url('delete_subattribute')?><?='?action=delete'?>" method="post">
	<table class="table table-striped table-condensed" id="subAttrListTable" style="font-size:10pt;">
        <thead>
        <tr>
		  <th>&nbsp;&nbsp;</th>
		  <th>Sub Attribute</th>
        </tr>
        </thead>
        <tbody>
			<?php if($this->countp > 0) { ?>
			<?php 
            $escaper = new Zend\Escaper\Escaper('utf-8');
            foreach($this->rows as $row) :
                $output = (array)$row;
                $params = implode(', ', $output);
            ?>
			<tr>
				<td>
					<input type="checkbox" id="selSubAttr" name="selectSubAttr[]" value=<?=$row['id']?>>
				</td>
				<td>
					<a href="<?=$this->url('edit_subattribute')?><?='?wkat_id=' . $attr_id . '&id=' . $row['id'] . '&action=edit'?>">
					<?php echo $escaper->escapeHtml($row['subattribute']); ?></a>			
				</td>
			</tr>
			<?php endforeach; ?>
		<?php } ?>
        </tbody>
	</table>
	<input type="hidden" name="wkat_id" value="<?=$attr_id?>">
	<input type="submit" name="delSubAttrs" id="delSubAttrs" value="Delete">
	</form>
	<?php if($this->countp > 1) { ?>
		<form method="get" action="page">
			<?=$this->paginationControl($this->rows,
                'Sliding',
                'vubib::controls',
                [
                    'route' => 'manage_subattributes',
                    'extraParams' => $searchParams,
                ]
            );?>
		</form>
    <?php } ?> 
</div>