<?php $this->headTitle('Merge Publisher'); ?>
<?php 
	  $this->layout()->breadcrumbs .= '<a href="' .  $this->url('manage_publisher') . '" style="float:left;color:white;"> Publisher > </a>' 
	                                . ' Merge';
 ?>
<?php
$url_components = parse_url($this->serverUrl());
$url_host = $url_components['scheme'] . '://' . $url_components['host'];
?>
<script>
	//var ur = <?php echo json_encode($url_host); ?>;
	var ur = "";
    function addMergeButton(context) {
        if (($('#mrg_src_id', context).val().length != 0) && ($('#mrg_dest_id', context).val().length != 0)) {
            $('#submit_clear', context).before('<button type="submit" class="btn btn-default" name="submitt" id="submit_save" value="Save">Merge</button>');
            return false;
        }
    }
    $(document).ready(function () {
        $("#find_dest_pub").prop("disabled", "disabled");
        $("#dest_pub_find_bt").prop("disabled", "disabled");
        //source find
        $("#src_pub_find_bt").on('click', function () {
            var find_srcpub = $('#find_src_pub').val();
            $.ajax({
                method: 'post',
                //url: 'http://localhost<?= $this->url("get_work_details") ?>',
				url: ur + '<?=$this->url('get_work_details')?>',
                data: {
                    pub_name: find_srcpub
                },
                dataType: "json",
                cache: false,
                success: function (data) {
                    if ((data.pub_row.length) > 0) {
                        $('#src_find_outer_div').after('<div class="form-group" id="src_select_div">');
                        var src_result_table = '<table style="font-size:10pt; border-collapse: separate; border-spacing: 10px;" id="src_result_table">' +
                                '<tr><th>Select</th><th>Publisher Name</th><th>Works</th></tr>';
                        $.each(data.pub_row, function (key, val) {
                            src_result_table += '<tr><td><div class="radio"><label>' +
                                    '<input type="radio" id="src_select" name="src_select" value="' + val.id + '"></label>' + '</div></td>' +
                                    '<td>' + val.name + '</td><td>' + val.works + '</td></tr>';
                        });
                        src_result_table += '</table>';
                        $('#src_select_div').append(src_result_table);
                        $('#src_result_table').append('<button class="btn btn-default" name="btn_select_src" id="btn_select_src">Select</button>');
                    } else {
                        $('#find_src_pub').val('');
                    }
                },
                error: function (data) {}
            });
            return false;
        });
        //source select
        $(document).on('click', '#btn_select_src', function () {
            var src = $('input[name="src_select"]:checked').val();
            if (src !== null) {               
                //alert("selected src is " + src);
                //alert("name is " + fn);
                $("#find_dest_pub").prop("disabled", false);
                $("#dest_pub_find_bt").prop("disabled", false);              
                $('#mrg_src_id').val(src);
                //alert("hidden src " + $('#mrg_src_id').val());
				$.ajax({
					method: 'post',
                    //url: 'http://localhost<?= $this->url("get_work_details") ?>',
				    url: ur + '<?=$this->url('get_work_details')?>',
					data: {
						publisher_Id_locs: src
					},
					dataType: "json",
					cache: false,
					success: function (data) {
						if ((data.pub_locs.length) > 0) {
							$('#src_result_table').html('');
							$('#src_find_outer_div').after('<div class="form-group" id="src_loc_select_div">');
							var src_loc_result_table = '<table style="font-size:10pt; border-collapse: separate; border-spacing: 10px;" id="src_loc_result_table">' +
												'<tr><th>Move</th><th>Merge</th><th>Location</th><th>Works</th></tr>';
							$.each(data.pub_locs, function (key, val) {
								src_loc_result_table += '<tr><td>' +
											'<input type="radio" id="src_loc_mv_select" name="src_loc[' + val.id + ']" value="move">' + '</td>' +
											'<td>'+
											'<input type="radio" id="src_loc_mrg_select" name="src_loc[' + val.id + ']" value="merge">' + '</td>' +
											'<td>' + val.location + '</td><td>' + val.works + '</td></tr>';
							});
							src_result_table += '</table>';
							$('#src_loc_select_div').append(src_loc_result_table);
							//$('#src_loc_result_table').append('<button class="btn btn-default" name="btn_select_src" id="btn_select_src">Select</button>');
						} else {
							$('#src_result_table').html('');
						}
					},
					error: function (data) {}
				});
				/*
				var fn = $('input[name="src_select"]:checked').closest("tr").find('td:eq(1)').text() + ' ' +
                        $('input[name="src_select"]:checked').closest("tr").find('td:eq(2)').text();
				$('#src_find_outer_div').html('');
                $('#src_select_div').html('');
				$('#src_label').after('<br />' + fn);*/
               
                //addMergeButton(document);
            }
            return false;
        });
        //destination find
        $("#dest_pub_find_bt").on('click', function () {
            var find_dstpub = $('#find_dest_pub').val();
            $.ajax({
                method: 'post',
                //url: 'http://localhost<?= $this->url("get_work_details") ?>',
				url: ur + '<?=$this->url('get_work_details')?>',
                data: {
                    pub_name: find_dstpub
                },
                dataType: "json",
                cache: false,
                success: function (data) {
                    if ((data.pub_row.length) > 0) {
                        $('#dest_find_outer_div').after('<div class="form-group" id="dest_select_div">');
                        var dest_result_table = '<table style="font-size:10pt; border-collapse: separate; border-spacing: 10px;" id="dest_result_table">' +
                                '<tr><th>Select</th><th>Publisher Name</th><th>Works</th></tr>';
                        $.each(data.pub_row, function (key, val) {
                            if (("" + val.id) !== ($('#mrg_src_id').val())) {
                                dest_result_table += '<tr><td><div class="radio"><label>' +
                                        '<input type="radio" id="dest_select" name="dest_select" value="' + val.id + '"></label>' + '</div></td>' +
                                        '<td>' + val.name + '</td><td>' + val.works + '</td></tr>';
                            }
                        });
                        dest_result_table += '</table>';
                        $('#dest_select_div').append(dest_result_table);
                        $('#dest_result_table').append('<button class="btn btn-default" name="btn_select_dest" id="btn_select_dest">Select</button>');
                    } else {
                        $('#find_dest_pub').val('');
                    }
                },
                error: function (data) {}
            });
            return false;
        });
        //destination select
        $(document).on('click', '#btn_select_dest', function () {
            var dest = $('input[name="dest_select"]:checked').val();
            if (dest !== null) {
               /* var fn = $('input[name="dest_select"]:checked').closest("tr").find('td:eq(1)').text() + ' ' +
                        $('input[name="dest_select"]:checked').closest("tr").find('td:eq(2)').text();
                $('#dest_find_outer_div').html('');
                $('#dest_select_div').html('');
                $('#dest_label').after('<br />' + fn);*/
                //alert("hidden dest before " + $('#mrg_dest_id').val().length);
                $('#mrg_dest_id').val(dest);
                //alert("hidden dest now " + $('#mrg_dest_id').val().length);
				
				$.ajax({
					method: 'post',
                    //url: 'http://localhost<?= $this->url("get_work_details") ?>',
				    url: ur + '<?=$this->url('get_work_details')?>',
					data: {
						publisher_Id_locs: dest
					},
					dataType: "json",
					cache: false,
					success: function (data) {
						if ((data.pub_locs.length) > 0) {
							$('#dest_result_table').html('');
							$('#dest_find_outer_div').after('<div class="form-group" id="dest_loc_select_div">');
							var dest_loc_result_table = '<table style="font-size:10pt; border-collapse: separate; border-spacing: 10px;" id="dest_loc_result_table">' +
												'<tr><th>Move/Merge To</th><th>Location</th><th>Works</th></tr>';
							$.each(data.pub_locs, function (key, val) {
								dest_loc_result_table += '<tr><td>' +
											'<input type="radio" id="dest_loc_select" name="dest_loc_select" value="' + val.id + '">' + '</td>' +
											'<td>' + val.location + '</td><td>' + val.works + '</td></tr>';
							});
							src_result_table += '</table>';
							$('#dest_loc_select_div').append(dest_loc_result_table);
							//$('#src_loc_result_table').append('<button class="btn btn-default" name="btn_select_src" id="btn_select_src">Select</button>');
						} else {
							$('#dest_result_table').html('');
						}
					},
					error: function (data) {}
				});
				
                addMergeButton(document);
				
            }
            return false;
        });
        //check if src and dest are same
        $(document).on('click', '#submit_save', function () {
            if ($('#mrg_src_id').val() === $('#mrg_dest_id').val()) {
                $('.mergePubError').show();
                return false;
            }
        });
        $('#submit_clear').on('click', function () {
            location.reload(true);
        });
    });
</script>
<div class="col-lg-12">
    <form class="form-horizontal" name="merge_pub_form" id="merge_pub_form" method="post" action="<?= $this->url('manage_publisher') ?>">
        <input type="hidden" name="action" value="merge_publisher">
        <input type="hidden" name="mrg_src_id" id="mrg_src_id" value="">
        <input type="hidden" name="mrg_dest_id" id="mrg_dest_id" value="">
        <div class="form-group">
            <table style="font-size:10pt; border-collapse: separate; border-spacing: 10px;">        
                <tbody>
                    <tr>			
                        <td style="border-spacing: 10px;" id="src_find_col">				
                            <b id="src_label">Source Publisher</b><br>
                            <div class="form-group" id="src_find_outer_div">
                                <label class="col-xs-4 control-label">Find: </label>
                                <div class="col-xs-7">
                                    <input type="text" class="form-control" name="find_src_pub" id="find_src_pub" placeholder="enter publisher"/>
                                </div>	
                                <div class="col-xs-7">
                                    <button type="submit" class="btn btn-default" name="src_pub_find_bt" id="src_pub_find_bt" value="Save">Find</button>
                                </div>
                            </div>
                        </td>	
                        <td style="border-spacing: 10px;">
                            <b id="dest_label">Destination Publisher</b><br>
                            <div class="form-group" id="dest_find_outer_div">
                                <label class="col-xs-4 control-label">Find: </label>
                                <div class="col-xs-7">
                                    <input type="text" class="form-control" name="find_dest_pub" id="find_dest_pub" placeholder="enter publisher"/>
                                </div>
                                <div class="col-xs-7">
                                    <button type="submit" class="btn btn-default" name="dest_pub_find_bt" id="dest_pub_find_bt" value="Save">Find</button>
                                </div>
                            </div>
                        </td>			
                    </tr>
                </tbody>
            </table>		
        </div>	
        <div class="form-group">
            <div class="col-sm-offset-4 col-sm-10">
                <!--<button type="submit" class="btn btn-default" name="submit_save" id="submit_save" value="Save">Merge</button>-->
                <button type="reset" class="btn btn-default" name="submit_clear" id="submit_clear" value="Cancel">Clear</button>
                <p class="mergePubError" style="display:none;color:red;margin-bottom:20px;">Cannot merge -- source and destination are the same.</p>
            </div>
        </div>
    </form>
</div>