<?php
$this->headTitle('Edit Work');
?>
<?php 
	  $this->layout()->breadcrumbs .= '<a href="' .  $this->url('manage_work') . '" style="float:left;color:white;"> Work > </a>' 
	                                . ' Edit';
	  $this->layout()->page = "Work/edit?action=edit";
 ?>
<?php
$id;
if ($request->getqueryParams('id') !== null) {
    $params  = $request->getqueryParams();
    $action  = 'work_' . $params['action'];
    $id      = $params['id'];
    //fetch name based on id
    $table   = new \VuBib\Db\Table\Work($adapter);
    $wk_row  = $table->findRecordById($id);
    $type_id = $wk_row['type_id'];
    $status  = $wk_row['status'];    	
    //if ($status != 1) {
		//fetch parent work
		$pr_wrk = "";
		if (!is_null($wk_row['work_id'])) {
            //fetch name based on id
            $table   = new \VuBib\Db\Table\Work($adapter);
            $pr_wrk_row  = $table->findRecordById($wk_row['work_id']);
            $pr_wrk = $pr_wrk_row['title'];	
            $pr_wrk_id = $pr_wrk_row['id'];			
		}
        //fetch worktype based on id
        $table    = new \VuBib\Db\Table\WorkType($adapter);
        $wk_types = $table->findRecordById($type_id);
        $wk_type  = $wk_types['type'];
        
        //fetch worktypes
        $table      = new \VuBib\Db\Table\WorkType($this->adapter);
        $paginator  = $table->fetchAllWorkTypes();
        $itemsCount = $paginator->getTotalItemCount();
        $paginator->setItemCountPerPage($itemsCount);
        
        //fetch agent types
        $table            = new \VuBib\Db\Table\AgentType($this->adapter);
        $paginator_agtype = $table->fetchAgentTypes();
        $itemsCount       = $paginator_agtype->getTotalItemCount();
        $paginator_agtype->setItemCountPerPage($itemsCount);
        
        //fetch worktype values
        $table       = new \VuBib\Db\Table\Work_WorkAttribute($adapter);
        $attrs       = $table->findWorkAttributeTypesByWorkId($id);
        $wktyp_attrs = json_decode($attrs, true);

        //fetch folders
        $arr_fl = [];
        $table    = new \VuBib\Db\Table\Work_Folder($this->adapter);
        $wkfl_row = $table->findRecordsByWorkId($id);    

        //fetch publishers attached to work
        $table = new \VuBib\Db\Table\WorkPublisher($this->adapter);
        $pub_rows = $table->findRecordByWorkId($id);

		//fetch agents attached to work
		$table = new \VuBib\Db\Table\WorkAgent($this->adapter);
		$ag_rows = $table->findRecordByWorkId($id);
    //}
}
$url_components = parse_url($this->serverUrl());
$url_host = $url_components['scheme'] . '://' . $url_components['host'];
?>
<script type="text/javascript" src="<?=$this->url('home')?>js/work.js" ></script>
<style>
table[name="source_fl_table"] {
	font-size:10pt;
	border-collapse: separate;
	border-spacing: 10px;
	display: block;
}
tr[name="source_fl_row"], td[name="source_fl_col"] {
	vertical-align: top;
}
td[name="source_fl_col"] {
	border-spacing: 10px;
	display: inline-block;
}
.yrFrom, .yrTo {
	min-width: 80px;
	max-width: 80px;
}
input[name="pub_yrFrom"], input[name="pub_yrTo"] {
	width: 100%;
}
</style>
<script>
//var ur = <?php echo json_encode($url_host); ?>;
var ur = "";
var workURL = '<?=$this->url('get_work_details')?>';

$(document).ready(function () {	
	//get attributes for selected worktypes
	$('#work_type',document).on('change', function() {	
		bindWorkTypeAttributes(document,workURL);		
	});
		
	//Publisher
	//change publisher
	$("#pub_table").on('click','input[name="pub_name[]"]',function(){
		var rw = $(this).closest("tr");
		bindPublisherAutocomplete(rw,workURL);
		return false;
	});
	
	//add publisher rows
	$("#pub_add").click(function(){
		var pub_row = $('<tr name="pub_row[]"><input type="hidden" name="pub_id[]" id="pubId" value="">'+
							'<td><input type="text" class="form-control" name="pub_name[]" id="pubName" placeholder="none" /></td>'+
							'<input type="hidden" name="publoc_id[]" id="publoc_id" value="">'+
							'<td><select class="form-control pub_locations" name="pub_location[]" disabled><option value=""></option></select></td>'+
							'<td><button type="submit" class="btn btn-default" name="pub_remove" id="pub_remove" value="Remove">Remove</button></td>'+
							'<td class="yrFrom"><input type="text" class="form-control" name="pub_yrFrom[]" id="pubyrFrom"/></td>'+
							'<td class="yrTo"><input type="text" class="form-control" name="pub_yrTo[]" id="pubyrTo" /></td>'+
							'</tr>');				
							
        $("#pub_table").append(pub_row);
		bindPublisherAutocomplete(pub_row,workURL);
		return false;
    });
	//remove publisher rows
	$("#pub_table").on('click','#pub_remove',function(){
        $(this).parent().parent().remove();
    });
	//change publisher location
	$("#pub_table").on('change','.pub_locations',function(){
		var lc_chg = $(this).val();
		var rw = $(this).closest("tr");
		
		//rw.find('select').val(lc_chg);
		rw.find('input[name="publoc_id[]"]').val(lc_chg);		
		return false;
	});
	
	//agent auto complete
	<?php
	if(count($ag_rows) == 0) {
	?>
		bindAgentAutocomplete(document,workURL);
	<?php
	}
	?>
	
	$("#agent_add").click(function(){
		var agent_row = $('<tr><td><input type="hidden" name="agent_id[]" id="agentId" value="">'+
						'<select class="form-control agent_type" name="agent_type[]" id="agent_type">'+
						'<option value=""></option>'+
						<?php
						foreach($paginator_agtype as $row) :
						?>
						'<option value="<?=$row['id']?>"><?php echo $row['type']; ?></option>'+						
						<?php endforeach; ?>
						'</select>'+
						'</td>'+
						'<td><input type="text" class="form-control" name="agent_FirstName[]" id="agent_FirstName" /></td>'+
						'<td><input type="text" class="form-control" name="agent_LastName[]" id="agent_LastName" /></td>'+
						'<td><input type="text" class="form-control" name="agent_AlternateName[]" id="agent_AlternateName" /></td>'+
						'<td><input type="text" class="form-control" name="agent_OrganizationName[]" id="agent_OrganizationName" /></td>'+
						'<td><button type="submit" class="btn btn-default" name="agent_remove" id="agent_remove" value="Remove">Remove</button></td>'+
						'</tr>');				
							
        $("#agent_table").append(agent_row);
		//agent auto complete
		bindAgentAutocomplete(agent_row,workURL);
		return false;
    });
	//remove agent rows
	$("#agent_table").on('click','#agent_remove',function(){
        $(this).parent().parent().remove();
    });
	//classification
	//add classification rows
	$("#fl_add").on('click', function(){
		var fl_row = $('<tr name="source_fl_row[]">' +
						'<td><b>Subject Tree</b></td>' + 
						'<td class="source_fl_col" name="source_fl_col" id="source_fl_col">' +				
						'<select class="form-control select_source_fl select2" name="select_source_fl[]">' + 
						'<option value=""></option>' + 
						<?php
						$table = new \VuBib\Db\Table\Folder($this->adapter);
						$fl_siblings = $table->getFoldersWithNullParent();
						foreach($fl_siblings as $row) :
						?>
							'<option value="<?=$row['id']?>"><?php echo $row['text_fr']; ?></option>' + 							
						<?php endforeach; ?>
						'</select>' + 
						'</td>' + 
						'<td style="display: inline-block;"><button type="submit" class="btn btn-default" name="fl_remove" id="fl_remove" value="Remove">Remove</button></td>' + 
						'</tr>');
		$("#source_fl_table").append(fl_row);
		//bindSourceClassification(this,document,workURL);
		return false;
    });
	//remove classification rows
	$("#source_fl_table").on('click','#fl_remove',function(){
        $(this).parent().parent().remove();
    });
	$('table[name="source_fl_table"]').on('change',".select_source_fl", function() {
		var to_add_row = $(this).closest("tr");
		//to_add_row.children('td').children('select').eq(0).css('background-color','#8ec252');
		
		if($(this).val() == ""){
			to_add_row.find('.source_fl_col').eq(0).nextAll('.source_fl_col').remove();
			to_add_row.find('.source_fl_col').eq(0).val('');
			return false;
		}
		else
		{
			fl_changed = $(this).val();
			var no_of_fl_parent = to_add_row.find('.select_source_fl').length;
			for(var i = 0;i < no_of_fl_parent; i++)
			{
				if(to_add_row.find('.select_source_fl').eq(i).val() === fl_changed)
				{
					change_idx = i;
					folder_Id = to_add_row.find('.select_source_fl').eq(i).val();
					break;
				}
			}
			to_add_row.find('.source_fl_col').eq(change_idx).nextAll('.source_fl_col').remove();
			
			//no_of_fl_parent = $('.select_source_fl').length;
			no_of_fl_parent = to_add_row.find('.select_source_fl').length;
			$.ajax({
				method: 'post',
				//url: 'http://localhost<?=$this->url('get_work_details')?>',
				url: ur + workURL,
				data: {
					folder_Id: folder_Id
				},
				dataType: "json", 
				cache: false,
				success: function(data)
				{						
					if(data.folder_children.length > 0)
					{
					to_add_row.find('.source_fl_col').eq(no_of_fl_parent-1).after('<td class="source_fl_col" name="source_fl_col" id="source_fl_col"/>');
					
					_select = $('<select class="form-control select_source_fl select2" name="select_source_fl[]">');
					to_append = $('<option value=""></option>');
					$.each(data.folder_children, function (key, val) {
						to_append += '<option value="'+val.id+'">'+val.text_fr+'</option>';
					});
					_select.append($('<option />'));
					_select.append(to_append);

					to_add_row.find('.source_fl_col').eq(no_of_fl_parent).append(_select);
					to_add_row.find('.source_fl_col').eq(no_of_fl_parent).append('</select>');
					
					_select.on('change',function(){
						bindSourceClassification(this,document,workURL);
						return false;
					});	
					}
				},
				error: function (data) { 
					$("#Classification", context).html('<p>No Options</p>');
				}
			});	
			return false;
		}
	});
	//Parent Lookup
    $('#parentLookup_modal').on('shown.bs.modal', function() {
	    bindParentWork(document,workURL);
		return false;
    });   
       
	//Remove Parent Lookup
	$('.pr_work_div').on('click', '#parent_removeBtn', function() {
       $('#pr_work_lookup_id').val('');
	   $('.pr_work_div').html('');
	   $('.pr_work_div').append('<button type="button" class="btn btn-default parent_lookupBtn" name="parent_lookupBtn" id="parent_lookupBtn" ' +
				                'data-toggle="modal" data-target="#parentLookup_modal">Lookup</button>');
	   return false;
	});	
	//save
	$('#submit_save').on('click', function(){
		//var no_of_rows = $('table[name="source_fl_table"]').find("tr").length;
		var arr = [];
		var values;
		$('table[name="source_fl_table"]').each(function() {
			$(this).find('tr').each(function(){
				values = [];
				$(this).find('td').find('.select_source_fl').each(function(){
					//$(this).find('.select_source_fl').each(function(){
						values.push($(this).val());
					//});						
				});
				var newInput = $('<input type="hidden" name="arr[]" value="">');
				newInput.val(values);
				$("#edit-work-data").append(newInput);
			});
		});
		return true;
	});
});
</script>
<?php
    $usr = $this->isUser()->getUserType();
	$escaper = new Zend\Escaper\Escaper('utf-8');
    if (($status == 1) && ($usr['level'] == 'User')) {
        echo 'This work has been completed, you do not have access to edit this.';
	?>
	    	    <div style="float: left; margin: 20px 5px 0px 5px;">
        <table style="font-size:10pt; border-collapse: separate; border-spacing: 10px;">
            <tr>
            <th align="right">Title: </th>
            <td><?php echo $escaper->escapeHtml($wk_row['title']); ?></td>
            </tr>
            <tr>
            <th align="right">SubTitle: </th>
            <td><?php echo $escaper->escapeHtml($wk_row['subtitle']); ?></td>
            </tr>
            <tr>
            <th align="right">Parallel Title: </th>
            <td><?php echo $escaper->escapeHtml($wk_row['paralleltitle']); ?></td>
            </tr>
            <tr>
            <th align="right">Description: </th>
            <td><?php echo $escaper->escapeHtml($wk_row['description']); ?></textarea></td>
            </tr>
            <th align="right">Parent Work: </th>
            <td>
			<?php 
			     //echo $escaper->escapeHtml($wk_row['description']); 
				 echo $escaper->escapeHtml($pr_wrk);
			?></textarea>
		    </td>
            </tr>
            <tr>
            <th align="right" valign="top">Agent: </th>
            <td>
                <table style="font-size:10pt; border-collapse: separate; border-spacing: 10px;">
                <tr bgcolor="#CCCCCC" align="left">
                <th>Agent Type</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Alternate Name</th>
                <th>Organization Name</th>
                </tr>
                <?php
                //fetch agents attached to work
                //$table = new \VuBib\Db\Table\WorkAgent($this->adapter);
                //$ag_rows = $table->findRecordByWorkId($id);
                if(count($ag_rows) > 0)
                {
                    for($i = 0;$i < count($ag_rows);$i++)
                    {
				?>
                        <tr>
                        <td width="100" style="border-bottom: solid 1px #CCCCCC;"><?php echo $escaper->escapeHtml($ag_rows[$i]['type']); ?></td>
                        <td width="110" style="border-bottom: solid 1px #CCCCCC;"><?php echo $escaper->escapeHtml($ag_rows[$i]['fname']); ?></td>
                        <td width="110" style="border-bottom: solid 1px #CCCCCC;"><?php echo $escaper->escapeHtml($ag_rows[$i]['lname']); ?></td>
                        <td width="130" style="border-bottom: solid 1px #CCCCCC;"><?php echo $escaper->escapeHtml($ag_rows[$i]['alternate_name']); ?></td>
                        <td width="150" style="border-bottom: solid 1px #CCCCCC;"><?php echo $escaper->escapeHtml($ag_rows[$i]['organization_name']); ?></td>
                        </tr>
			   <?php
					}
				}
				?>
               </table>
           </td>
           </tr>
            <tr>
            <th align="right" valign="top">Publisher: </th>
            <td>
                <table style="font-size:10pt; border-collapse: separate; border-spacing: 10px;">
                <tr bgcolor="#CCCCCC" align="left">
                <th>Publisher</th>        
                <th>Location</th>
                <th>Year From</th>
                <th>Year To</th>  
                </tr>
                <?php
		        if(count($pub_rows) != 0)
		        {
			        for($i = 0;$i < count($pub_rows);$i++)
			        {
		?>
                        <tr>
                        <td width="100" style="border-bottom: solid 1px #CCCCCC;"><?php echo $escaper->escapeHtml($pub_rows[$i]['name']); ?></td>
                        <td width="130" style="border-bottom: solid 1px #CCCCCC;"><?php echo $escaper->escapeHtml($pub_rows[$i]['location']); ?></td>
                        <td width="110" style="border-bottom: solid 1px #CCCCCC;"><?php echo $escaper->escapeHtml($pub_rows[$i]['publish_year']); ?></td>
                        <td width="110" style="border-bottom: solid 1px #CCCCCC;"><?php echo $escaper->escapeHtml($pub_rows[$i]['publish_year_end']); ?></td>
                        </tr>
			   <?php
					}
				}
				?>
                </table>
            </td>
            </tr>
            <tr>
            <th align="right" valign="top">Subject Tree: </th>
			<td>
                <table style="font-size:10pt; border-collapse: separate; border-spacing: 10px;">
            <?php
				if(count($wkfl_row) >= 1)
				{
					$wkfl_row = array_reverse($wkfl_row);
					foreach($wkfl_row as $row):
				?>
				        <tr>
						<td>
				<?php
						$table = new \VuBib\Db\Table\Folder($this->adapter);
						$arr_fl = $table->getParentChain($row['folder_id']);
						for($i = 0; $i < count($arr_fl); $i++)
						{
							$table = new \VuBib\Db\Table\Folder($this->adapter);
							$fl = $table->findRecordById($arr_fl[$i]);
							echo $fl['text_fr'] . '>';
						}
				?>
                        </td>
				        </tr>
				<?php
					endforeach;
				}
            ?>
                </table>
			</td>
			</tr>
            <tr>
            <th align="right">Type: </th>
            <td><?php echo $wk_type; ?></td>
            </tr>
			<tr>
			<?php
			   $table = new \VuBib\Db\Table\WorkAttribute($this->adapter);
               $pg_wkt = $table->getAttributesForWorkType($type_id);
               $itemsCount = $pg_wkt->getTotalItemCount();
               $pg_wkt->setItemCountPerPage($itemsCount);
               foreach ($pg_wkt as $row) :
		   ?>
		           <tr>
				   <th align="right"><?php echo $row['field'] . ':'; ?></th>
				   <?php
				   $table = new \VuBib\Db\Table\Work_WorkAttribute($this->adapter);
				   $rec = $table->getRecord($id,$row['id']);
				   if(count($rec) >= 1)
				   {
					   if($row['type'] == 'Select')
					   {
						  $table = new \VuBib\Db\Table\WorkAttribute_Option($this->adapter);
				          $rc = $table->findRecordById($rec['value']); 
				   ?>
				          <td><?php echo $rc['title']; ?></td>
				   <?php
					   }
					   else
					   {
				   ?>
				       <td><?php echo $rec['value']; ?></td>
				   <?php
				       }
				   }
				   ?>
				   </tr>
	       <?php
               endforeach;
			?>
			</tr>
        </table>
		</div>
	<?php
	}
	else
	{
?>
<div class="col-md-10">
<form id="edit-work-data" class="form-horizontal" method="POST" action="<?=$this->url('manage_work')?>">
<input type="hidden" name="id" value="<?=$id?>">
<input type="hidden" name="action" value="<?=$action?>">
<?php 
	//get user
	$user = $this->isUser()->getUser();
?>
<input type="hidden" name="user" id="user" value="<?=$user?>">
<div class="tabbable">
	<ul class="nav nav-tabs">
		<li class="active">
			<a href="#General" data-toggle="tab">General</a>
		</li>
		<li>
			<a href="#Classification" data-toggle="tab">Classification</a>
		</li>  
		<li>
			<a href="#Publisher" data-toggle="tab">Publisher</a>
		</li>
		<li>
			<a href="#Agents" data-toggle="tab">Agents</a>
		</li>
		<li>
			<a href="#Citation" data-toggle="tab">Citation</a>
		</li>
	</ul>
	<div class="tab-content">
    <div class="tab-pane active" id="General">      
		<div class="form-group required">
			<label class="col-xs-2 control-label">Title: </label>
			<div class="col-xs-10">
				<input type="text" class="form-control" name="edit_worktitle" id="editworktitle" required="true" value="<?=$escaper->escapeHtml($wk_row['title'])?>"/>
			</div>
		</div>
		<div class="form-group">
			<label class="col-xs-2 control-label">Sub Title: </label>
			<div class="col-xs-10">
				<input type="text" class="form-control" name="edit_worksubtitle" id="editworksubtitle" value="<?=$escaper->escapeHtml($wk_row['subtitle'])?>"/>
			</div>
		</div>
		<div class="form-group">
			<label class="col-xs-2 control-label">Parallel Title: </label>
			<div class="col-xs-10">
				<input type="text" class="form-control" name="edit_workparalleltitle" id="editworkparalleltitle" value="<?=$escaper->escapeHtml($wk_row['paralleltitle'])?>"/>
			</div>
		</div>
		<div class="form-group">
			<label class="col-xs-2 control-label">Description: </label>
			<div class="col-xs-10">
				<textarea class="form-control" placeholder="Message" name="description" id="description"><?php echo $escaper->escapeHtml($wk_row['description']); ?></textarea>
			</div>
		</div>
		<div class="form-group">
			<label class="col-xs-2 control-label">Type: </label>
			<div class="col-xs-10">
				<select class="form-control" name="edit_work_type" id="work_type" required="true">
				<option value="<?=$wk_row['type_id']?>"><?php echo $escaper->escapeHtml($wk_type); ?></option>					
				<?php
				foreach($paginator as $row) :
					if($row['type'] != $wk_type)
					{
				?>
						<option value="<?=$row['id']?>"><?php echo $escaper->escapeHtml($row['type']); ?></option>							
				<?php 
					}
				endforeach; 
				?>
				</select>
			</div>
		</div>
		<div class="form-group">
            <label class="col-xs-2 control-label">Parent Work: </label>
			    <input type="hidden" name="pr_work_lookup_id" id="pr_work_lookup_id" value="<?=isset($pr_wrk_id)?$pr_wrk_id:""?>">
                <div class="col-xs-10 pr_work_div">
				    <?php
					if ($pr_wrk !== "") {
						echo $pr_wrk; ?>
                        <button type="button" class="btn btn-default parent_Chng_Btn" name="parent_changeBtn" id="parent_changeBtn"
					            data-toggle="modal" data-target="#parentLookup_modal">Change</button> 
                       <button type="button" class="btn btn-default parent_Rmv_Btn" name="parent_removeBtn"
					           id="parent_removeBtn">Remove</button>
					<?php
					} else {?>
                    <button type="button" class="btn btn-default parent_lookupBtn" name="parent_lookupBtn" id="parent_lookupBtn" 
					        data-toggle="modal" data-target="#parentLookup_modal">Lookup</button>
					<?php } ?>
                </div>
				<!-- Parent work Lookup -->
                <div class="modal fade ig" id="parentLookup_modal" role="dialog">
                <div class="modal-dialog ig">
                    <div class="modal-content ig">
                        <div class="modal-header ig">
                            <button type="button" class="close ig" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title ig" id="parentLookup_modalLabel">Lookup</h4>
                        </div>
                        <div class="modal-body ig">
                             <div class="form-group ig">
                                <label class="col-xs-2 control-label ig">Title: </label>
                                <div class="col-xs-10 ig">
                                    <input type="text" class="form-control ig parent_title" name="parent_title" id="parent_title" />
                                </div>
                            </div>
                            <div class="form-group ig">
                                <div class="col-sm-offset-2 col-sm-10 ig">
                                    <button type="button" class="btn btn-primary ig parent_lookup_search" id="parentLookup_search">Search</button>
                                </div>
                            </div>
                            <div class="pr_work_results ig">
                            </div>
						</div>
						<div class="modal-footer ignore ig">
                            <button type="button" class="btn btn-default option_lookup_close ig" data-dismiss="modal">Close</button>
                        </div>
					</div>
                </div>
                </div>
		</div>
		<div class="form-group">
			<label class="col-xs-2 control-label">Status: </label>
			<div class="col-xs-10">
				<div class="radio">
					<label class="radio"><input type="radio" id="editworkstatus" name="edit_workstatus" value="00" <?php echo (is_null($status))?'checked':'' ?>>In Progress</label>
					<label class="radio"><input type="radio" id="editworkstatus" name="edit_workstatus" value="0" <?php echo ($status === 0)?'checked':'' ?>>Pending Review</label>
					<label class="radio"><input type="radio" id="editworkstatus" name="edit_workstatus" value="2" <?php echo ($status == 2)?'checked':'' ?>>Unseen Source Doc</label>
                    <?php if ($usr['level'] != 'User') { ?>
					<label class="radio"><input type="radio" id="editworkstatus" name="edit_workstatus" value="1" <?php echo ($status == 1)?'checked':'' ?>>Complete</label>
					<?php } ?>
				</div>
			</div>
		</div>		 
    </div>
	<div class="tab-pane" id="Classification">
		<div class="form-group">
			<table name="source_fl_table" id="source_fl_table"> 
			<!--<th>Subject Tree</th>-->
			<tbody>
				<?php
				if(count($wkfl_row) >= 1)
				{
					$wkfl_row = array_reverse($wkfl_row);
					foreach($wkfl_row as $row):
						$table = new \VuBib\Db\Table\Folder($this->adapter);
						$arr_fl = $table->getParentChain($row['folder_id']);
					?>
						<tr name="source_fl_row[]">
						<td><b>Subject Tree</b><br></td>					
						<?php
						for($i = 0; $i < count($arr_fl); $i++)
						{
							$table = new \VuBib\Db\Table\Folder($this->adapter);
							$fl = $table->findRecordById($arr_fl[$i]);
						?>
							<td class="source_fl_col" name="source_fl_col" id="source_fl_col">
							<select class="form-control select_source_fl select2" name="select_source_fl[]">
							<option value="<?=$fl['id']?>" selected><?php echo $fl['text_fr']; ?></option>
							<?php
							$table = new \VuBib\Db\Table\Folder($this->adapter);
							$fl_siblings = $table->getSiblings($fl['parent_id']);
							foreach($fl_siblings as $row) :
								if($row['id'] != $arr_fl[$i])
								{
							?>
									<option value="<?=$row['id']?>"><?php echo $row['text_fr']; ?></option>
							<?php
								}
							endforeach;
							?>
							</select>
							</td>
							<?php
							if($i == (count($arr_fl)-1))
							{
								$table = new \VuBib\Db\Table\Folder($this->adapter);
								$chl_rows = $table->getChild($arr_fl[$i]);
								if(count($chl_rows) != 0)
								{
							?>
									<td class="source_fl_col" name="source_fl_col" id="source_fl_col" style="vertical-align: top; border-spacing: 10px;">
									<select class="form-control select_source_fl select2" name="select_source_fl[]">
									<option value=""></option>
									<?php
									foreach($chl_rows as $row) :
									?>
										<option value="<?=$row['id']?>"><?php echo $row['text_fr']; ?></option>
									<?php
									endforeach;
								}
							}
						}
						?>
						<td style="display: inline-block;"><button type="submit" class="btn btn-default" name="fl_remove" id="fl_remove" value="Remove">Remove</button></td>
						</tr>
					<?php
					endforeach;
				}
				else
				{
				?>		
					<tr name="source_fl_row[]">
						<b>Subject Tree</b><br>
						<td class="source_fl_col" name="source_fl_col" id="source_fl_col">				
							<select class="form-control select_source_fl select2" name="select_source_fl[]">
							<option value=""></option>
							<?php
							$table = new \VuBib\Db\Table\Folder($this->adapter);
							$fl_siblings = $table->getFoldersWithNullParent();
							foreach($fl_siblings as $row) :
							?>
								<option value="<?=$row['id']?>"><?php echo $row['text_fr']; ?></option>							
							<?php 
							endforeach; ?>
							</select>
						</td>
						<td style="display: inline-block;"><button type="submit" class="btn btn-default" name="fl_remove" id="fl_remove" value="Remove">Remove</button></td>
					</tr>
				<?php
				}
				?>	
			</tbody>
			</table>
			<button type="submit" class="btn btn-default" name="fl_add" id="fl_add" value="Add">Add</button>
		</div>		
    </div>
	<div class="tab-pane" id="Publisher">
		<div class="form-group">
		<table class="table table-striped table-condensed" name="pub_table" style="font-size:10pt;" id="pub_table">
        <thead>
			<th>Publisher</th>        
			<th>Location</th>
			<th>Year From</th>
			<th>Year To</th>  
			<th>Remove</th>
		</thead>
		<tbody>
		<?php
		if(count($pub_rows) != 0)
		{
			for($i = 0;$i < count($pub_rows);$i++)
			{
		?>
				<tr name="pub_row[]">
					<input type="hidden" name="pub_id[]" id="pubId" value="<?=$pub_rows[$i]['publisher_id']?>" />
					<td><input type="text" class="form-control" name="pub_name[]" id="pubName"  value="<?=$pub_rows[$i]['name']?>" /></td>	
					<input type="hidden" name="publoc_id[]" id="publoc_id" value="<?=$pub_rows[$i]['location_id']?>">
					<td>						
					<?php
						if(!is_null($pub_rows[$i]['location_id']))
						{
					?>		
							<select class="form-control pub_locations" name="pub_location[]" id="pubLocation">					
								<option value="<?=$pub_rows[$i]['location_id']?>"><?php echo $pub_rows[$i]['location']; ?></option>	
								<?php
								$table = new \VuBib\Db\Table\PublisherLocation($this->adapter);
								$loc_rows = $table->getPublisherLocations($pub_rows[$i]['publisher_id']);
								//var_dump($loc_rows);
								foreach($loc_rows as $row):
									
									if($row['id'] != $pub_rows[$i]['location_id'])
									{
										//echo $row['id'] . " and " . $pub_rows[$i]['location_id'];
								?>
										<option value="<?=$row['id']?>"><?php echo $row['location']; ?></option>	
								<?php
									}
								endforeach;
						}
						else
						{
						?>
							<select class="form-control pub_locations" name="pub_location[]" id="pubLocation" disabled>
							<option value=""></option>
						<?php
						}
					?>
					</select>
					</td>
					<td><input type="text" class="form-control" name="pub_yrFrom[]" id="pubyrFrom"  
								value="<?=$pub_rows[$i]['publish_year'] == 0 ? NULL : $pub_rows[$i]['publish_year']?>" /></td>
					<td><input type="text" class="form-control" name="pub_yrTo[]" id="pubyrTo"  
								value="<?=$pub_rows[$i]['publish_year_end'] == 0 ? NULL : $pub_rows[$i]['publish_year_end']?>" /></td>	
					<td><button type="submit" class="btn btn-default" name="pub_remove" id="pub_remove" value="Remove">Remove</button></td>
				</tr>
			<?php
			}
		}
		else
		{
		?>		
			<tr name="pub_row[]">
				<input type="hidden" name="pub_id[]" id="pubId" value="">
				<td><input type="text" class="form-control" name="pub_name[]" id="pubName" placeholder="none" /></td>
				<input type="hidden" name="publoc_id[]" id="publoc_id" value="">
				<td>
					<select class="form-control pub_locations" name="pub_location[]" id="pubLocation" disabled>
					<option value=""></option>				
					</select>
				</td>
				<td class="yrFrom"><input type="text" class="form-control" name="pub_yrFrom[]" id="pubyrFrom"/></td>
				<td class="yrTo"><input type="text" class="form-control" name="pub_yrTo[]" id="pubyrTo" /></td>
				<td><button type="submit" class="btn btn-default" name="pub_remove" id="pub_remove" value="Remove">Remove</button></td>
			</tr>
		<?php
		}
		?>
		</tbody>
		</table>
		<button type="submit" class="btn btn-default" name="pub_add" id="pub_add" value="Add">Add</button> 
		</div>
	</div>
	<div class="tab-pane" id="Agents">
		<div class="form-group">
		<table class="table table-striped table-condensed" style="font-size:10pt;" id="agent_table">
        <thead>
          <th>Agent Type</th>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Alternate Name</th>
		  <th>Organization Name</th>
          <th>Remove</th>
		</thead>
		<tbody>	
		<?php
		if(count($ag_rows) > 0)
		{
			for($i = 0;$i < count($ag_rows);$i++)
			{
		?>		<tr>
					<td>
						<input type="hidden" name="agent_id[]" id="agentId" value="<?=$ag_rows[$i]['agent_id']?>">
						<select class="form-control agent_type" name="agent_type[]" id="agent_type">
						<option value="<?=$ag_rows[$i]['agenttype_id']?>"><?php echo $ag_rows[$i]['type']; ?></option>
						<?php
							foreach($paginator_agtype as $row) :
								if($row['id'] != $ag_rows[$i]['agenttype_id'])
								{
						?>
									<option value="<?=$row['id']?>"><?php echo $row['type']; ?></option>						
						<?php 
								}
							endforeach; 
						?>
						</select>
					</td>
				<td>
					<?php
					if($ag_rows[$i]['fname'] == "" || $ag_rows[$i]['fname'] == NULL)
					{
					?>
						<input type="text" class="form-control" name="agent_FirstName[]" id="agent_FirstName" 
								value="" disabled />
					<?php
					}
					else
					{
					?>
						<input type="text" class="form-control" name="agent_FirstName[]" id="agent_FirstName" 
								value="<?=$ag_rows[$i]['fname']?>" disabled />
					<?php
					}
					?>
				</td>
				<td>
					<?php
					if($ag_rows[$i]['lname'] == "" || $ag_rows[$i]['lname'] == NULL)
					{
					?>
						<input type="text" class="form-control" name="agent_FirstName[]" id="agent_FirstName" 
								value="" disabled />
					<?php
					}
					else
					{
					?>
						<input type="text" class="form-control" name="agent_LastName[]" id="agent_LastName" 
								value="<?=$ag_rows[$i]['lname']?>" disabled />
					<?php
					}
					?>
				</td>
				<td>
					<?php
					if($ag_rows[$i]['alternate_name'] == "" || $ag_rows[$i]['alternate_name'] == NULL)
					{
					?>
						<input type="text" class="form-control" name="agent_FirstName[]" id="agent_FirstName" 
								value="" disabled />
					<?php
					}
					else
					{
					?>
						<input type="text" class="form-control" name="agent_AlternateName[]" id="agent_AlternateName" 
								value="<?=$ag_rows[$i]['alternate_name']?>" disabled />
					<?php
					}
					?>
				</td>
				<td>
					<?php
					if($ag_rows[$i]['organization_name'] == "" || $ag_rows[$i]['organization_name'] == NULL)
					{
					?>
						<input type="text" class="form-control" name="agent_FirstName[]" id="agent_FirstName" 
								value="" disabled />
					<?php
					}
					else
					{
					?>
						<input type="text" class="form-control" name="agent_OrganizationName[]" id="agent_OrganizationName" 
								value="<?=$ag_rows[$i]['organization_name']?>" disabled />
					<?php
					}
					?>
				</td>
				<td><button type="submit" class="btn btn-default" name="agent_remove" id="agent_remove" value="Remove">Remove</button></td>
			</tr>
		<?php		
			}
		}
		else
		{
		?>
			<tr>
				<td>
					<input type="hidden" name="agent_id[]" id="agentId" value="">
					<select class="form-control agent_type" name="agent_type[]" id="agent_type">
					<option value=""></option>
					<?php
						foreach($paginator_agtype as $row) :
					?>
							<option value="<?=$row['id']?>"><?php echo $row['type']; ?></option>						
					<?php 
						endforeach; 
					?>
					</select>
				</td>
				<td><input type="text" class="form-control" name="agent_FirstName[]" id="agent_FirstName" /></td>
				<td><input type="text" class="form-control" name="agent_LastName[]" id="agent_LastName" /></td>
				<td><input type="text" class="form-control" name="agent_AlternateName[]" id="agent_AlternateName" /></td>
				<td><input type="text" class="form-control" name="agent_OrganizationName[]" id="agent_OrganizationName" /></td>
				<td><button type="submit" class="btn btn-default" name="agent_remove" id="agent_remove" value="Remove">Remove</button></td>
			</tr>
		<?php
		}
		?>
		</tbody>
		</table>
		<button type="submit" class="btn btn-default" name="agent_add" id="agent_add" value="Add">Add</button> 
		</div>
    </div>
	<div class="tab-pane" id="Citation">
		<!--<div class="form-group" id="divforoptions">
		</div>-->
		<!-- Work Type Attribute Options Lookup -->
		<div class="modal fade ig" id="optionsLookup" role="dialog">
		<div class="modal-dialog ig">
		<div class="modal-content ig">
			<div class="modal-header ig">
				<button type="button" class="close ig" data-dismiss="modal">&times;</button>
				<h4 class="modal-title ig" id="myModalLabel">Lookup</h4>
			</div>
			<div class="modal-body ig">
				<div class="form-group ig">
				<label class="col-xs-2 control-label ig">Title: </label>
				<div class="col-xs-10 ig">
					<input type="text" class="form-control ig" name="lookup_Option" id="lookupOption" />
				</div>
				</div>
				<div class="form-group ig">
				<div class="col-sm-offset-2 col-sm-10 ig">
				<button type="button" class="btn btn-primary option_search ig" id="option_search">Search</button>
				</div>
				</div>
				<div class="option_results ig">
				</div>
			</div>
			<div class="modal-footer ignore ig">
				<button type="button" class="btn btn-default option_lookup_close ig" data-dismiss="modal">Close</button>
			</div>
		</div>
		</div>
		</div>

		<script>
		//var ur = <?php echo json_encode($url_host); ?>;
		var ur = "";
		function setValues(context)
		{
			var title = "";
			<?php
			for($i = 0; $i < count($wktyp_attrs); $i++)
			{
			?>				
			<?php
				if(strtolower($wktyp_attrs[$i]['type']) == strtolower('select'))
				{
						$table = new \VuBib\Db\Table\WorkAttribute_Option($adapter);
						//$wkopt = (array)$table->getOptionTitle($wktyp_attrs[$i]['value'], $wktyp_attrs[$i]['workattribute_id']);
						$wkopt = $table->findRecordById($wktyp_attrs[$i]['value']); 
			?>
						title = <?php echo json_encode($wkopt['title']); ?>;
						opt_id = <?php echo json_encode($wkopt['id']); ?>;
						var opt = <?php echo json_encode("wkatid," . $wktyp_attrs[$i]['workattribute_id']); ?>;
						sel_opt = $('input[name="' + opt + '"]');
						$('input[name="' + opt + '"]').attr('name', sel_opt.attr('name') + 'optid,' + opt_id);
						sel_opt.val(title);
			<?php
				}
				else if($wktyp_attrs[$i]['type'] == 'Textarea')
				{
				?>
					title =  <?php echo json_encode($escaper->escapeHtml($wktyp_attrs[$i]['value'])); ?>;
					$('textarea[name="' + <?php echo json_encode("wkatid," . $wktyp_attrs[$i]['workattribute_id']); ?> + '"]').val(title);
				<?php					
				}
				else if($wktyp_attrs[$i]['type'] == 'RadioButton')
				{
				?>
					title =  <?php echo json_encode($wktyp_attrs[$i]['value']); ?>;
					if(title == "true")
					{
						$('input[id="' + <?php echo json_encode("t:" . $wktyp_attrs[$i]['workattribute_id']); ?> + '"]').prop("checked",true);
					}
					if(title == "false")
					{
						//$('input[id="' + <?php echo json_encode("f:" . $wktyp_attrs[$i]['workattribute_id']); ?> + '"]').css("background","#8ec252");
						$('input[id="' + <?php echo json_encode("f:" . $wktyp_attrs[$i]['workattribute_id']); ?> + '"]').prop("checked",true);
					}
				<?php
				}
				else
				{
				?>
					title =  <?php echo json_encode($wktyp_attrs[$i]['value']); ?>;
					$('input[name="' + <?php echo json_encode("wkatid," . $wktyp_attrs[$i]['workattribute_id']); ?> + '"]').val(title);
				<?php
				}
			}
			?>
			return false;
		}
		$(document).ready(function () {
			var worktype_Id = $('#work_type').val();
			$.ajax({
				method: 'post',
				//url: 'http://localhost<?=$this->url('get_work_details')?>',
				url: ur + workURL,
				data: {
					worktype_Id: worktype_Id
				},
				dataType: "json", 
				cache: false,
				success: function(data)
				{
					$.each(data.worktype_attribute, function (key, val) {				
					$("<div />").attr("class","form-group optiondiv").attr("id","optiondiv").appendTo("#Citation");
					$("<label />").attr("class","col-xs-2 control-label").text(val.field).appendTo("#Citation");
					//$("</label>").appendTo("#divforoptions");
					$("<div />").attr("id","optionfieldsdiv").appendTo("#Citation");
					// append input control at end of form
					if(val.type == 'Textarea')
					{
						$("<textarea />")
							.attr("class","form-control")
							.attr("id", val.field)
							.attr("name", 'wkatid,' + val.id)
							.appendTo("#Citation");
						//$("</textarea>").appendTo("#divforoptions");
					}
					if(val.type == 'Text')
					{
						$("<input />")
							.attr("type","text")
							.attr("class","form-control")
							.attr("id", val.field)
							.attr("name", 'wkatid,' + val.id)
							.appendTo("#Citation");
					}	
					if(val.type == 'RadioButton')
					{
						$('<div class="radio">' +
							'<label class="radio"><input type="radio" id="t:' + val.id + '" name="wkatid,' + val.id + '" value="true" />True</label>' + 
							'<label class="radio"><input type="radio" id="f:' + val.id + '" name="wkatid,' + val.id + '" value="false" />False</label>' + 
							'</div>').appendTo("#Citation");
					}
					if(val.type == 'Select')
					{
						var container = $('<div/>');
						$("<input />")
							.attr("type","text")
							.attr("class","form-control Attributeoption")
							.attr("id", val.field + ':' + val.id)
							.attr("name", 'wkatid,' + val.id)
							.appendTo(container);
						$("<button data-toggle='modal' data-target='#pubLookup'/>")
							.attr("class","btn btn-default optionLookupBtn")
							.attr("id","optionLookupBtn")
							.attr("data-toggle","modal")
							.attr("data-target","optionsLookup")
							.attr("value","Lookup")
							.text("Lookup")
							.appendTo(container);	
						container.appendTo('#Citation');
					}	
					})			
					$(".optionLookupBtn").on('click', function(e){
						// show Modal
						var lookupBtn = this;
						attr_option_lookup = $(lookupBtn).prev();
						$("#optionsLookup").modal('show');
						$('#optionsLookup').on('shown.bs.modal', function () {
							$('#lookupOption').focus()
							$('.option_search').on('click', function(e) {					
								//var attribute_Id = $(lookupBtn).prev().attr('id');
								var attribute_Id = attr_option_lookup.attr('id');
								var option = $('#lookupOption').val();
								$.ajax({
									method: 'post',
									//url: 'http://localhost<?=$this->url('get_work_details')?>',
									url: ur + '<?=$this->url('get_work_details')?>',
									data: {
										option: option,
										attribute_Id: attribute_Id
									},
									dataType: "json", 
									cache: false,
									success: function(data)
									{
										$(".option_results",document).html('');
										$(".option_results",document).append('<p>Search Results</p>');
										$.each(data.attribute_options, function (key, val) {
											$(".option_results",document).append('<p><a name="'+val.id+'" href="'+ val.title +'" class="link_options">' + val.title + '</a></p>');
										})
									},
									error: function () { 
										$(".option_results",document).append('<p>None available</p>');
									}
								});	
								$(document).off('click', '.link_options');
								$(document).on("click", ".link_options", function(e) {
									var linkval = $(this).attr('href');
									attr_option_lookup.val(linkval);
									attr_option_lookup.attr('name', attr_option_lookup.attr('name') + 'optid,' + $(this).attr('name'));
									console.log(attr_option_lookup.attr('name'));
									$('#lookupOption').val('');
									$(".option_results",document).html('');	
									$('.option_lookup_close').trigger('click');																
									return false;
								});
							});
						});
						return false;
					});
					setValues(document);
				},
				error: function (data) { 
					$("#Citation", document).html('<p>No Options</p>');
				}
			});
			return false;
		});
		</script>
		
	</div>
</div>
<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<button type="submit" class="btn btn-default" name="submit_save" id="submit_save" value="Save">Save</button> 
        <button type="submit" class="btn btn-default" name="submit_cancel" value="Cancel">Cancel</button>
	</div>
  </div>
</form>
</div>
<?php
	}
?>