<?php $this->headTitle('New Work'); ?>
<?php 
	  $this->layout()->breadcrumbs .= '<a href="' .  $this->url('manage_work') . '" style="float:left;color:white;"> Work > </a>' 
	                                . ' New';
	  $this->layout()->page = "Work/New";
 ?>
<?php
//fetch worktypes
$table = new \VuBib\Db\Table\WorkType($this->adapter);
$paginator = $table->fetchAllWorkTypes();
$itemsCount = $paginator->getTotalItemCount();
$paginator->setItemCountPerPage($itemsCount);

//fetch agent types
$table = new \VuBib\Db\Table\AgentType($this->adapter);
$paginator_agtype = $table->fetchAgentTypes();
$itemsCount_ag = $paginator_agtype->getTotalItemCount();
$paginator_agtype->setItemCountPerPage($itemsCount_ag);

//get url host
$url_components = parse_url($this->serverUrl());
$url_host = $url_components['scheme'] . '://' . $url_components['host'];
?>
<script type="text/javascript" src="<?=$this->url('home')?>js/work.js" ></script>
<style>
table[name="source_fl_table"] {
	font-size:10pt;
	border-collapse: separate;
	border-spacing: 10px;
	display: block;
}
tr[name="source_fl_row"], td[name="source_fl_col"] {
	vertical-align: top;
}
td[name="source_fl_col"] {
	border-spacing: 10px;
	display: inline-block;
}
.yrFrom, .yrTo {
	min-width: 80px;
	max-width: 80px;
}
input[name="pub_yrFrom"], input[name="pub_yrTo"] {
	width: 100%;
}
</style>
<script>
//var ur = <?php echo json_encode($url_host); ?>;
var ur = "";
var workURL = '<?=$this->url('get_work_details')?>';
//var ur = HOSTURL();

$(document).ready(function() {
	//Publisher
	bindPublisherAutocomplete(document, workURL);
	//add publisher rows
	$("#pub_add").click(function() {
		var pub_row = $('<tr name="pub_row[]"><input type="hidden" name="pub_id[]" id="pubId" value="">' +
			'<td><input type="text" class="form-control" name="pub_name[]" id="pubName" placeholder="none" /></td>' +
			'<!--<td><input type="text" class="form-control" name="pub_location" id="pubLocation" /></td>-->' +
			'<input type="hidden" name="publoc_id[]" id="publoc_id" value="">' +
			'<td><select class="form-control pub_locations" name="pub_location[]" id="pubLocation"><option value=""></option></select></td>' +
			'<td class="yrFrom"><input type="text" class="form-control" name="pub_yrFrom[]" id="pubyrFrom"/></td>' +
			'<td class="yrTo"><input type="text" class="form-control" name="pub_yrTo[]" id="pubyrTo" /></td>' +
			'<td><button type="submit" class="btn btn-default" name="pub_remove" id="pub_remove" value="Remove">Remove</button></td>' +
			'</tr>');

		$("#pub_table").append(pub_row);
		bindPublisherAutocomplete(pub_row, workURL);
		return false;
	});
	//remove publisher rows
	$("#pub_table").on('click', '#pub_remove', function() {
		$(this).parent().parent().remove();
	});
	//agent
	bindAgentAutocomplete(document, workURL);
	//add agent rows
	$("#agent_add").click(function() {
		var agent_row = $('<tr><td><input type="hidden" name="agent_id[]" id="agentId" value="">' +
				'<select class="form-control agent_type" name="agent_type[]" id="agent_type">' +
				'<option value=""></option>' +
				<?php
				foreach ($paginator_agtype as $ag_row) :
				//print_r($row);
				?>
					'<option value="<?= $ag_row['id'] ?>"><?php echo $ag_row['type']; ?></option>' +
				<?php endforeach; ?>
				'</select>' +
				'</td>' +
				'<td><input type="text" class="form-control" name="agent_FirstName[]" id="agent_FirstName" /></td>' +
				'<td><input type="text" class="form-control" name="agent_LastName[]" id="agent_LastName" /></td>' +
				'<td><input type="text" class="form-control" name="agent_AlternateName[]" id="agent_AlternateName" /></td>' +
				'<td><input type="text" class="form-control" name="agent_OrganizationName[]" id="agent_OrganizationName" /></td>' +
				'<td><button type="submit" class="btn btn-default" name="agent_remove" id="agent_remove" value="Remove">Remove</button></td>' +
				'</tr>');

		$("#agent_table").append(agent_row);
		bindAgentAutocomplete(agent_row, workURL);
		return false;
	});
	//remove agent rows
	$("#agent_table").on('click', '#agent_remove', function() {
		$(this).parent().parent().remove();
	});
	//get attributes for selected worktypes
	$('#work_type', document).on('change', function() {
		bindWorkTypeAttributes(document, workURL);
	});
	//classification
	//add classification rows
	$("#fl_add").on('click', function() {
		var fl_row = $('<tr name="source_fl_row[]">' + 
				'<td class="source_fl_col" name="source_fl_col" id="source_fl_col">' +
				'<select class="form-control select_source_fl select2" name="select_source_fl[]">' +
				'<option value=""></option>' +
				<?php
				$table = new \VuBib\Db\Table\Folder($this->adapter);
				$fl_siblings = $table->getFoldersWithNullParent();
				foreach ($fl_siblings as $row) :
				?>
					'<option value="<?= $row['id'] ?>"><?php echo $row['text_fr']; ?></option>' +
				<?php endforeach; ?>
				'</select>' +
				'</td>' +
				'<td style="display: inline-block;"><button type="submit" class="btn btn-default" name="fl_remove" id="fl_remove" value="Remove">Remove</button></td>' +
				'</tr>');
		$("#source_fl_table").append(fl_row);
		//bindSourceClassification(this,document);
		return false;
	});
	//remove classification rows
	$("#source_fl_table").on('click', '#fl_remove', function() {
		$(this).parent().parent().remove();
	});

	$('table[name="source_fl_table"]').on('change', ".select_source_fl", function() {
		var to_add_row = $(this).closest("tr");

		if ($(this).val() == "") {
			to_add_row.find('.source_fl_col').eq(0).nextAll('.source_fl_col').remove();
			to_add_row.find('.source_fl_col').eq(0).val('');
			return false;
		} else {
			fl_changed = $(this).val();

			var no_of_fl_parent = to_add_row.find('.select_source_fl').length;
			for (var i = 0; i < no_of_fl_parent; i++) {
				if (to_add_row.find('.select_source_fl').eq(i).val() === fl_changed) {
					change_idx = i;
					folder_Id = to_add_row.find('.select_source_fl').eq(i).val();
					break;
				}
			}
			to_add_row.find('.source_fl_col').eq(change_idx).nextAll('.source_fl_col').remove();

			no_of_fl_parent = to_add_row.find('.select_source_fl').length;

			$.ajax({
				method: 'post',
				//url: 'http://localhost<?= $this->url('get_work_details') ?>',
				url: ur + workURL,
				data: {
					folder_Id: folder_Id
				},
				dataType: "json",
				cache: false,
				success: function(data) {
					to_add_row.find('.source_fl_col').eq(no_of_fl_parent - 1).after('<td class="source_fl_col" name="source_fl_col" id="source_fl_col" style="border-spacing: 10px; display: inline-block;"/>');

					_select = $('<select class="form-control select_source_fl select2" name="select_source_fl[]">');
					to_append = $('<option value=""></option>');
					$.each(data.folder_children, function(key, val) {
						to_append += '<option value="' + val.id + '">' + val.text_fr + '</option>';
					});
					_select.append($('<option />'));
					_select.append(to_append);

					to_add_row.find('.source_fl_col').eq(no_of_fl_parent).append(_select);
					to_add_row.find('.source_fl_col').eq(no_of_fl_parent).append('</select>');

					_select.on('change', function() {
						bindSourceClassification(this, document, workURL);
						return false;
					});
				},
				error: function(data) {
					$("#Classification", context).html('<p>No Options</p>');
				}
			});
			return false;
		}
	});
   
   //Parent Lookup
   $('#parentLookup_modal').on('shown.bs.modal', function() {
	   bindParentWork(document, workURL);
	   return false;
   });   
   
   //Remove Parent Lookup
   $('.pr_work_div').on('click', '#parent_removeBtn', function() {
	   //alert("remove");
	   $('#pr_work_lookup_id').val('');
	   $('.pr_work_div').html('');
	   $('.pr_work_div').append('<button type="button" class="btn btn-default parent_lookupBtn" name="parent_lookupBtn" id="parent_lookupBtn" ' +
								'data-toggle="modal" data-target="#parentLookup_modal">Lookup</button>');
	   return false;
   });
   
	$('#submit_save').on('click', function() {
	   var no_of_rows = $('table[name="source_fl_table"]').find("tr").length;
		var arr = [];
		var values;
		$('table[name="source_fl_table"]').each(function() {
			$(this).find('tr').each(function() {
				values = [];
				$(this).find('td').find('.select_source_fl').each(function() {
					//$(this).find('.select_source_fl').each(function(){
					values.push($(this).val());
						//});						
				});
				var newInput = $('<input type="hidden" name="arr[]" value="">');
				newInput.val(values);
				$("#new-work-data").append(newInput);
			});
		});
		return true;
	});
});
 </script>
<div class="col-md-10">
    <form id="new-work-data" class="form-horizontal" method="POST" action="<?= $this->url('manage_work') ?>">
        <input type="hidden" name="action" value="work_new">
        <!--<input type="hidden" name="arr[]" id="arrs" value="frm jquery">-->
        <?php
		//get user
		$user = $this->isUser()->getUser();
		?>
        <input type="hidden" name="user" id="user" value="<?= $user ?>">
        <div class="tabbable">
            <ul class="nav nav-tabs">
                <li class="active">
                    <a href="#General" data-toggle="tab">General</a>
                </li>
                <li>
                    <a href="#Classification" data-toggle="tab">Classification</a>
                </li>
                <li>
                    <a href="#Publisher" data-toggle="tab">Publisher</a>
                </li>
                <li>
                    <a href="#Agents" data-toggle="tab">Agents</a>
                </li>
                <li>
                    <a href="#Citation" data-toggle="tab">Citation</a>
                </li>
            </ul>
        <div class="tab-content">
        <div class="tab-pane active" id="General">
			<div class="form-group required">
				<label class="col-xs-2 control-label">Title: </label>
                <div class="col-xs-10">
                    <input type="text" class="form-control" name="new_worktitle" id="newworktitle" required="true" />
                </div>
			</div>
			<div class="form-group">
                <label class="col-xs-2 control-label">Sub Title: </label>
                <div class="col-xs-10">
                    <input type="text" class="form-control" name="new_worksubtitle" id="newworksubtitle" />
                </div>
			</div>
			<div class="form-group">
                <label class="col-xs-2 control-label">Parallel Title: </label>
                <div class="col-xs-10">
                    <input type="text" class="form-control" name="new_workparalleltitle" id="newworkparalleltitle" />
                </div>
			</div>
			<div class="form-group">
                <label class="col-xs-2 control-label">Description: </label>
                <div class="col-xs-10">
                    <textarea class="form-control" placeholder="Message" name="description" id="description"></textarea>
                </div>
			</div>
			<div class="form-group">
                <label class="col-xs-2 control-label">Type: </label>
                <div class="col-xs-10">
                    <select class="form-control" name="work_type" id="work_type" required="true">
                        <option value="">Choose Work Type</option>
                        <?php
						foreach ($paginator as $row) :
						?>
                            <option value="<?= $row['id'] ?>"><?php echo $row['type']; ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
			</div>
			<div class="form-group">
                <label class="col-xs-2 control-label">Parent Work: </label>
				<input type="hidden" name="pr_work_lookup_id" id="pr_work_lookup_id" value="">
                <div class="col-xs-10 pr_work_div">
                    <button type="button" class="btn btn-default parent_lookupBtn" name="parent_lookupBtn" id="parent_lookupBtn" 
					        data-toggle="modal" data-target="#parentLookup_modal">Lookup</button>
                </div>
				<!-- Parent work Lookup -->
                <div class="modal fade ig" id="parentLookup_modal" role="dialog">
                <div class="modal-dialog ig">
                    <div class="modal-content ig">
                        <div class="modal-header ig">
                            <button type="button" class="close ig" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title ig" id="parentLookup_modalLabel">Lookup</h4>
                        </div>
                        <div class="modal-body ig">
                             <div class="form-group ig">
                                <label class="col-xs-2 control-label ig">Title: </label>
                                <div class="col-xs-10 ig">
                                    <input type="text" class="form-control ig parent_title" name="parent_title" id="parent_title" />
                                </div>
                            </div>
                            <div class="form-group ig">
                                <div class="col-sm-offset-2 col-sm-10 ig">
                                    <button type="button" class="btn btn-primary ig parent_lookup_search" id="parentLookup_search">Search</button>
                                </div>
                            </div>
                            <div class="pr_work_results ig">
                            </div>
						</div>
						<div class="modal-footer ignore ig">
                            <button type="button" class="btn btn-default option_lookup_close ig" data-dismiss="modal">Close</button>
                        </div>
					</div>
                </div>
                </div>
			</div>
			<div class="form-group">
				<label class="col-xs-2 control-label">Status: </label>
				<div class="col-xs-10">
					<div class="radio">
						<label class="radio">
							<input checked type="radio" id="selectworkstatus" name="select_workstatus" value="00">In Progress</label>
						<label class="radio">
							<input type="radio" id="selectworkstatus" name="select_workstatus" value="0">Pending Review</label>
						<label class="radio">
							<input type="radio" id="selectworkstatus" name="select_workstatus" value="2">Unseen Source Doc</label>
						<label class="radio">
							<input type="radio" id="selectworkstatus" name="select_workstatus" value="1">Complete</label>
					</div>
				</div>
			</div>
        </div>
        <div class="tab-pane" id="Classification">
			<div class="form-group" id="class_grp">
                <table class="table table-striped" name="source_fl_table" id="source_fl_table">
                <tbody>
                    <tr name="source_fl_row[]">
                        <b>Subject Tree</b>
                        <br>
                        <td class="source_fl_col" name="source_fl_col" id="source_fl_col">
							<select class="form-control select_source_fl select2" name="select_source_fl[]">
								<option value=""></option>
								<?php
								$table = new \VuBib\Db\Table\Folder($this->adapter);
								$fl_siblings = $table->getFoldersWithNullParent();
								foreach ($fl_siblings as $row) :
								?>
									<option value="<?= $row['id'] ?>"><?php echo $row['text_fr']; ?></option>
								<?php endforeach; ?>
							</select>
                        </td>
                        <td style="display: inline-block;">
                            <button type="submit" class="btn btn-default" name="fl_remove" id="fl_remove" value="Remove">Remove</button>
                        </td>
                    </tr>
                </tbody>
                </table>
                 <button type="submit" class="btn btn-default" name="fl_add" id="fl_add" value="Add">Add</button>
			</div>
		</div>
        <div class="tab-pane" id="Publisher">
            <div class="form-group">
                <table class="table table-striped table-condensed" name="pub_table" style="font-size:10pt;" id="pub_table">
                <thead>
                    <th>Publisher</th>
                    <th>Location</th>
                    <th>Year From</th>
                    <th>Year To</th>
                    <th>Remove</th>
                </thead>
                <tbody>
                    <tr name="pub_row[]">
                        <input type="hidden" name="pub_id[]" id="pubId" value="">
                        <td>
                            <input type="text" class="form-control" name="pub_name[]" id="pubName" placeholder="none" />
                        </td>
						<!--<td><input type="text" class="form-control" name="pub_location" id="pubLocation" /></td>-->
                        <input type="hidden" name="publoc_id[]" id="publoc_id" value="">
                        <td>
                            <select class="form-control pub_locations" name="pub_location[]" id="pubLocation">
                                <option value=""></option>
                            </select>
                        </td>
                        <td class="yrFrom">
                            <input type="text" class="form-control" name="pub_yrFrom[]" id="pubyrFrom" />
                        </td>
                        <td class="yrTo">
                            <input type="text" class="form-control" name="pub_yrTo[]" id="pubyrTo" />
                        </td>
                        <td>
                            <button type="submit" class="btn btn-default" name="pub_remove" id="pub_remove" value="Remove">Remove</button>
                        </td>
                    </tr>
                </tbody>
                </table>
                <button type="submit" class="btn btn-default" name="pub_add" id="pub_add" value="Add">Add</button>
            </div>
        </div>
        <div class="tab-pane" id="Agents">
            <div class="form-group">
                <table class="table table-striped table-condensed" style="font-size:10pt;" id="agent_table">
                <thead>
                    <th>Agent Type</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Alternate Name</th>
                    <th>Organization Name</th>
                    <th>Remove</th>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            <input type="hidden" name="agent_id[]" id="agentId" value="">
                            <select class="form-control agent_type" name="agent_type[]" id="agent_type">
                                <option value=""></option>
                                <?php
								//fetch agenttypes
								//$table = new \VuBib\Db\Table\AgentType($this->adapter);
								//$paginator = $table->fetchAgentTypes();
								foreach ($paginator_agtype as $row) :
								?>
                                <option value="<?= $row['id'] ?>"><?php echo $row['type']; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </td>
                        <td>
                            <input type="text" class="form-control" name="agent_FirstName[]" id="agent_FirstName" />
                        </td>
                        <td>
                            <input type="text" class="form-control" name="agent_LastName[]" id="agent_LastName" />
                        </td>
                        <td>
                            <input type="text" class="form-control" name="agent_AlternateName[]" id="agent_AlternateName" />
                        </td>
                        <td>
                            <input type="text" class="form-control" name="agent_OrganizationName[]" id="agent_OrganizationName" />
                        </td>
                        <td>
                            <button type="submit" class="btn btn-default" name="agent_remove" id="agent_remove" value="Remove">Remove</button>
                        </td>
                    </tr>
                </tbody>
                </table>
                <button type="submit" class="btn btn-default" name="agent_add" id="agent_add" value="Add">Add</button>
            </div>
        </div>
        <div class="tab-pane" id="Citation">
            <!--<div class="form-group" id="divforoptions">
            </div>-->
            <!-- Work Type Attribute Options Lookup -->
            <div class="modal fade ig" id="optionsLookup" role="dialog">
                <div class="modal-dialog ig">
                    <div class="modal-content ig">
                        <div class="modal-header ig">
                            <button type="button" class="close ig" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title ig" id="myModalLabel">Lookup</h4>
                        </div>
                        <div class="modal-body ig">
                             <div class="form-group ig">
                                <label class="col-xs-2 control-label ig">Title: </label>
                                <div class="col-xs-10 ig">
                                    <input type="text" class="form-control ig" name="lookup_Option" id="lookupOption" />
                                </div>
                            </div>
                            <div class="form-group ig">
                                <div class="col-sm-offset-2 col-sm-10 ig">
                                    <button type="button" class="btn btn-primary option_search ig" id="option_search">Search</button>
                                </div>
                            </div>
                            <div class="option_results ig">
                            </div>
						</div>
						<div class="modal-footer ignore ig">
                            <button type="button" class="btn btn-default option_lookup_close ig" data-dismiss="modal">Close</button>
                        </div>
					</div>
                </div>
            </div>
        </div>
		</div>
		</div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default" name="submit_save" id="submit_save" value="Save">Save</button>
                <button type="submit" class="btn btn-default" name="submit_cancel" value="Cancel" formnovalidate>Cancel</button>
            </div>
        </div>
    </form>
</div>