<?php $this->headTitle('Review Work'); ?>
<?php 
	  $this->layout()->breadcrumbs .= '<a href="' .  $this->url('manage_work') . '" style="float:left;color:white;"> Work > </a>' 
	                                . ' Review';
 ?>
<div class="col-lg-12">
<p>
<?php foreach ($this->carat as $value) { ?>
    <a href="<?=$this->url('manage_work')?><?='?letter='. $value['letter']. '&action=review'?>">
    <?php echo ' '.$value['letter'].' '; ?></a><?php echo '|';  ?>
<?php } ?>
<?php
$q_str = "";
$sort_ord = isset($_GET['sort_ord'])?"DESC":"ASC";
if ($request->getqueryParams()!= null) {
	$params = $request->getqueryParams();
	$q_str = $_SERVER["QUERY_STRING"];
	if(preg_match('/(?P<pg>page=\d+&)?(?P<action>.*)(?P<ord>&orderBy=\w+&sort_ord=\w+)/',$q_str,$matches)) {
        $q_str = preg_replace('/(?P<pg>page=\d+&)?(?P<action>.*)(?P<ord>&orderBy=\w+&sort_ord=\w+)/', $matches['action'], $q_str);
    }
}
?>
</p>
        <table class="table table-striped table-condensed" style="font-size:10pt;">
        <thead>
        <tr>
		 <th><a href="<?=$this->url('manage_work')?><?='?' . $q_str .'&orderBy=title&sort_ord=' . $sort_ord?>">Title</a></th>
		 <th><a href="<?=$this->url('manage_work')?><?='?' . $q_str .'&orderBy=type&sort_ord=' . $sort_ord?>">Type</a></th>
         <th>Status</th>
		 <th><a href="<?=$this->url('manage_work')?><?='?' . $q_str .'&orderBy=created&sort_ord=' . $sort_ord?>">Created</th>
		 <th><a href="<?=$this->url('manage_work')?><?='?' . $q_str .'&orderBy=modified&sort_ord=' . $sort_ord?>">Modified</th>
		 <th>Actions</th>
        </tr>
        </thead>
		<tbody>
		<?php $escaper = new Zend\Escaper\Escaper('utf-8'); ?>
        <?php foreach($this->rows as $row) : ?>
		<tr>
		<td>
			<?php 
					echo $escaper->escapeHtml($row['title']);					
			?>
		</td>
		<td>
			<?php
				//fetch work type based on type_id
                $table = new \VuBib\Db\Table\WorkType($adapter);
                $work_type = $table->findRecordById($row['type_id']);
                $type = $work_type['type'];
				echo $escaper->escapeHtml($type); 
			?>
		</td>
		<td>
			<?php
					if (is_null($row['status'])): ?>
						<img src="../images/images_admin/inactive.gif" alt="In progress" title="Inactive">						
			<?php	elseif ($row['status'] == 1): ?>
						<img src="../images/images_admin/active.gif" alt="Complete" title="Active">					
			<?php	elseif ($row['status'] == 0 || $row['status'] == 2): ?>
						<img src="../images/images_admin/review.gif" alt="Needs Review" title="Needs Review">
			<?php	endif;
					//echo $row['status'];
			?>
		</td>
		<td>
			<?php	
					//fetch created username based on create_user_id
					$table = new \VuBib\Db\Table\User($adapter);
					$cuser = $table->findRecordById($row['create_user_id']);
					$c_user = $cuser['username'];
					echo $c_user . " " . date("M d, y", strtotime($row['create_date']));?>
		</td>
		<td>
			<?php	
                if($row['modify_user_id'] != '')
				{
					//fetch modified username based on modify_user_id
					$table = new \VuBib\Db\Table\User($adapter);
					$muser = $table->findRecordById($row['modify_user_id']);
					$m_user = $muser['username'];
					echo $m_user . " " . date("M d, y", strtotime($row['modify_date']));
				}
			?>
		</td>
		<td>
			<a href="<?=$this->url('edit_work')?><?='?id='. $row['id']. '&action=edit'?>">Edit</a>        
            |
            <a href="<?=$this->url('delete_work')?><?='?id='. $row['id']. '&action=delete'?>">Delete</a>
		</td>			
		</tr>
		<?php endforeach; ?>
		</tbody>
		</table>
		<?php if($this->countp > 1) { ?>
        <form method="get" action="page">
            <?=$this->paginationControl($this->rows,
                'Sliding',
                'vubib::controls',
                [
                    'route'  => 'manage_work',
                    'extraParams' => $searchParams,
                ]
            );?>
        </form>
        <?php } ?>
</div>