<?php $this->headTitle('Delete Publisher'); ?>
<?php 
	  $this->layout()->breadcrumbs .= '<a href="' .  $this->url('manage_publisher') . '" style="float:left;color:white;"> Publisher > </a>' 
	                                . ' Delete';
 ?>

<div class="col-xs-4">
    <form method="post" action="<?= $this->url('manage_publisher') ?>">
        <p>Are you sure you want to delete this?</p>
        <ul>
            <li><?php
                $id;
                if ($request->getqueryParams('id') !== null) {
                    $params = $request->getqueryParams();
                    $action = $params['action'];
                    $id = $params['id'];
                    //fetch name based on id
                    $table = new \VuBib\Db\Table\Publisher($adapter);
                    $row = $table->findRecordById($id);
                    $name = $row['name'];
                    echo $name;
                }
                ?>
            </li>
            <input type="hidden" name="id" value="<?= $id ?>">
            <input type="hidden" name="action" value="<?= $action ?>">
        </ul>
        <input type="submit" name="submitt" value="Delete"> 
        <input type="submit" name="submitt" value="Cancel">
    </form>
</div>

