<?php $this->headTitle('Manage Publisher'); ?>
<?php
      $this->layout()->breadcrumbs .= ' Publisher';
 ?>
<script type='text/javascript'>
$(document).ready(function () {
    //Check if records are selected for delete
    $("#delPub").on('click', function () {
        if ($("#pubListTable input:checkbox:checked").length > 0) {
            // any one is checked
            return true;
        } else {
            // none is checked
            alert("No publisher(s) selected, Please select publisher(s) to delete.");
            return false;
        }
    });
});
</script>
<div class="col-lg-10">
    <p>
        <?php foreach ($this->carat as $value) { ?>
            <a href="<?= $this->url('manage_publisher') ?><?= '?letter=' . $value['letter'] . '&action=alphasearch' ?>">
                <?php echo ' ' . $value['letter'] . ' '; ?></a><?php echo '|'; ?>
        <?php } ?>
        <br> <a href="<?php echo $this->url('new_publisher') ?><?='?action=new'?>"><b style="text-decoration: underline;">Add Publisher</b></a></li>
    </p>
    <form action="<?= $this->url('delete_publisher') ?><?= '?action=delete' ?>" method="post">
    <table class="table table-striped table-condensed" id="pubListTable" style="font-size:10pt;">
        <thead>
            <tr>
                <th>&nbsp;&nbsp;</th>
                <th>Name</th>
                <th>Locations</th>
            </tr>
        </thead>
        <tbody>
            <?php $escaper = new Zend\Escaper\Escaper('utf-8'); ?>
            <?php foreach ($this->rows as $row) : //var_dump($row);?>
                <tr>
                    <td>
                        <input type="checkbox" id="selPub" name="selectPub[]" value=<?=$row['id']?>>
                    </td>
                    <td>
                    <a href="<?= $this->url('edit_publisher') ?><?= '?id=' . $row['id'] . '&action=edit' ?>">
                    <?php echo $escaper->escapeHtml($row['name']); ?></a>
                    </td>
                    <td>            
                        <?php
                        $output = (array)$row;
                        if (!isset($row['publisher_id'])) {
                        ?>        
                            <a href="<?= $this->url('manage_publisherlocation') ?><?= '?id=' . $row['id'] ?>">Manage Locations</a>  
                        <?php
                        } else {
                        ?>
                            <a href="<?= $this->url('manage_publisherlocation') ?><?= '?id=' . $row['publisher_id'] ?>">Manage Locations</a>
                        <?php
                        }
                        ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <input type="submit" name="delPub" id="delPub" value="Delete">
    </form>
    <?php if ($this->countp > 1) { ?>
        <form method="get" action="page">
            <?=
            $this->paginationControl($this->rows, 'Sliding', 'vubib::controls', [
                'route' => 'manage_publisher',
                'extraParams' => $searchParams,
                ]
            );
            ?>
        </form>
    <?php } ?>
</div>
