<?php $this->headTitle('Manage Users'); ?>
<?php
      $this->layout()->breadcrumbs .= ' Users';
 ?>
 <script>
$(document).ready(function () {
    //Check if records are selected for delete
    $("#delUser").on('click', function () {
        console.log("clicked");
        if ($("#userListTable input:checkbox:checked").length > 0) {
            // any one is checked
            return true;
        } else {
            // none is checked
            alert("No agent type(s) selected, Please select agent type(s) to delete.");
            return false;
        }
    });
});
</script>
<div class="col-md-9">
    <a href="<?php echo $this->url('new_user') ?><?='?action=new'?>"><b style="text-decoration: underline;">Add User</b></a>
    <form action="<?= $this->url('delete_user') ?><?= '?action=delete' ?>" method="post">
    <table class="table table-striped table-condensed" id="userListTable" style="font-size:10pt;">
        <thead>
            <tr>
                <th>Name</th>
                <th>Access Level</th>
            </tr>
        </thead>
        <tbody>
            <?php $escaper = new Zend\Escaper\Escaper('utf-8'); ?>
            <?php
            foreach ($this->rows as $row) :
                $output = (array)$row;
                $params = implode(', ', $output);
             ?>
                <tr>
                    <td>
                    <input type="checkbox" id="selUser" name="selectUser[]" value=<?=$row['id']?>>
                    </td>
                    <td>
                        <a href="<?= $this->url('edit_user') ?><?= '?id=' . $row['id'] . '&action=edit' ?>">
                        <?php echo $escaper->escapeHtml($row['name']); ?>
                        </a>
                    </td>
                    <td>
                        <?php
                        if (isset($row['level'])) {
                            if ($row['level'] == 1)
                                echo "Administrator";
                            else
                                echo "Super User";
                        } else
                            echo "User";
                        ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <input type="submit" name="delUser" id="delUser" value="Delete">
    </form>
    <?php if ($this->countp > 1) { ?>
        <form method="get" action="page">
            <?=
            $this->paginationControl($this->rows, 'Sliding', 'vubib::controls', [
                'route' => 'manage_user',
                'extraParams' => $searchParams,
                ]
            );
            ?>
        </form>
    <?php } ?>
</div>
