<?php $this->headTitle('Merge Agent'); ?>
<?php
    $this->headScript()->appendFile($this->url('home') . 'js/menu.js');
    $this->layout()->breadcrumbs .= '<a href="' . $this->url('manage_agent') . '">Agent</a> &gt; Merge';
    $this->layout()->page = "Agent/Merge";
 ?>
<?php
if ($request->getqueryParams('action') !== null) {
    $params = $request->getqueryParams();
    $action = $params['action'];
}
$url_components = parse_url($this->serverUrl());
$url_host = $url_components['scheme'] . '://' . $url_components['host'];
?>
<div class="col-lg-12">
    <form class="form-horizontal" name="merge_ag_form" id="merge_ag_form" method="post" action="<?= $this->url('manage_agent') ?>">
        <p class="error-empty alert alert-danger" style="display:none">Please select a source and destination agent.</p>
        <p class="error-same-id alert alert-danger" style="display:none">Cannot merge -- source and destination are the same.</p>
        <input type="hidden" name="action" value="<?= $action ?>">
        <div class="row">
            <div class="col-sm-6">
                <p><b id="src_label">Source Agent</b></p>
                <div class="form-group" id="src_find_outer_div">
                    <label class="col-sm-2 control-label">Find: </label>
                    <div class="col-sm-10">
                        <div class="agent-acs" id="acs_agent_merge_src">
                            <input type="hidden" class="acs-hidden" name="mrg_src_id" id="mrg_src_id" value="" />
                            <input type="text" class="acs-input form-control" name="find_src_agent" id="find_src_agent" placeholder="Start typing last name"/>
                        </div>
                        <div id="src_locations"></div>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <p><b id="dest_label">Destination Agent</b></p>
                <div class="form-group" id="dest_find_outer_div">
                    <label class="col-sm-2 control-label">Find: </label>
                    <div class="col-sm-10">
                        <div class="agent-acs" id="acs_agent_merge_dest">
                            <input type="hidden" class="acs-hidden" name="mrg_dest_id" id="mrg_dest_id" value="" />
                            <input type="text" class="acs-input form-control" name="find_dest_pub" id="find_dest_pub" placeholder="Start typing last name"/>
                        </div>
                        <div id="dest_locations"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-1 col-sm-11">
                <button type="submit" class="btn btn-primary" name="submit_save" id="submit_save" value="Save">Merge</button>
                <button type="reset" class="btn btn-default" name="submit_clear" id="submit_clear" value="Cancel">Clear</button>
            </div>
        </div>
    </form>
</div>

<script>
    var workURL = "<?=$this->url('get_work_details')?>";
    setupACS(
      ".agent-acs",
      function ajaxData(input) {
        return { autofor: "agent", term: input.value };
      },
      function ajaxSuccess(data, callback, input) {
        if(!data.length){
          callback([{ text: "no matches", _disabled: true }]);
        } else {
          // TODO: Add new
          callback(
            data.map(item => ({
              text: item.lname + ", " + item.fname,
              id:   item.id
            }))
          );
        }
      }
    );

    //check if src and dest are same
    $(document).on('click', '#submit_save', function () {
        $('.error-empty,.error-same-id').hide();
        if (!$('#mrg_src_id').val() || !$('#mrg_dest_id').val()) {
            $('.error-empty').show();
            return false;
        }
        if ($('#mrg_src_id').val() === $('#mrg_dest_id').val()) {
            $('.error-same-id').show();
            return false;
        }
        return true;
    });
    $('#submit_clear').on('click', function () {
        location.reload(true);
    });
</script>