<?php $this->headTitle('Exportlist Classification'); ?>
<?php //$this->layout()->instructions = ""; ?>
<div class="row">
    <div class="col-md-4">
        <h2>
                Exportlist Classification Coming Soon
        </h2>
       
    </div>
</div>
<div class="col-md-9">
<?php
	$parent = NULL;
	$table = new \App\Db\Table\Folder($this->adapter);
    $table->exportClassification($parent);
?>
</div>