<?php $this->headTitle('Manage Classification'); ?>
<?php //$this->layout()->instructions = ""; 
	//$bc = array();
	//array_push( $bc,$this->previous_folder['text_fr'] );
		if(!isset($bc[0]))
		{
			$bc[0] = $this->previous_folder['text_fr'];
			$i = 0;
		} else
		{
			$bc[$i++] = $this->previous_folder['text_fr'];
		}
		$i++;
	print_r($bc);
?>
<div class="col-md-9">
	<p style="font-weight:bold;" id="view_hierarchy">Viewing:
	<a href="#">
	<?php echo $this->previous_folder['text_fr'] . '>'; ?>
	</a>
	</p>
	<table class="table table-striped table-condensed" style="font-size:10pt;">
        <thead>
        <tr>
          <th>Title</th>
          <th>Actions</th>
        </tr>
        </thead>
        <tbody>
		<?php $escaper = new Zend\Escaper\Escaper('utf-8'); ?>
        <?php foreach($this->rows as $row) : ?>
        <tr>
        <td><a href="<?=$this->url('manage_classification')?><?='?id='. $row['id']. '&action=get_children'?>" class="folder_name">
			<?php echo $escaper->escapeHtml($row['text_fr']); ?></a></td>
        <td>                   
            <a href="#">Edit</a>        
			|
			<a href="#">Move</a>
			|
            <a href="#">Delete</a>
			|
			<a href="#">Manage References</a>
        </td>
        </tr>
		<?php endforeach; ?>
        </tbody>
		</table>
		<?php if($this->countp > 1) { ?>
        <form method="get" action="page">
            <?=$this->paginationControl($this->rows,
                'Sliding',
                'app::controls',
                [
                    'route'  => 'manage_classification',
                ]
            );?>
        </form>
        <?php } ?>
</div>
