<?php $this->headTitle('Manage Classification'); ?>

<div class="col-md-9">
	<p style="font-weight:bold;" id="view_hierarchy">Viewing:
	<?php //$this->layout()->instructions = ""; 
	if(count($this->trail) > 0)
	{
		for($i=0;$i<=count($this->trail)-2;$i++)
		{
		?>
			<a href="#"><?php echo $this->trail[$i]; ?></a>
			<?php echo ' > ';
		}
		echo $this->trail[$i];
	}	
?>
	</a>
	</p>
	<table class="table table-striped table-condensed" style="font-size:10pt;">
        <thead>
        <tr>
          <th>Title</th>
          <th>Actions</th>
        </tr>
        </thead>
        <tbody>
		<?php $escaper = new Zend\Escaper\Escaper('utf-8'); ?>
        <?php foreach($this->rows as $row) : ?>
        <tr>
        <td><a href="<?=$this->url('manage_classification')?><?='?id='. $row['id']. '&fl='. $escaper->escapeHtml($row['text_fr']). '&action=get_children'?>" class="folder_name">
			<?php echo $escaper->escapeHtml($row['text_fr']); ?></a></td>
        <td>                   
            <a href="#">Edit</a>        
			|
			<a href="#">Move</a>
			|
            <a href="#">Delete</a>
			|
			<a href="#">Manage References</a>
        </td>
        </tr>
		<?php endforeach; ?>
        </tbody>
		</table>
		<?php if($this->countp > 1) { ?>
        <form method="get" action="page">
            <?=$this->paginationControl($this->rows,
                'Sliding',
                'app::controls',
                [
                    'route'  => 'manage_classification',
                ]
            );?>
        </form>
        <?php } ?>
</div>
