<?php $this->headTitle('Merge Classification'); ?>
<?php //$this->layout()->instructions = ""; ?>
<script>
_select = '';
function bindSourceClassification(context)
{
	fl_changed = $(_select,context).val();

		var no_of_fl_parent = $('.select_source_fl',context).length;

		for(var i = 0;i < no_of_fl_parent; i++)
		{
			if($('.select_source_fl',context).eq(i).val() === fl_changed)
			{
				change_idx = i;
				folder_Id = $('.select_source_fl',context).eq(i).val();
				break;
			}
		}
		
		if(folder_Id === "none" || folder_Id === "")
		{
			alert("if");
			$('.source_fl_col').eq(0).nextAll('.source_fl_col',context).remove();
			$('.source_fl_col').eq(0).val('none');
		}
		else
		{
			alert("else");
			$('.source_fl_col').eq(change_idx).nextAll('.source_fl_col',context).remove();
		}
			
		no_of_fl_parent = $('.select_source_fl',context).length;

		$.ajax({
			method: 'post',
			url: 'http://localhost<?=$this->url('get_work_details')?>',
			data: {
				folder_Id: folder_Id
			},
			dataType: "json", 
			cache: false,
			success: function(data)
			{						
				if(data.folder_children.length > 0)
				{
					$('.source_fl_col',context).eq(no_of_fl_parent-1).css('background','#8ec252');		
					$('.source_fl_col',context).eq(no_of_fl_parent-1).after('<td class="source_fl_col" name="source_fl_col" id="source_fl_col" style="border-spacing: 10px;"/>');
					
					_select = $('<select class="form-control select_source_fl" name="select_source_fl[]">');
					to_append = $('<option value="none"></option>');
					$.each(data.folder_children, function (key, val) {
						to_append += '<option value="'+val.id+'">'+val.text_fr+'</option>';
					});
					_select.append($('<option />'));
					_select.append(to_append);
					$('.source_fl_col',context).eq(no_of_fl_parent).append(_select);
					$('.source_fl_col',context).eq(no_of_fl_parent).append('</select>');
					
					_select.on('change',function(){
						bindSourceClassification(document);
					});	
				}
			},
			error: function (data) { 
				//$("#Classification", context).html('<p>No Options</p>');
			}
		});	
		return false;	
}
function bindDestClassification(context)
{
	fl_changed = $(_select,context).val();

		var no_of_fl_parent = $('.select_dest_fl',context).length;

		for(var i = 0;i < no_of_fl_parent; i++)
		{
			if($('.select_dest_fl',context).eq(i).val() === fl_changed)
			{
				change_idx = i;
				folder_Id = $('.select_dest_fl',context).eq(i).val();
				break;
			}
		}
		
		if(folder_Id === "none" || folder_Id === "")
		{
			alert("if");
			$('.dest_fl_col').eq(0).nextAll('.dest_fl_col',context).remove();
			$('.dest_fl_col').eq(0).val('none');
		}
		else
		{
			alert("else");
			$('.dest_fl_col').eq(change_idx).nextAll('.dest_fl_col',context).remove();
		}
			
		no_of_fl_parent = $('.select_dest_fl',context).length;

		$.ajax({
			method: 'post',
			url: 'http://localhost<?=$this->url('get_work_details')?>',
			data: {
				folder_Id: folder_Id
			},
			dataType: "json", 
			cache: false,
			success: function(data)
			{						
				if(data.folder_children.length > 0)
				{
					$('.dest_fl_col',context).eq(no_of_fl_parent-1).css('background','#8ec252');		
					$('.dest_fl_col',context).eq(no_of_fl_parent-1).after('<td class="dest_fl_col" name="dest_fl_col" id="dest_fl_col" style="border-spacing: 10px;"/>');
					
					_select = $('<select class="form-control select_dest_fl" name="select_dest_fl[]">');
					to_append = $('<option value="none"></option>');
					$.each(data.folder_children, function (key, val) {
						to_append += '<option value="'+val.id+'">'+val.text_fr+'</option>';
					});
					_select.append($('<option />'));
					_select.append(to_append);
					$('.dest_fl_col',context).eq(no_of_fl_parent).append(_select);
					$('.dest_fl_col',context).eq(no_of_fl_parent).append('</select>');
					
					_select.on('change',function(){
						bindDestClassification(document);
					});	
				}
			},
			error: function (data) { 
				//$("#Classification", context).html('<p>No Options</p>');
			}
		});	
		return false;	
}
$(document).ready(function() {
	//click clear
	$("#submit_clear").on('click', function() {
		alert("clear");
		/*$('.source_fl_col').eq(0).nextAll('.source_fl_col',context).remove();
		$('.dest_fl_col').eq(0).nextAll('.dest_fl_col',context).remove();
		$('.source_fl_col').eq(0).val('none');
		$('.dest_fl_col').eq(0).val('none');*/
		return false;
	});
	//source classification
	$(".select_source_fl").on('change', function() {
		if($(this).val() == "none" || $(this).val() == ""){
			$('.source_fl_col').eq(0).nextAll('.source_fl_col',context).remove();
			$('.source_fl_col').eq(0).val('none');
			return false;
		}
		else
		{
		fl_changed = $(this).val();
		alert("changed value is " + fl_changed);
		var no_of_fl_parent = $('.select_source_fl').length;

		for(var i = 0;i < no_of_fl_parent; i++)
		{
			if($('.select_source_fl').eq(i).val() === fl_changed)
			{
				change_idx = i;
				folder_Id = $('.select_source_fl').eq(i).val();
				break;
			}
		}
		
		no_of_fl_parent = $('.select_source_fl').length;

		$.ajax({
			method: 'post',
			url: 'http://localhost<?=$this->url('get_work_details')?>',
			data: {
				folder_Id: folder_Id
			},
			dataType: "json", 
			cache: false,
			success: function(data)
			{						
				$('.source_fl_col').eq(no_of_fl_parent-1).css('background','#8ec252');		
				$('.source_fl_col').eq(no_of_fl_parent-1).after('<td class="source_fl_col" name="source_fl_col" id="source_fl_col" style="border-spacing: 10px;"/>');
					
				_select = $('<select class="form-control select_source_fl" name="select_source_fl[]">');
				to_append = $('<option value="none"></option>');
				$.each(data.folder_children, function (key, val) {
					to_append += '<option value="'+val.id+'">'+val.text_fr+'</option>';
				});
				_select.append($('<option />'));
				_select.append(to_append);
				$('.source_fl_col').eq(no_of_fl_parent).append(_select);
				$('.source_fl_col').eq(no_of_fl_parent).append('</select>');
					
				_select.on('change',function(){
					bindSourceClassification(document);
				});			
			},
			error: function (data) { 
				//$("#Classification", context).html('<p>No Options</p>');
			}
		});	
		return false;
		}
	});
	//destination classification
	$(".select_dest_fl").on('change', function() {
		if($(this).val() == "none" || $(this).val() == ""){
			$('.dest_fl_col').eq(0).nextAll('.dest_fl_col',context).remove();
			$('.dest_fl_col').eq(0).val('none');
			return false;
		}
		else
		{
		fl_changed = $(this).val();
		alert("changed value is " + fl_changed);
		var no_of_fl_parent = $('.select_dest_fl').length;

		for(var i = 0;i < no_of_fl_parent; i++)
		{
			if($('.select_dest_fl').eq(i).val() === fl_changed)
			{
				change_idx = i;
				folder_Id = $('.select_dest_fl').eq(i).val();
				break;
			}
		}
		
		no_of_fl_parent = $('.select_dest_fl').length;

		$.ajax({
			method: 'post',
			url: 'http://localhost<?=$this->url('get_work_details')?>',
			data: {
				folder_Id: folder_Id
			},
			dataType: "json", 
			cache: false,
			success: function(data)
			{						
				$('.dest_fl_col').eq(no_of_fl_parent-1).css('background','#8ec252');		
				$('.dest_fl_col').eq(no_of_fl_parent-1).after('<td class="dest_fl_col" name="dest_fl_col" id="dest_fl_col" style="border-spacing: 10px;"/>');
					
				_select = $('<select class="form-control select_dest_fl" name="select_dest_fl[]">');
				to_append = $('<option value="none"></option>');
				$.each(data.folder_children, function (key, val) {
					to_append += '<option value="'+val.id+'">'+val.text_fr+'</option>';
				});
				_select.append($('<option />'));
				_select.append(to_append);
				$('.dest_fl_col').eq(no_of_fl_parent).append(_select);
				$('.dest_fl_col').eq(no_of_fl_parent).append('</select>');
					
				_select.on('change',function(){
					bindDestClassification(document);
				});			
			},
			error: function (data) { 
				//$("#Classification", context).html('<p>No Options</p>');
			}
		});	
		return false;
		}
	});
	//click save
	$("#submit_save").click( function() {
		
		return false;
	});
	
});
</script>
<div class="col-lg-12">
<form class="form-horizontal" method="post" action="<?=$this->url('manage_classification')?>">
<input type="hidden" name="action" value="<?=$action?>">
<div class="form-group">
		<table name="source_fl_table" id="source_fl_table" style="font-size:10pt; border-collapse: separate; border-spacing: 10px;">        
		<tbody>
		<tr name="source_fl_row">
			<b>Source Classification</b><br>
			<td class="source_fl_col" name="source_fl_col" id="source_fl_col" style="border-spacing: 10px;">				
				<select class="form-control select_source_fl" name="select_source_fl[]">
				<option value="none"></option>
				<?php
				$table = new \App\Db\Table\Folder($this->adapter);
				//$fl_siblings = $table->getChild($arr_fl[$i+1]);
				$fl_siblings = $table->getFoldersWithNullParent();
					foreach($fl_siblings as $row) :
				?>
				<option value="<?=$row['id']?>"><?php echo $row['text_fr']; ?></option>							
				<?php 
					endforeach; ?>
				</select>
			</td>
		</tr>
		</tbody>
		</table>		
</div>	
<div class="form-group">
		<table name="dest_fl_table" id="dest_fl_table" style="font-size:10pt; border-collapse: separate; border-spacing: 10px;">        
		<tbody>
		<tr name="dest_fl_row">
				<b>Destination Classification</b><br>
				<td class="dest_fl_col" name="dest_fl_col" id="dest_fl_col" style="border-spacing: 10px;">
				<select class="form-control select_dest_fl" name="select_dest_fl">
				<option value="none"></option>
				<?php
				$table = new \App\Db\Table\Folder($this->adapter);
				$fl_siblings = $table->getFoldersWithNullParent();
					foreach($fl_siblings as $row) :
				?>
				<option value="<?=$row['id']?>"><?php echo $row['text_fr']; ?></option>							
				<?php 
					endforeach; ?>
				</select>
			</td>			
		</tr>
		</tbody>
		</table>		
</div>	
<div class="form-group">
	<div class="col-sm-offset-4 col-sm-10">
		<button type="submit" class="btn btn-default" name="submit_save" value="Save">Save</button> 
        <button type="reset" class="btn btn-default" name="submit_clear" id="submit_clear" value="Cancel">Clear</button>
	</div>
</div>
</form>
</div>