<?php $this->headTitle('Move Classification'); ?>
<?php //$this->layout()->instructions = ""; ?>
<?php                                       
    $id;
    if ($request->getqueryParams('id') !== null) 
    {   
        $params = $request->getqueryParams();
        $action = $params['action'];
        $id = $params['id'];
    }
?>
<script>
_select = '';
function bindClassificationFolder(context)
{
	//fl_changed = $(this).val();
	fl_changed = $(_select,context).val();
	//alert("changed is " + fl_changed);
	var no_of_fl_parent = $('.select_fl').length;
	for(var i = 0;i < no_of_fl_parent; i++)
	{
		if($('.select_fl').eq(i).val() === fl_changed)
		{
			change_idx = i;
			folder_Id = $('.select_fl').eq(i).val();
			break;
		}
	}
	for(i = change_idx + 1; i < no_of_fl_parent; i++)
	{
		$('.label_fl').eq(i).remove();
		$('.inner_div_fl').eq(i).remove();
		$('.select_fl').eq(i).remove();
		
		/*$('label[name="label_fl"]').eq(i).remove();
		$('div[name="inner_div_fl"]').eq(i).remove();
		$('select[name="select_fl"]').eq(i).remove();*/
	}
			
	no_of_fl_parent = $('.select_fl').length;

	$.ajax({
		method: 'post',
		url: 'http://localhost<?=$this->url('get_work_details')?>',
		data: {
			folder_Id: folder_Id
		},
			dataType: "json", 
			cache: false,
			success: function(data)
			{	
				$('.outer_div_fl').eq(no_of_fl_parent-1).css('background','#8ec252');
					
				if(data.folder_children.length > 0)
				{
					$('.outer_div_fl').eq(no_of_fl_parent-1).after('<div class="form-group outer_div_fl" name="outer_div_fl" />');
					$('.outer_div_fl').eq(no_of_fl_parent).append('<label class="col-xs-2 control-label label_fl" name="label_fl">Subject Tree: </label>');
					$('.outer_div_fl').eq(no_of_fl_parent).append('<div class="col-xs-5 inner_div_fl" name="inner_div_fl" />');
					
					_select = $('<select class="form-control select_fl" name="select_fl[]">');
					to_append = '';
					$.each(data.folder_children, function (key, val) {
						to_append += '<option value="'+val.id+'">'+val.text_fr+'</option>';
					});
					_select.append($('<option />'));
					_select.append(to_append);
					$('.inner_div_fl').eq(no_of_fl_parent).append(_select);
					$('.inner_div_fl').eq(no_of_fl_parent).append('</select>');
					
					_select.on('change',function(){
						//alert("call function");
						bindClassificationFolder(document);
					});	
				}
			},
			error: function (data) { 
				//$("#Classification", context).html('<p>No Options</p>');
			}
		});			
		return false;
}

$(document).ready(function() {
	$("#submit_save").click( function() {
		var fl_id = $("#mv_fl_id").val();
		var $select = $('select[name="fl_to_mv"]');
		fl_moved_id = $select.val();
		if(fl_id === fl_moved_id)
		{
			alert("wrong");
			$('.moveError').show();
			$select.focus();
			return false;
		}
    });
	
	$(".select_fl").on('change', function() {
		fl_changed = $(this).val();
		var no_of_fl_parent = $('.select_fl').length;

		for(var i = 0;i < no_of_fl_parent; i++)
		{
			if($('.select_fl').eq(i).val() === fl_changed)
			{
				change_idx = i;
				folder_Id = $('.select_fl').eq(i).val();
				break;
			}
		}

		$('.outer_div_fl').eq(change_idx).nextAll('.outer_div_fl').remove();

			
			no_of_fl_parent = $('.select_fl').length;

			$.ajax({
				method: 'post',
				url: 'http://localhost<?=$this->url('get_work_details')?>',
				data: {
					folder_Id: folder_Id
				},
				dataType: "json", 
				cache: false,
				success: function(data)
				{	
					$('.outer_div_fl').eq(no_of_fl_parent-1).css('background','#8ec252');
		
					$('.outer_div_fl').eq(no_of_fl_parent-1).after('<div class="form-group outer_div_fl" name="outer_div_fl" />');
					$('.outer_div_fl').eq(no_of_fl_parent).append('<label class="col-xs-2 control-label label_fl" name="label_fl">Subject Tree: </label>');
					$('.outer_div_fl').eq(no_of_fl_parent).append('<div class="col-xs-5 inner_div_fl" name="inner_div_fl" />');
					
					_select = $('<select class="form-control select_fl" name="select_fl[]">');
					to_append = '';
					$.each(data.folder_children, function (key, val) {
						to_append += '<option value="'+val.id+'">'+val.text_fr+'</option>';
					});
					_select.append($('<option />'));
					_select.append(to_append);
					$('.inner_div_fl').eq(no_of_fl_parent).append(_select);
					$('.inner_div_fl').eq(no_of_fl_parent).append('</select>');
					
					_select.on('change',function(){
						bindClassificationFolder(document);
					});			
				},
				error: function (data) { 
					//$("#Classification", context).html('<p>No Options</p>');
				}
			});	
		
		return false;
	});
});
</script>
<div class="col-md-7" name="mv_classification" id="mv_classification">
<form id="move-folder-data" class="form-horizontal" name="form_mv_classification" id="form_mv_classification" 
      method="POST" action="<?=$this->url('manage_classification')?>">
<input type="hidden" name="action" value="<?=$action?>">
<input type="hidden" name="id" id="mv_fl_id" value="<?=$id?>">	
<?php
$arr_fl = [];			
if(isset($id)) 
{
	$arr_fl[] = $id;
	$table = new \App\Db\Table\Folder($this->adapter);
	$fl_row = $table->getParent($id); 
	while(isset($fl_row['parent_id'])) 
	{
		$arr_fl[] = $fl_row['parent_id'];				
		$table = new \App\Db\Table\Folder($this->adapter);
		$fl_row = $table->getParent($fl_row['parent_id']);
		if($fl_row['parent_id'] == NULL)
		{
			break;
		}
	}
	$cnt = count($arr_fl);
	echo "<pre>";print_r($arr_fl);echo "</pre>"; //die();
	for($i = $cnt-1; $i >= 0; $i--)
	{		
		if($arr_fl[$i] == $id)
		{
		?>
			<div class="form-group outer_div_fl" name="outer_div_fl">
			<label class="col-xs-2 control-label label_fl" name="label_fl">Subject Tree: </label>
			<div class="col-xs-5 inner_div_fl" name="inner_div_fl">
				<select class="form-control select_fl" name="select_fl[]">
				<option value="none"></option>
				<?php
				$table = new \App\Db\Table\Folder($this->adapter);
				$fl_siblings = $table->getChild($arr_fl[$i+1]);
					foreach($fl_siblings as $row) :
				?>
				<option value="<?=$row['id']?>"><?php echo $row['text_fr']; ?></option>	
					<?php 
					endforeach; ?>
				</select>
			</div>
			</div>	
		<?php
		}
		else if($i != ($cnt-1))
		{
			$table = new \App\Db\Table\Folder($this->adapter);
			$fl = $table->findRecordById($arr_fl[$i]);
		?>
			<div class="form-group outer_div_fl" name="outer_div_fl">
			<label class="col-xs-2 control-label label_fl" name="label_fl">Subject Tree: </label>
			<div class="col-xs-5 inner_div_fl" name="inner_div_fl">
				<select class="form-control select_fl" name="select_fl[]">
				<option value="none"></option>
				<option value="<?=$arr_fl[$i]?>" selected><?php echo $fl['text_fr']; ?></option>
				<?php
				$table = new \App\Db\Table\Folder($this->adapter);
				$fl_siblings = $table->getChild($arr_fl[$i+1]);
					foreach($fl_siblings as $row) :
					if($row['id'] != $arr_fl[$i])
					{
				?>
				<option value="<?=$row['id']?>"><?php echo $row['text_fr']; ?></option>							
				<?php
					}
					endforeach; ?>
				</select>
			</div>
		</div>		
		<?php
		}
		else
		{
			$table = new \App\Db\Table\Folder($this->adapter);
			$fl = $table->findRecordById($arr_fl[$i]);
		?>
			<div class="form-group outer_div_fl" name="outer_div_fl">
			<label class="col-xs-2 control-label label_fl" name="label_fl">Subject Tree: </label>
			<div class="col-xs-5 inner_div_fl" name="inner_div_fl">
				<select class="form-control select_fl" name="select_fl[]">
				<option value="none"></option>
				<option value="<?=$arr_fl[$i]?>" selected><?php echo $fl['text_fr']; ?></option>
				<?php
				$table = new \App\Db\Table\Folder($this->adapter);
				//$fl_siblings = $table->getChild($arr_fl[$i+1]);
				$fl_siblings = $table->getFoldersWithNullParent();
					foreach($fl_siblings as $row) :
					if($row['id'] != $arr_fl[$i])
					{
				?>
				<option value="<?=$row['id']?>"><?php echo $row['text_fr']; ?></option>							
				<?php 
					}
					endforeach; ?>
				</select>
			</div>
			</div>	
		<?php
		}
	}
}
?>
<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<button type="submit" class="btn btn-default" name="submit_save" id="submit_save" value="Save">Save</button> 
        <button type="submit" class="btn btn-default" name="submit_cancel" value="Cancel">Cancel</button>
		<p class="moveError" style="display:none;color:red;margin-bottom:20px;">Cannot move a classification into itself.</p>
	</div>
</div>
</form>
</div>