( [0] => 11079 [1] => 11076 [2] => 11060 [3] => 11057 [4] => 10434 )

doctrine
Temps. Histoire
Temps
Temporalite
Temporalite - Move

Doctrine->Temps. Histoire->Temps->Temporalite->none selected but list in dropdown to select

Doctrine->Temps. Histoire->Temps->Temporalite->none selected but sibs of mv_t1,mv_t2

select mv_t2 and save

id p_id en fr de nl es it no sort_ord
-  11076 mv_t1               NULL     23841
-  11076 mv_t2               NULL     23842

move:
-----
1. select same - display message
2. select other than id in last dropdown, make selected fl id as parent_id for id record
3. in any other dropdown select smthng else - display hierarchy accordingly

for($i = $cnt-1; $i >= 0; $i--)
	{
		
		//echo "i is $i";
		if($i != ($cnt-1))
		{
			echo "folder is " . $arr_fl[$i] . "</br>";
			echo "parent is " . $arr_fl[$i+1] . "</br>";
			$table = new \App\Db\Table\Folder($this->adapter);
			$fl_siblings = $table->getChild($arr_fl[$i+1]);
			//echo "<pre>";print_r($fl_siblings);echo "</pre>";
		?>
		<div class="form-group" id="class_grp">
			<label class="col-xs-2 control-label">Subject Tree: </label>
			<div class="col-xs-5">
				<select class="form-control subject_tree" name="subject_tree" id="subject_tree">
				<option value=""></option>
				<?php
					//fetch worktypes
					//$table = new \App\Db\Table\Folder($this->adapter);
					//$paginator = $table->findParent();
					foreach($fl_siblings as $row) :
				?>
				<option value="<?=$row['id']?>"><?php echo $row['text_fr']; ?></option>							
				<?php endforeach; ?>
				</select>
			</div>
		</div>		
		<?php
		}
		else
		{
			echo "folder is " . $arr_fl[$i] . "</br>";
			echo "parent is null" . "</br>";
			$table = new \App\Db\Table\Folder($this->adapter);
			$fl_siblings = $table->getFoldersWithNullParent();
			//echo "<pre>";print_r($fl_siblings);echo "</pre>";
		?>
			<div class="form-group" id="class_grp">
			<label class="col-xs-2 control-label">Subject Tree: </label>
			<div class="col-xs-5">
				<select class="form-control subject_tree" name="subject_tree" id="subject_tree">
				<option value=""></option>
				<?php
					//fetch worktypes
					//$table = new \App\Db\Table\Folder($this->adapter);
					//$paginator = $table->findParent();
					foreach($fl_siblings as $row) :
				?>
				<option value="<?=$row['id']?>"><?php echo $row['text_fr']; ?></option>							
				<?php endforeach; ?>
				</select>
			</div>
			</div>	
		<?php
		}
	}