<?php $this->headTitle('Delete User'); ?>
<?php
      $this->layout()->breadcrumbs .= '<a href="' . $this->url('manage_users') . '" style="float:left;color:white;"> Users > </a>' . ' Delete';
 ?>
<div class="col-xs-4">
    <form method="post" action="<?= $this->url('manage_users') ?>">
        <p>Are you sure you want to delete?</p>
        <?php
        $id;
        if ($request->getqueryParams('id') !== null) {
            $params = $request->getqueryParams();
            $action = $params['action'];
        }

        if ($request->getMethod() == 'POST') {
            $post = $request->getParsedBody();
        }
        $user = [];
        if(count($post['selectUser']) > 0) {
            foreach($post['selectUser'] as $usr):
                $user['id'] = $usr;
                //fetch name based on id
                $table = new \VuBib\Db\Table\User($adapter);
                $row = $table->findRecordById($user['id']);
                $name = $row['name'];
                $username = $row['username'];
                echo "<p>user " . $name . " with username as " . $username . "</p>";
        ?>
        <ul>
        <input type="hidden" name="user_id[]" value="<?=$user['id']?>">                        
        <input type="hidden" name="action" value="<?=$action?>">
        </ul>                        
        <?php
            endforeach;
        }
        ?>
        <input type="submit" name="submitt" value="Delete"> 
        <input type="submit" name="submitt" value="Cancel">
    </form>
</div>