<?php $this->headTitle('Delete/Merge Locations Publisher'); ?>
<?php
    $this->layout()->breadcrumbs .= '<a href="' . $this->url('manage_publisher') . '">Publisher</a> &gt; Delete/Merge Locations';
    $this->layout()->page = "Publisher - Delete/Merge Locations";
?>
<?php
$id;
if ($request->getqueryParams('id') !== null) {
    $params = $request->getqueryParams();
    $id = $params['id'];
    $this->layout()->breadcrumbs .= '<a href="' . $this->url('manage_publisher') . '" style="float:left;color:white;"> Publisher > </a>' .
            '<a href="' . $this->url('manage_publisherlocation') . '?id=' . $id . '" style="float:left;color:white;"> Publisher Locations > </a>'
            . ' Delete/Merge Locations';
}
?>
<?php if ($_POST['submitt'] == 'Delete') { ?>
    <div class="col-xs-4">
        <form method="post" action="<?= $this->url('manage_publisherlocation') ?><?= '?id=' . $params['id'] . '&count=0' ?>">
            <p>Are you sure you want to delete this location for the publisher?</p>
            <ul>
                <li>
                    <?php
                    $locs = [];
                    foreach ($_POST['selectchk1'] as $loc) {
                        $locs[] = $loc;
                        echo $loc . "<br />";
                    }
                    ?>
                </li>
                <input type="hidden" name="id" value="<?= $id ?>">
                <input type="hidden" name="action" value="<?= 'delete' ?>">
                <?php foreach ($_POST['selectchk1'] as $loc) { ?>
                    <input type="hidden" name="locs[]" value="<?= $loc ?>">
                <?php } ?>
                <?php
                //fetch location ids of locations selected for delete
                $row = [];
                $table = new \VuBib\Db\Table\PublisherLocation($adapter);
                $row = $table->findLocationId($id, $locs);
                //var_dump($row);
                foreach ($row as $locid) {
                ?>
                    <input type="hidden" name="locids[]" value="<?= $locid['id'] ?>">
                <?php } ?>
            </ul>
            <input type="submit" name="submitt" value="Delete">
            <input type="submit" name="submitt" value="Cancel">
        </form>
    </div>
<?php } ?>
<?php if ($_POST['submitt'] == 'Merge') { ?>
    <form method="post" action="<?= $this->url('manage_publisherlocation') ?><?= '?id=' . $params['id'] . '&count=0' ?>">
        <input type="hidden" name="id" value="<?= $id ?>">
        <input type="hidden" name="action" value="<?= 'merge' ?>">

        <p>Are you sure you want to merge these?</p>
        <div class="row">
            <div class="col-xs-4">
                <p><b>From:</b></p>
                <ul>
                    <?php
                    $source_locs;
                    $dest_loc;
                    foreach ($_POST['selectsource'] as $sourceloc) {
                        $source_locs = unserialize($sourceloc);
                        if(strpos($source_locs['location'], '**hasSpace**') !== false) {
                            $source_locs['location'] = str_replace("**hasSpace**", " ", $source_locs['location']);
                        }
                        ?>
                        <input type="hidden" name="sourceids[]" value="<?= $source_locs['id'] ?>">
                        <?php
                        echo '<li>' . $source_locs['location'] . '</li>';
                    }
                    ?>
                </ul>
            </div>
            <div class="col-xs-4">
                <?php $dest_loc = unserialize($_POST['selectdest']); ?>
                <p><b>To:</b></p>
                <p><?=$dest_loc[0]['location']; ?></p>
                <input type="hidden" name="destid" value="<?= $dest_loc[0]['id'] ?>">
            </div>
        </div>
        <input type="submit" name="submitt" value="Merge">
        <input type="submit" name="submitt" value="Cancel">
    </form>
<?php } ?>
