<?php $this->headTitle('Merge Publisher'); ?>
<?php
    $this->layout()->breadcrumbs .= '<a href="' . $this->url('manage_publisher') . '" style="float:left;color:white;"> Publisher > </a>'
                                    . ' Merge';
    $this->headScript()->appendFile($this->url('home') . 'js/work.js');
?>
<script>
    var ur = "";
    var workURL = '<?=$this->url('get_work_details')?>';
    $(document).ready(function () {
        $("#find_dest_pub").prop("disabled", "disabled");
        $("#dest_pub_find_bt").prop("disabled", "disabled");
        //source find
        $("#src_pub_find_bt").on('click', function () {
            findPublisher(workURL, 'src');
            return false;
        });
        //source select
        $(document).on('click', '#btn_select_src', function () {
            findPublisherLoc(document, workURL, 'src');
            return false;
        });
        //destination find
        $("#dest_pub_find_bt").on('click', function () {
            findPublisher(workURL, 'dest');
            return false;
        });
        //destination select
        $(document).on('click', '#btn_select_dest', function () {
            findPublisherLoc(document, workURL, 'dest');
            return false;
        });
        //check if src and dest are same
        $(document).on('click', '#submit_save', function () {
            var src_loc_row_cnt = $('#src_loc_result_table').find('tr[class="src_loc_row"]').length;
            var src_loc_mv_cnt = $('#src_loc_result_table').find('input[id="src_loc_mv_select"]:checked').length;
            var src_loc_mrg_cnt = $('#src_loc_result_table').find('input[id="src_loc_mrg_select"]:checked').length;
            var src_loc_sel_cnt = src_loc_mv_cnt + src_loc_mrg_cnt;

            if(src_loc_row_cnt !== src_loc_sel_cnt) {
                $('.mergePubSelError').show();
                return false;
            }
            if ($('#mrg_src_id').val() === $('#mrg_dest_id').val()) {
                $('.mergePubError').show();
                return false;
            }
            //return false;
        });
        $('#submit_clear').on('click', function () {
            location.reload(true);
        });
    });
</script>
<div class="col-lg-12">
    <form class="form-horizontal" name="merge_pub_form" id="merge_pub_form" method="post" action="<?= $this->url('manage_publisher') ?>">
        <input type="hidden" name="action" value="merge_publisher">
        <input type="hidden" name="mrg_src_id" id="mrg_src_id" value="">
        <input type="hidden" name="mrg_dest_id" id="mrg_dest_id" value="">
        <div class="form-group">
            <table style="font-size:10pt; border-collapse: separate; border-spacing: 10px;">        
                <tbody>
                    <tr valign="Top">            
                        <td style="border-spacing: 10px;" id="src_find_col">                
                            <b id="src_label">Source Publisher</b><br>
                            <div class="form-group" id="src_find_outer_div">
                                <label class="col-xs-4 control-label">Find: </label>
                                <div class="col-xs-7">
                                    <input type="text" class="form-control" name="find_src_pub" id="find_src_pub" placeholder="enter publisher"/>
                                </div>    
                                <div class="col-xs-7">
                                    <button type="button" class="btn btn-default" name="src_pub_find_bt" id="src_pub_find_bt" value="Save">Find</button>
                                </div>
                            </div>
                        </td>    
                        <td style="border-spacing: 10px;">
                            <b id="dest_label">Destination Publisher</b><br>
                            <div class="form-group" id="dest_find_outer_div">
                                <label class="col-xs-4 control-label">Find: </label>
                                <div class="col-xs-7">
                                    <input type="text" class="form-control" name="find_dest_pub" id="find_dest_pub" placeholder="enter publisher"/>
                                </div>
                                <div class="col-xs-7">
                                    <button type="button" class="btn btn-default" name="dest_pub_find_bt" id="dest_pub_find_bt" value="Save">Find</button>
                                </div>
                            </div>
                        </td>            
                    </tr>
                </tbody>
            </table>        
        </div>    
        <div class="form-group">
            <div class="col-sm-offset-4 col-sm-10">
                <!--<button type="submit" class="btn btn-default" name="submit_save" id="submit_save" value="Save">Merge</button>-->
                <button type="reset" class="btn btn-default" name="submit_clear" id="submit_clear" value="Cancel">Clear</button>
                <p class="mergePubError" style="display:none;color:red;margin-bottom:20px;">Cannot merge -- source and destination are the same.</p>
                <p class="mergePubSelError" style="display:none;color:red;margin-bottom:20px;">Cannot merge -- Select move or merge action for all locations of source publisher.</p>
            </div>
        </div>
    </form>
</div>