<?php $this->headTitle('Merge Publisher'); ?>
<?php
    $this->layout()->breadcrumbs .= '<a href="' . $this->url('manage_publisher') . '">Publisher</a> &gt; Merge';
    $this->layout()->page = "Publisher/Merge";
?>
<?php
    $this->headScript()->appendFile($this->url('home') . 'js/menu.js');
    $this->headScript()->appendFile($this->url('home') . 'js/work.js');
?>
<form class="form-horizontal" name="merge_pub_form" id="merge_pub_form" method="post" action="<?= $this->url('manage_publisher') ?>">
    <input type="hidden" name="action" value="merge_publisher">

    <div id="mergeMissingError" class="alert alert-danger" style="display:none">Please select a source and a destination.</div>
    <div id="mergePubError" class="alert alert-danger" style="display:none">Cannot merge -- source and destination are the same.</div>
    <div id="mergePubSelError" class="alert alert-danger" style="display:none">Cannot merge -- Select move or merge action for all locations of source publisher.</div>

    <div class="row">
        <div class="col-sm-6">
            <p><b id="src_label">Source Publisher</b></p>
            <div class="form-group" id="src_find_outer_div">
                <label class="col-sm-2 control-label">Find: </label>
                <div class="col-sm-10">
                    <div class="publisher-acs" id="acs_publisher_merge_src">
                        <input type="hidden" class="acs-hidden" name="mrg_src_id" id="mrg_src_id" value="" />
                        <input type="text" class="acs-input form-control" name="find_src_pub" id="find_src_pub" placeholder="enter publisher"/>
                    </div>
                    <div id="src_locations"></div>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <p><b id="dest_label">Destination Publisher</b></p>
            <div class="form-group" id="dest_find_outer_div">
                <label class="col-sm-2 control-label">Find: </label>
                <div class="col-sm-10">
                    <div class="publisher-acs" id="acs_publisher_merge_dest">
                        <input type="hidden" class="acs-hidden" name="mrg_dest_id" id="mrg_dest_id" value="" />
                        <input type="text" class="acs-input form-control" name="find_dest_pub" id="find_dest_pub" placeholder="enter publisher"/>
                    </div>
                    <div id="dest_locations"></div>
                </div>
            </div>
        </div>
    </div>

    <button type="submit" class="btn btn-primary" name="submitt" id="submit_save" value="Save">Merge</button>
    <button type="reset" class="btn btn-link" name="submit_clear" id="submit_clear" value="Cancel">Clear</button>
</form>
<script>
    var workURL = '<?=$this->url('get_work_details')?>';
    bindFindPublisher();
</script>
