<?php $this->headTitle('Delete Agent'); ?>
<?php
    $this->layout()->breadcrumbs = '<a href="' . $this->url('manage_agent') . '">Agent</a> &gt; Delete';
?>

<div class="col-xs-4">
    <form method="post" action="<?= $this->url('manage_agent') ?>">
        <p>Are you sure you want to delete this?</p>
        <?php
            if ($request->getqueryParams('action') !== null)
            {
                $params = $request->getqueryParams();
                $action = $params['action'];
            }

            if ($request->getMethod() == 'POST') {
                $post = $request->getParsedBody();
            }

            $ag = [];
            if(count($post['selectAgent']) > 0) {
                foreach($post['selectAgent'] as $agent):
                    $ag['id'] = $agent;
                    //fetch name based on id
                    $table = new \VuBib\Db\Table\Agent($adapter);
                    $row = $table->findRecordById($ag['id']);
                    $name = $row['lname'] . $row['fname'];
                    echo "<li>$name</li>";
                    //fetch no of works associated
                    $table = new \VuBib\Db\Table\WorkAgent($this->adapter);
                    $paginator = $table->countRecordsByAgent($ag['id']);
                    $cnt = $paginator->getTotalItemCount();
                    echo "<p><b>There are $cnt works associated with it.</b></p>"; ?>
                    <ul>
                    <input type="hidden" name="agent_id[]" value="<?=$ag['id']?>">
                    <input type="hidden" name="action" value="<?=$action?>">
                    </ul>
                    <?php
                endforeach;
            }
            ?>
        <input type="submit" name="submitt" value="Delete">
        <input type="submit" name="submitt" value="Cancel">
    </form>
</div>
