<?php
$this->headTitle('Edit Agent');
?> 
<?php 
	  $this->layout()->breadcrumbs .= '<a href="' .  $this->url('manage_agent') . '" style="float:left;color:white;"> Agent > </a>' . ' Edit';
 ?>

<?php
$id;
if ($request->getqueryParams('id') !== null) {
    $params = $request->getqueryParams();
    $action = $params['action'];
    $id = $params['id'];
    //fetch name based on id
    $table = new \VuBib\Db\Table\Agent($adapter);
    $row = $table->findRecordById($id);
    $fname = $row['fname'];
    $lname = $row['lname'];
    $altname = $row['alternate_name'];
    $orgname = $row['organization_name'];
	$mail = $row['email'];
}
?>
<?php $escaper = new Zend\Escaper\Escaper('utf-8'); ?>
<div class="col-md-4">
    <form class="form-horizontal" method="post" action="<?= $this->url('manage_agent') ?>">
        <input type="hidden" name="action" value="<?= trim($action) ?>">
        <input type="hidden" name="id" value="<?= trim($id) ?>">
        <div class="form-group">
            <label class="col-xs-4 control-label">First Name: </label>
            <div class="col-xs-7">
                <input type="text" class="form-control" name="edit_agentfirstname" id="editagentfirstname" value="<?= $escaper->escapeHtml(trim($fname)) ?>" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-xs-4 control-label">Last Name: </label>
            <div class="col-xs-7">
                <input type="text" class="form-control" name="edit_agentlastname" id="editagentlastname" value="<?= $escaper->escapeHtml(trim($lname)) ?>" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-xs-4 control-label">Alternate Name: </label>
            <div class="col-xs-7">
                <input type="text" class="form-control" name="edit_agentaltname" id="editagentaltname" value="<?= $escaper->escapeHtml(trim($altname)) ?>" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-xs-4 control-label">Organization Name: </label>
            <div class="col-xs-7">
                <input type="text" class="form-control" name="edit_agentorgname" id="editagentorgname" value="<?= $escaper->escapeHtml(trim($orgname)) ?>" />
            </div>
        </div>
		<div class="form-group">
            <label class="col-xs-4 control-label">Email: </label>
            <div class="col-xs-7">
                <input type="text" class="form-control" name="edit_agentemail" id="editagentemail" value="<?= $escaper->escapeHtml(trim($mail)) ?>" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-4 col-sm-10">
                <button type="submit" class="btn btn-default" name="submitt" value="Save">Save</button> 
                <button type="submit" class="btn btn-default" name="submitt" value="Cancel">Cancel</button>
            </div>
        </div>
    </form>
</div>
