<?php $this->headTitle('Manage Agent'); ?>
<?php
      $this->layout()->breadcrumbs .= ' Agent';
 ?>
<script type='text/javascript'>
$(document).ready(function () {
    //Check if records are selected for delete
    $("#delAgent").on('click', function () {
        if ($("#agentListTable input:checkbox:checked").length > 0) {
            // any one is checked
            return true;
        } else {
            // none is checked
            alert("No agent(s) selected, Please select agent(s) to delete.");
            return false;
        }
    });
});
</script>
<div class="col-md-12">     
    <p>
        <?php foreach ($this->carat as $value) { ?>
            <a href="<?= $this->url('manage_agent') ?><?= '?letter=' . $value['letter'] . '&action=alphasearch' ?>">
                <?php echo ' ' . $value['letter'] . ' '; ?></a><?php echo '|'; ?>
        <?php } ?>
        <br> <a href="<?php echo $this->url('new_agent') ?><?='?action=new'?>"><b style="text-decoration: underline;">Add Agent</b></a>
    </p>
    <form action="<?= $this->url('delete_agent') ?><?= '?action=delete' ?>" method="post">
    <table class="table table-striped table-condensed" id="agentListTable" style="font-size:10pt;">
        <thead>
            <tr>
                <th>&nbsp;&nbsp;</th>
                <th>Name</th>
                <th>Alternate Name</th>
                <th>Organization Name</th>
            </tr>
        </thead>
        <tbody>
            <?php $escaper = new Zend\Escaper\Escaper('utf-8'); ?>
            <?php foreach ($this->rows as $row) : ?>
                <tr>
                    <td>
                        <input type="checkbox" id="selAgent" name="selectAgent[]" value=<?=$row['id']?>>
                    </td>
                    <td>
                        <a href="<?= $this->url('edit_agent') ?><?= '?id=' . $row['id'] . '&action=edit' ?>">
                        <?php echo $escaper->escapeHtml($row['lname']) . " " . $escaper->escapeHtml($row['fname']); ?></a>
                    </td>
                    <td><?php echo $escaper->escapeHtml($row['alternate_name']); ?></td>
                    <td><?php echo $escaper->escapeHtml($row['organization_name']); ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <input type="submit" name="delAgent" id="delAgent" value="Delete">
    </form>
    <?php if ($this->countp > 1) { ?>
        <form method="get" action="page">
            <?=
            $this->paginationControl($this->rows, 'Sliding', 'vubib::controls', [
                'route' => 'manage_agent',
                'extraParams' => $searchParams,
                ]
            );
            ?>                               
        </form>
    <?php } ?>
</div>
