<?php $this->headTitle('Exportlist Classification'); ?>
<?php 
	  $this->layout()->breadcrumbs .= '<a href="' .  $this->url('manage_classification') . '" style="float:left;color:white;"> Classification > </a>' 
	                                . ' Export';
 ?>
<?php
//$parent = NULL;
$table = new \VuBib\Db\Table\Folder($this->adapter);
$table->exportClassification();
?>
<div class="row">
    <div class="col-md-4">
        <h2>
            Download Classification List
        </h2>

    </div>
</div>
<div class="col-md-9">

</div>