<?php $this->headTitle('Merge Classification'); ?>
<?php 
	  $this->layout()->breadcrumbs .= '<a href="' .  $this->url('manage_classification') . '" style="float:left;color:white;"> Classification > </a>' 
	                                . ' Merge';
 ?>
<?php
if ($request->getqueryParams('action') !== null) {
    $params = $request->getqueryParams();
    $action = $params['action'];
}
$url_components = parse_url($this->serverUrl());
$url_host = $url_components['scheme'] . '://' . $url_components['host'];
?>
<script>
	//var ur = <?php echo json_encode($url_host); ?>;
	var ur = "";
    _select = '';
    function bindSourceClassification(that, context)
    {
        //fl_changed = $(_select,context).val();
        fl_changed = $(that).val();
        var no_of_fl_parent = $('.select_source_fl', context).length;

        for (var i = 0; i < no_of_fl_parent; i++)
        {
            if ($('.select_source_fl', context).eq(i).val() === fl_changed)
            {
                change_idx = i;
                folder_Id = $('.select_source_fl', context).eq(i).val();
                break;
            }
        }

        if (folder_Id === "")
        {
            $('.source_fl_col').eq(0).nextAll('.source_fl_col', context).remove();
            $('.source_fl_col').eq(0).val('');
        } else
        {
            $('.source_fl_col').eq(change_idx).nextAll('.source_fl_col', context).remove();
        }

        no_of_fl_parent = $('.select_source_fl', context).length;

        $.ajax({
            method: 'post',
            //url: 'http://localhost<?= $this->url('get_work_details') ?>',
			url: ur + '<?=$this->url('get_work_details')?>',
            data: {
                folder_Id: folder_Id
            },
            dataType: "json",
            cache: false,
            success: function (data)
            {
                if (data.folder_children.length > 0)
                {
                    $('.source_fl_col', context).eq(no_of_fl_parent - 1).css('background', '#8ec252');
                    $('.source_fl_col', context).eq(no_of_fl_parent - 1).after('<td class="source_fl_col" name="source_fl_col" id="source_fl_col" style="border-spacing: 10px;"/>');

                    _select = $('<select class="form-control select_source_fl" name="select_source_fl[]">');
                    to_append = $('<option value=""></option>');
                    $.each(data.folder_children, function (key, val) {
                        to_append += '<option value="' + val.id + '">' + val.text_fr + '</option>';
                    });
                    _select.append($('<option />'));
                    _select.append(to_append);
                    $('.source_fl_col', context).eq(no_of_fl_parent).append(_select);
                    $('.source_fl_col', context).eq(no_of_fl_parent).append('</select>');

                    _select.on('change', function () {
                        bindSourceClassification(this, document);
                    });
                }
            },
            error: function (data) {
                //$("#Classification", context).html('<p>No Options</p>');
            }
        });
        return false;
    }
    function bindDestClassification(that, context)
    {
        //fl_changed = $(_select,context).val();
        fl_changed = $(that).val();
        var no_of_fl_parent = $('.select_dest_fl', context).length;

        for (var i = 0; i < no_of_fl_parent; i++)
        {
            if ($('.select_dest_fl', context).eq(i).val() === fl_changed)
            {
                change_idx = i;
                folder_Id = $('.select_dest_fl', context).eq(i).val();
                break;
            }
        }

        if (folder_Id === "")
        {
            $('.dest_fl_col').eq(0).nextAll('.dest_fl_col', context).remove();
            $('.dest_fl_col').eq(0).val('');
        } else
        {
            $('.dest_fl_col').eq(change_idx).nextAll('.dest_fl_col', context).remove();
        }

        no_of_fl_parent = $('.select_dest_fl', context).length;

        $.ajax({
            method: 'post',
            //url: 'http://localhost<?= $this->url('get_work_details') ?>',
			url: ur + '<?=$this->url('get_work_details')?>',
            data: {
                folder_Id: folder_Id
            },
            dataType: "json",
            cache: false,
            success: function (data)
            {
                if (data.folder_children.length > 0)
                {
                    $('.dest_fl_col', context).eq(no_of_fl_parent - 1).css('background', '#8ec252');
                    $('.dest_fl_col', context).eq(no_of_fl_parent - 1).after('<td class="dest_fl_col" name="dest_fl_col" id="dest_fl_col" style="border-spacing: 10px;"/>');

                    _select = $('<select class="form-control select_dest_fl" name="select_dest_fl[]">');
                    to_append = $('<option value=""></option>');
                    $.each(data.folder_children, function (key, val) {
                        to_append += '<option value="' + val.id + '">' + val.text_fr + '</option>';
                    });
                    _select.append($('<option />'));
                    _select.append(to_append);
                    $('.dest_fl_col', context).eq(no_of_fl_parent).append(_select);
                    $('.dest_fl_col', context).eq(no_of_fl_parent).append('</select>');

                    _select.on('change', function () {
                        bindDestClassification(this, document);
                    });
                }
            },
            error: function (data) {
                //$("#Classification", context).html('<p>No Options</p>');
            }
        });
        return false;
    }
    $(document).ready(function () {
        //source classification
        $(".select_source_fl").on('change', function () {
            if ($(this).val() == "") {
                $('.source_fl_col').eq(0).nextAll('.source_fl_col').remove();
                $('.source_fl_col').eq(0).val('');
                return false;
            } else
            {
                fl_changed = $(this).val();
                //alert("changed value is " + fl_changed);
                var no_of_fl_parent = $('.select_source_fl').length;

                for (var i = 0; i < no_of_fl_parent; i++)
                {
                    if ($('.select_source_fl').eq(i).val() === fl_changed)
                    {
                        change_idx = i;
                        folder_Id = $('.select_source_fl').eq(i).val();
                        break;
                    }
                }
                $('.source_fl_col').eq(change_idx).nextAll('.source_fl_col').remove();

                no_of_fl_parent = $('.select_source_fl').length;

                $.ajax({
                    method: 'post',
                    //url: 'http://localhost<?= $this->url('get_work_details') ?>',
					url: ur + '<?=$this->url('get_work_details')?>',
                    data: {
                        folder_Id: folder_Id
                    },
                    dataType: "json",
                    cache: false,
                    success: function (data)
                    {
                        $('.source_fl_col').eq(no_of_fl_parent - 1).css('background', '#8ec252');
                        $('.source_fl_col').eq(no_of_fl_parent - 1).after('<td class="source_fl_col" name="source_fl_col" id="source_fl_col" style="border-spacing: 10px;"/>');

                        _select = $('<select class="form-control select_source_fl" name="select_source_fl[]">');
                        to_append = $('<option value=""></option>');
                        $.each(data.folder_children, function (key, val) {
                            to_append += '<option value="' + val.id + '">' + val.text_fr + '</option>';
                        });
                        _select.append($('<option />'));
                        _select.append(to_append);
                        $('.source_fl_col').eq(no_of_fl_parent).append(_select);
                        $('.source_fl_col').eq(no_of_fl_parent).append('</select>');

                        _select.on('change', function () {
                            bindSourceClassification(this, document);
                        });
                    },
                    error: function (data) {
                        //$("#Classification", context).html('<p>No Options</p>');
                    }
                });
                return false;
            }
        });
        //destination classification
        $(".select_dest_fl").on('change', function () {
            if ($(this).val() == "") {
                $('.dest_fl_col').eq(0).nextAll('.dest_fl_col', context).remove();
                $('.dest_fl_col').eq(0).val('');
                return false;
            } else
            {
                fl_changed = $(this).val();

                var no_of_fl_parent = $('.select_dest_fl').length;

                for (var i = 0; i < no_of_fl_parent; i++)
                {
                    if ($('.select_dest_fl').eq(i).val() === fl_changed)
                    {
                        change_idx = i;
                        folder_Id = $('.select_dest_fl').eq(i).val();
                        break;
                    }
                }
                $('.dest_fl_col').eq(change_idx).nextAll('.dest_fl_col').remove();

                no_of_fl_parent = $('.select_dest_fl').length;

                $.ajax({
                    method: 'post',
                    //url: 'http://localhost<?= $this->url('get_work_details') ?>',
					url: ur + '<?=$this->url('get_work_details')?>',
                    data: {
                        folder_Id: folder_Id
                    },
                    dataType: "json",
                    cache: false,
                    success: function (data)
                    {
                        $('.dest_fl_col').eq(no_of_fl_parent - 1).css('background', '#8ec252');
                        $('.dest_fl_col').eq(no_of_fl_parent - 1).after('<td class="dest_fl_col" name="dest_fl_col" id="dest_fl_col" style="border-spacing: 10px;"/>');

                        _select = $('<select class="form-control select_dest_fl" name="select_dest_fl[]">');
                        to_append = $('<option value=""></option>');
                        $.each(data.folder_children, function (key, val) {
                            to_append += '<option value="' + val.id + '">' + val.text_fr + '</option>';
                        });
                        _select.append($('<option />'));
                        _select.append(to_append);
                        $('.dest_fl_col').eq(no_of_fl_parent).append(_select);
                        $('.dest_fl_col').eq(no_of_fl_parent).append('</select>');

                        _select.on('change', function () {
                            bindDestClassification(this, document);
                        });
                    },
                    error: function (data) {
                        //$("#Classification", context).html('<p>No Options</p>');
                    }
                });
                return false;
            }
        });
        //click save
        $("#submit_save").click(function () {
            var src_id = $('.select_source_fl').eq(($('.select_source_fl').length) - 1).val();
            var dst_id = $('.select_dest_fl').eq(($('.select_dest_fl').length) - 1).val();

            if (src_id === '')
            {
                var $src_select = $('.select_source_fl').eq(($('.select_source_fl').length) - 2);
                src_id = $src_select.val();
            }

            if (dst_id === '')
            {
                var $dst_select = $('.select_dest_fl').eq(($('.select_dest_fl').length) - 2);
                dst_id = $dst_select.val();
            }

            if (src_id === "" || dst_id === "")
            {
                $('.mergeError4').show();
                return false;
            }

            if (src_id === dst_id)
            {
                $('.mergeError1').show();
                return false;
            }

            $.ajax({
                method: 'post',
                //url: 'http://localhost<?= $this->url("get_work_details") ?>',
				url: ur + '<?=$this->url('get_work_details')?>',
                data: {
                    fl_id: src_id
                },
                dataType: "json",
                cache: false,
                success: function (data)
                {
                    var valid_pass = true;
                    $.each(data.fl_row, function (key, val) {
                        if (("" + val) === dst_id)
                        {
                            //alert("wrong3");
                            $('.mergeError3').show();
                            valid_pass = false;
                        }
                    });
                    $.ajax({
                        method: 'post',
                        //url: 'http://localhost<?= $this->url('get_work_details') ?>',
						url: ur + '<?=$this->url('get_work_details')?>',
                        data: {
                            fl_id: dst_id
                        },
                        dataType: "json",
                        cache: false,
                        success: function (data)
                        {
                            //valid_pass = true;
                            $.each(data.fl_row, function (key, val) {
                                if (("" + val) === src_id)
                                {
                                    //alert("wrong2");
                                    $('.mergeError2').show();
                                    valid_pass = false;
                                }
                            });
                            if (valid_pass)
                            {
                                $("#merge_fl_form").submit();
                            }
                        },
                        error: function (data) {
                        }
                    });
                },
                error: function (data) {
                }
            });
            return false;
        });
        //click clear
        $("#submit_clear").on('click', function () {
            $('.source_fl_col').eq(0).nextAll('.source_fl_col').remove();
            $('.select_source_fl').eq(0).val('');
            $('.dest_fl_col').eq(0).nextAll('.dest_fl_col').remove();
            $('.select_dest_fl').eq(0).val('');
            $('.mergeError1').hide();
            $('.mergeError2').hide();
            $('.mergeError3').hide();
            $('.mergeError4').hide();
            return false;
        });
    });
</script>
<div class="col-lg-12">
    <form class="form-horizontal merge_fl_form" method="post" action="<?= $this->url('manage_classification') ?>" name="merge_fl_form" id="merge_fl_form">
        <input type="hidden" name="action" value="<?= $action ?>">
        <!--<input type="hidden" class="src_parent_id" name="src_parent_id" id="src_parent_id" value="">
        <input type="hidden" class="dst_parent_id" name="dst_parent_id" id="dst_parent_id" value="from ajax call">-->
        <div class="form-group">
            <table name="source_fl_table" id="source_fl_table" style="font-size:10pt; border-collapse: separate; border-spacing: 10px;">        
                <tbody>
                    <tr name="source_fl_row">
                <b>Source Classification</b><br>
                <td class="source_fl_col" name="source_fl_col" id="source_fl_col" style="border-spacing: 10px;">				
                    <select class="form-control select_source_fl" name="select_source_fl[]">
                        <option value=""></option>
                        <?php
                        $table = new \VuBib\Db\Table\Folder($this->adapter);
                        $fl_siblings = $table->getFoldersWithNullParent();
                        foreach ($fl_siblings as $row) :
                            ?>
                            <option value="<?= $row['id'] ?>"><?php echo $row['text_fr']; ?></option>							
                        <?php endforeach; ?>
                    </select>
                </td>
                </tr>
                </tbody>
            </table>		
        </div>	
        <div class="form-group">
            <table name="dest_fl_table" id="dest_fl_table" style="font-size:10pt; border-collapse: separate; border-spacing: 10px;">        
                <tbody>
                    <tr name="dest_fl_row">
                <b>Destination Classification</b><br>
                <td class="dest_fl_col" name="dest_fl_col" id="dest_fl_col" style="border-spacing: 10px;">
                    <select class="form-control select_dest_fl" name="select_dest_fl[]">
                        <option value=""></option>
                        <?php
                        $table = new \VuBib\Db\Table\Folder($this->adapter);
                        $fl_siblings = $table->getFoldersWithNullParent();
                        foreach ($fl_siblings as $row) :
                            ?>
                            <option value="<?= $row['id'] ?>"><?php echo $row['text_fr']; ?></option>							
                        <?php endforeach; ?>
                    </select>
                </td>			
                </tr>
                </tbody>
            </table>		
        </div>	
        <div class="form-group">
            <div class="col-sm-offset-4 col-sm-10">
                <button type="submit" class="btn btn-default" name="submit_save" id="submit_save" value="Save">Merge</button>
                <button type="reset" class="btn btn-default" name="submit_clear" id="submit_clear" value="Cancel">Clear</button>
                <p class="mergeError1" style="display:none;color:red;margin-bottom:20px;">Cannot merge -- source and destination are the same.</p>
                <p class="mergeError2" style="display:none;color:red;margin-bottom:20px;">Cannot merge a classification into its own child.</p>
                <p class="mergeError3" style="display:none;color:red;margin-bottom:20px;">Cannot merge a classification into its own parent.</p>
                <p class="mergeError4" style="display:none;color:red;margin-bottom:20px;">Cannot merge -- source and destination cannot be empty.</p>
            </div>
        </div>
    </form>
</div>