<?php $this->headTitle('New Classification'); ?>
<?php 
	  $this->layout()->breadcrumbs .= '<a href="' .  $this->url('manage_classification') . '" style="float:left;color:white;"> Classification > </a>' 
	                                . ' New';
 ?>
<?php
if ($request->getqueryParams('action') !== null) {
    $params = $request->getqueryParams();
    $action = $params['action'];
}
?>
<div class="col-md-4">
    <form class="form-horizontal" method="post" action="<?= $this->url('manage_classification') ?>">
        <input type="hidden" name="action" value="<?= $action ?>">
        <div class="form-group">
            <label class="col-xs-4 control-label">Sort Order: </label>
            <div class="col-xs-7">
                <input type="text" class="form-control" name="new_classif_sortorder" id="newclassif_sortorder" />
            </div>
        </div>
        <div class="form-group">  
            <label class="col-xs-4 control-label">Parent: </label>
            <div class="col-xs-7">
                <select class="form-control" name="parent_id">				
                    <option value=""></option>
                        <?php
                        $table = new \VuBib\Db\Table\Folder($this->adapter);
                        $fl_parents = $table->findParent();
                        foreach ($fl_parents as $row) :
                            ?>
                            <option value="<?= $row['id'] ?>"><?php echo $row['text_fr']; ?></option>							
                        <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label class="col-xs-4 control-label">English Title: </label>
            <div class="col-xs-7">
                <input type="text" class="form-control" name="new_classif_engtitle" id="newclassif_engtitle" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-xs-4 control-label">French Title: </label>
            <div class="col-xs-7">
                <input type="text" class="form-control" name="new_classif_frenchtitle" id="newclassif_frenchtitle" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-xs-4 control-label">German Title: </label>
            <div class="col-xs-7">
                <input type="text" class="form-control" name="new_classif_germantitle" id="newclassif_germantitle" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-xs-4 control-label">Dutch Title: </label>
            <div class="col-xs-7">
                <input type="text" class="form-control" name="new_classif_dutchtitle" id="newclassif_dutchtitle" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-xs-4 control-label">Spanish Title: </label>
            <div class="col-xs-7">
                <input type="text" class="form-control" name="new_classif_spanishtitle" id="newclassif_spanishtitle" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-xs-4 control-label">Italian Title: </label>
            <div class="col-xs-7">
                <input type="text" class="form-control" name="new_classif_italiantitle" id="newclassif_italiantitle" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-4 col-sm-10">
                <button type="submit" class="btn btn-default" name="submit" value="Save">Save</button> 
                <button type="submit" class="btn btn-default" name="submit" value="Cancel">Cancel</button>
            </div>
        </div>
    </form>
</div>