<?php
echo json_encode($rows);
exit;

if($this->publookup == 'pub_lookup') {
?>
<div class="modal-content" id="popup_publisher">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title" id="myModalLabel">Publisher Name</h4>
			</div>
			<div class="modal-body">
				<p>Helloooo</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				<button type="button" class="btn btn-primary" id="publisher_search">Search</button>
			</div>
		</div>
<?php
}
?>