<?php $this->headTitle('New Work'); ?>
<?php
		//fetch worktypes
		$table = new \App\Db\Table\WorkType($this->adapter);
		$paginator = $table->fetchAllWorkTypes();
		$itemsCount = $paginator->getTotalItemCount();
		$paginator->setItemCountPerPage($itemsCount);	

		//fetch agent types
		$table = new \App\Db\Table\AgentType($this->adapter);
		$paginator_agtype = $table->fetchAgentTypes();
		$itemsCount = $paginator->getTotalItemCount();
		$paginator_agtype->setItemCountPerPage($itemsCount);	
		
		
?>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script>
function bindPublisherAutocomplete(context) {
							
	//publisher enable/disable fields
	$("#pubLocation", context).prop("disabled", "disabled");
	
	//Publisher autocomplete
	$(function() {
		$( "#pubName", context).autocomplete({
			source: 'http://localhost<?=$this->url('get_work_details')?>?autofor=publisher',
			autoFocus:true,
			select: function(event, ui){
                $('#pubName', context).val(ui.item.label);
                $('#pubId', context).val(ui.item.id);
				$("#pubLocation", context).prop("disabled", false);
                return false;
            }
		});
	});	
	$('#pubName', context).on('autocompleteselect', function (e, ui) {
		var publisher_Id = ui.item.id;
		i=0;
		//arr = [];
		$.ajax({
        method: 'post',
        url: 'http://localhost<?=$this->url('get_work_details')?>',
		data: {
			publisher_Id: publisher_Id
		},
		dataType: "json", 
        cache: false,
        success: function(data)
        {
			$("#pubLocation", context).html('');
			$.each(data.publoc, function (key, val) {
                $("#pubLocation", context).append('<option id="' + val.id + '">' + val.label + '</option>');
				$("#publoc_id", context).eq(i).val(val.id);
				//arr.push(val.id);
				i++;
            })
			//console.log(arr);
			//$("#publoc_id", context) = arr;
		},
		error: function () { 
            $("#pubLocation", context).html('<option id="-1">none available</option>');
        }
        });
    });	
}
//Agent Autocomplete
function bindAgentAutocomplete(context) 
{						
	//agent enable/disable fields
	$("#agent_FirstName", context).prop("disabled", "disabled");
	$("#agent_LastName", context).prop("disabled", "disabled");
	$("#agent_AlternateName", context).prop("disabled", "disabled");
	$("#agent_OrganizationName", context).prop("disabled", "disabled");
	
	$('#agent_type',context).on('change', function() {
		$("#agent_FirstName", context).prop("disabled", false);
		//agent first name autocomplete
		$(function() {
			$( "#agent_FirstName", context).autocomplete({
				source: 'http://localhost<?=$this->url('get_work_details')?>?autofor=agent',
				autoFocus:true,
				select: function(event, ui){
					$('#agent_FirstName', context).val(ui.item.label);
					$('#agentId', context).val(ui.item.id);				
					return false;
				}
			});
		});	
	});
	$('#agent_FirstName', context).on('autocompleteselect', function (e, ui) {
		if(ui.item.lname != '') {
			$("#agent_LastName", context).prop("disabled", false);
			$("#agent_LastName", context).val(ui.item.lname);
		}
		if(ui.item.alternate_name != '') {
			$("#agent_AlternateName", context).prop("disabled", false);
			$("#agent_AlternateName", context).val(ui.item.alternate_name);
		}
		if(ui.item.organization_name != '') {
			$("#agent_OrganizationName", context).prop("disabled", false);
			$("#agent_OrganizationName", context).val(ui.item.organization_name);
		}		
    });	
}
//WorkType Autocomplete
function bindWorkTypeAttributes(context)
{
	$('#Citation *').not('.ig').remove();
	//$(".content_box a").not(".button")
	var worktype_Id = $('#work_type').val();
	$.ajax({
        method: 'post',
        url: 'http://localhost<?=$this->url('get_work_details')?>',
		data: {
			worktype_Id: worktype_Id
		},
		dataType: "json", 
        cache: false,
        success: function(data)
        {
			$.each(data.worktype_attribute, function (key, val) {				
				$("<div />").attr("class","form-group optiondiv").attr("id","optiondiv").appendTo("#Citation");
				$("<label />").attr("class","col-xs-2 control-label").text(val.field).appendTo("#Citation");
				//$("</label>").appendTo("#divforoptions");
				$("<div />").attr("id","optionfieldsdiv").appendTo("#Citation");
				// append input control at end of form
				if(val.type == 'Textarea')
				{
					$("<textarea />")
						.attr("class","form-control")
						.attr("id", val.field)
						.attr("name", val.field + ':' +val.id)
						.appendTo("#Citation");
					//$("</textarea>").appendTo("#divforoptions");
				}
				if(val.type == 'Text')
				{
					$("<input />")
						.attr("type","text")
						.attr("class","form-control")
						.attr("id", val.field)
						.attr("name", val.field + ':' + val.id)
						.appendTo("#Citation");
				}				
				if(val.type == 'Select')
				{
					var container = $('<div/>');
					$("<input />")
						.attr("type","text")
						.attr("class","form-control Attributeoption")
						.attr("id", val.field + ':' +val.id)
						.attr("name", val.field + ':' +val.id)
						.appendTo(container);
					$("<button data-toggle='modal' data-target='#pubLookup'/>")
						.attr("class","btn btn-default optionLookupBtn")
						.attr("id","optionLookupBtn")
						.attr("data-toggle","modal")
						.attr("data-target","optionsLookup")
						.attr("value","Lookup")
						.text("Lookup")
						.appendTo(container);	
					container.appendTo('#Citation');
				}	
            })			
			$(".optionLookupBtn").on('click', function(e){
				// show Modal
				var lookupBtn = this;
				attr_option_lookup = $(lookupBtn).prev();
				$("#optionsLookup").modal('show');
				$('#optionsLookup').on('shown.bs.modal', function () {
					$('#lookupOption').focus()
					$('.option_search').on('click', function(e) {					
						//console.log(attr_option_lookup);
						var attribute_Id = $(lookupBtn).prev().attr('id');
						var option = $('#lookupOption').val();
						$.ajax({
							method: 'post',
							url: 'http://localhost<?=$this->url('get_work_details')?>',
							data: {
								option: option,
								attribute_Id: attribute_Id
							},
							dataType: "json", 
							cache: false,
							success: function(data)
							{
								$(".option_results",context).html('');
								$(".option_results",context).append('<p>Search Results</p>');
								$.each(data.attribute_options, function (key, val) {
									$(".option_results",context).append('<p><a href="'+ val.title +'" class="link_options">' + val.title + '</a></p>');
								})
							},
							error: function () { 
								$(".option_results",context).append('<p>None available</p>');
							}
						});	
						$(context).on("click", ".link_options", function(e) {
							var linkval = $(this).attr('href');
							attr_option_lookup.val(linkval);
							$('#lookupOption').val('');
							$(".option_results",context).html('');	
							$('.option_lookup_close').trigger('click');												
							return false;
						});
					});
				});
				return false;
			});
		},
		error: function (data) { 
            $("#Citation", context).html('<p>No Options</p>');
			//alert('error');
        }
    });
	return false;
}
_select = '';
//$('<select class="form-control folder_child" name="folder_child"/>');
function bindClassificationFolder(context)
{
	folder_Id = $(_select,context).val();
	alert('from func ' + folder_Id);
	$.ajax({
		method: 'post',
		url: 'http://localhost<?=$this->url('get_work_details')?>',
		data: {
			folder_Id: folder_Id
		},
		dataType: "json", 
		cache: false,
		success: function(data)
		{
			//alert('func, length is ' + data.folder_children.length);
			if(data.folder_children.length > 0)
			{
				_select = $('<select class="form-control folder_child" name="folder_child"/>');
				to_append = '';
				$.each(data.folder_children, function (key, val) {
					to_append += '<option value="'+val.id+'">'+val.text_fr+'</option>';
				});
				_select.append($('<option />'));
				_select.append(to_append);
				_select.appendTo('#Classification');
				_select.on('change',function(){
					bindClassificationFolder(document);
				});
			}
		},
		error: function (data) { 
			$("#Classification", context).html('<p>No Options</p>');
						//alert('error');
		}
	});
	return false;
}
$(document).ready(function () {	
	//Publisher
	bindPublisherAutocomplete(document);
	//add publisher rows
	$("#pub_add").click(function(){
		var pub_row = $('<tr name="pub_row[]"><input type="hidden" name="pub_id[]" id="pubId" value="">'+
							'<td><input type="text" class="form-control" name="pub_name[]" id="pubName" placeholder="none" /></td>'+
							'<td><input type="text" class="form-control" name="pub_yrFrom[]" id="pubyrFrom"/></td>'+
							'<td><input type="text" class="form-control" name="pub_yrTo[]" id="pubyrTo" /></td>'+
							'<!--<td><input type="text" class="form-control" name="pub_location" id="pubLocation" /></td>-->'+
							'<input type="hidden" name="publoc_id[]" id="publoc_id" value="">'+
							'<td><select class="form-control pub_locations" name="pub_location[]" id="pubLocation"><option value=""></option></select></td>'+
							'<td><button type="submit" class="btn btn-default" name="pub_remove" id="pub_remove" value="Remove">Remove</button></td>'+
							'</tr>');				
							
        $("#pub_table").append(pub_row);
		bindPublisherAutocomplete(pub_row);
		return false;
    });
	//remove publisher rows
	$("#pub_table").on('click','#pub_remove',function(){
        $(this).parent().parent().remove();
    });
	//agent
	bindAgentAutocomplete(document);
	$("#agent_add").click(function(){
		var agent_row = $('<tr><td><input type="hidden" name="agent_id[]" id="agentId" value="">'+
						'<select class="form-control agent_type" name="agent_type[]" id="agent_type">'+
						'<option value=""></option>'+
						<?php
						foreach($paginator_agtype as $row) :
						?>
						'<option value="<?=$row['id']?>"><?php echo $row['type']; ?></option>'+						
						<?php endforeach; ?>
						'</select>'+
						'</td>'+
						'<td><input type="text" class="form-control" name="agent_FirstName[]" id="agent_FirstName" /></td>'+
						'<td><input type="text" class="form-control" name="agent_LastName[]" id="agent_LastName" /></td>'+
						'<td><input type="text" class="form-control" name="agent_AlternateName[]" id="agent_AlternateName" /></td>'+
						'<td><input type="text" class="form-control" name="agent_OrganizationName[]" id="agent_OrganizationName" /></td>'+
						'<td><button type="submit" class="btn btn-default" name="agent_remove" id="agent_remove" value="Remove">Remove</button></td>'+
						'</tr>');				
							
        $("#agent_table").append(agent_row);
		bindAgentAutocomplete(agent_row);
		return false;
    });
	//remove agent rows
	$("#agent_table").on('click','#agent_remove',function(){
        $(this).parent().parent().remove();
    });
	//get attributes for selected worktypes
	$('#work_type',document).on('change', function() {	
		bindWorkTypeAttributes(document);		
	});
	//classification
	$('#subject_tree',document).on('change', function(){
		//bindClassificationFolder(document);
		folder_Id = $('#subject_tree',document).val();
		$.ajax({
        method: 'post',
        url: 'http://localhost<?=$this->url('get_work_details')?>',
		data: {
			folder_Id: folder_Id
		},
		dataType: "json", 
        cache: false,
        success: function(data)
        {
			_select = $('<select class="form-control folder_child" name="folder_child"/>');
			to_append = '';
			$.each(data.folder_children, function (key, val) {
				to_append += '<option value="'+val.id+'">'+val.text_fr+'</option>';
			});
			_select.append($('<option />'));
			_select.append(to_append);
			_select.appendTo('#Classification');
			_select.on('change',function(){
				bindClassificationFolder(document);
			});
		},
		error: function (data) { 
            $("#Classification", context).html('<p>No Options</p>');
			//alert('error');
        }
		});
	//return false;
	});
});
</script>
<div class="col-md-7">
<form id="personal-data" class="form-horizontal" method="POST" action="<?=$this->url('manage_work')?>">
<input type="hidden" name="action" value="work_new">
<?php 
	//get user
	$user = $this->isUser()->getUser();
?>
<input type="hidden" name="user" id="user" value="<?=$user?>">
<div class="tabbable">
  <ul class="nav nav-tabs">
    <li class="active">
      <a href="#General" data-toggle="tab">General</a>
    </li>
    <li>
      <a href="#Classification" data-toggle="tab">Classification</a>
    </li>  
	<li>
      <a href="#Publisher" data-toggle="tab">Publisher</a>
    </li>
	<li>
      <a href="#Agents" data-toggle="tab">Agents</a>
    </li>
	<li>
      <a href="#Citation" data-toggle="tab">Citation</a>
    </li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="General">      
		<div class="form-group required">
			<label class="col-xs-2 control-label">Title: </label>
			<div class="col-xs-10">
				<input type="text" class="form-control" name="new_worktitle" id="newworktitle" required="true"/>
			</div>
		</div>
		<div class="form-group">
			<label class="col-xs-2 control-label">Sub Title: </label>
			<div class="col-xs-10">
				<input type="text" class="form-control" name="new_worksubtitle" id="newworksubtitle" />
			</div>
		</div>
		<div class="form-group">
			<label class="col-xs-2 control-label">Parallel Title: </label>
			<div class="col-xs-10">
				<input type="text" class="form-control" name="new_workparalleltitle" id="newworkparalleltitle" />
			</div>
		</div>
		<div class="form-group">
			<label class="col-xs-2 control-label">Description: </label>
			<div class="col-xs-10">
				<textarea class="form-control" placeholder="Message" name="description" id="description"></textarea>
			</div>
		</div>
		<div class="form-group">
			<label class="col-xs-2 control-label">Type: </label>
			<div class="col-xs-10">
				<select class="form-control" name="work_type" id="work_type" required="true">
				<option value="">Choose Work Type</option>					
				<?php
					foreach($paginator as $row) :
				?>
				<option value="<?=$row['id']?>"><?php echo $row['type']; ?></option>							
				<?php endforeach; ?>
				</select>
			</div>
		</div>
		<div class="form-group">
			<label class="col-xs-2 control-label">Parent Work: </label>
			<div class="col-xs-10">
				<button type="submit" class="btn btn-default" name="lookup_parent" value="parent_lookup">Lookup</button>
			</div>
		</div>		
		<div class="form-group">
			<label class="col-xs-2 control-label">Status: </label>
			<div class="col-xs-10">
				<div class="radio">
					<label class="radio"><input checked type="radio" id="selectworkstatus" name="select_workstatus" value="00">In Progress</label>
					<label class="radio"><input type="radio" id="selectworkstatus" name="select_workstatus" value="0">Pending Review</label>
					<label class="radio"><input type="radio" id="selectworkstatus" name="select_workstatus" value="2">Unseen Source Doc</label>
					<label class="radio"><input type="radio" id="selectworkstatus" name="select_workstatus" value="1">Complete</label>
				</div>
			</div>
		</div>		 
    </div>
    <div class="tab-pane" id="Classification">
		<div class="form-group" id="class_grp">
			<label class="col-xs-2 control-label">Subject Tree: </label>
			<div class="col-xs-5">
				<select class="form-control subject_tree" name="subject_tree" id="subject_tree">
				<option value=""></option>
				<?php
					//fetch worktypes
					$table = new \App\Db\Table\Folder($this->adapter);
					$paginator = $table->findParent();
					foreach($paginator as $row) :
				?>
				<option value="<?=$row['id']?>"><?php echo $row['text_fr']; ?></option>							
				<?php endforeach; ?>
				</select>
			</div>
		</div>		
    </div>  
	<div class="tab-pane" id="Publisher">
		<div class="form-group">
		<table class="table table-striped table-condensed" name="pub_table" style="font-size:10pt;" id="pub_table">
        <thead>
			<th>Publisher</th>
			<th>Year From</th>
			<th>Year To</th>          
			<th>Location</th>
			<th>Remove</th>
		</thead>
		<tbody>
		<tr name="pub_row[]">
			<input type="hidden" name="pub_id[]" id="pubId" value="">
			<td><input type="text" class="form-control" name="pub_name[]" id="pubName" placeholder="none" /></td>
			<td><input type="text" class="form-control" name="pub_yrFrom[]" id="pubyrFrom"/></td>
			<td><input type="text" class="form-control" name="pub_yrTo[]" id="pubyrTo" /></td>
			<!--<td><input type="text" class="form-control" name="pub_location" id="pubLocation" /></td>-->
			<input type="hidden" name="publoc_id[]" id="publoc_id" value="">
			<td>
				<select class="form-control pub_locations" name="pub_location[]" id="pubLocation">
				<option value=""></option>				
				</select>
			</td>
			<td><button type="submit" class="btn btn-default" name="pub_remove" id="pub_remove" value="Remove">Remove</button></td>
		</tr>
		</tbody>
		</table>
		<button type="submit" class="btn btn-default" name="pub_add" id="pub_add" value="Add">Add</button> 
		</div>
	</div>
	<div class="tab-pane" id="Agents">
		<div class="form-group">
		<table class="table table-striped table-condensed" style="font-size:10pt;" id="agent_table">
        <thead>
          <th>Agent Type</th>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Alternate Name</th>
		  <th>Organization Name</th>
          <th>Remove</th>
		</thead>
		<tbody>
		<tr>
			<td>
				<input type="hidden" name="agent_id[]" id="agentId" value="">
				<select class="form-control agent_type" name="agent_type[]" id="agent_type">
				<option value=""></option>
				<?php
					//fetch agenttypes
					//$table = new \App\Db\Table\AgentType($this->adapter);
					//$paginator = $table->fetchAgentTypes();
					foreach($paginator_agtype as $row) :
				?>
				<option value="<?=$row['id']?>"><?php echo $row['type']; ?></option>						
				<?php endforeach; ?>
				</select>
			</td>
			<td><input type="text" class="form-control" name="agent_FirstName[]" id="agent_FirstName" /></td>
			<td><input type="text" class="form-control" name="agent_LastName[]" id="agent_LastName" /></td>
			<td><input type="text" class="form-control" name="agent_AlternateName[]" id="agent_AlternateName" /></td>
			<td><input type="text" class="form-control" name="agent_OrganizationName[]" id="agent_OrganizationName" /></td>
			<td><button type="submit" class="btn btn-default" name="agent_remove" id="agent_remove" value="Remove">Remove</button></td>
		</tr>
		</tbody>
		</table>
		<button type="submit" class="btn btn-default" name="agent_add" id="agent_add" value="Add">Add</button> 
		</div>
		<!-- Agent Lookup -->
		<div class="modal fade" id="agentLookup" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Modal title</h4>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
		</div>
		</div>
	</div>
	<div class="tab-pane" id="Citation">
		<!--<div class="form-group" id="divforoptions">
		</div>-->
		<!-- Work Type Attribute Options Lookup -->
		<div class="modal fade ig" id="optionsLookup" role="dialog">
		<div class="modal-dialog ig">
		<div class="modal-content ig">
			<div class="modal-header ig">
				<button type="button" class="close ig" data-dismiss="modal">&times;</button>
				<h4 class="modal-title ig" id="myModalLabel">Lookup</h4>
			</div>
			<div class="modal-body ig">
				<div class="form-group ig">
				<label class="col-xs-2 control-label ig">Title: </label>
				<div class="col-xs-10 ig">
					<input type="text" class="form-control ig" name="lookup_Option" id="lookupOption" />
				</div>
				</div>
				<div class="form-group ig">
				<div class="col-sm-offset-2 col-sm-10 ig">
				<button type="button" class="btn btn-primary option_search ig" id="option_search">Search</button>
				</div>
				</div>
				<div class="option_results ig">
				</div>
			</div>
			<div class="modal-footer ignore ig">
				<button type="button" class="btn btn-default option_lookup_close ig" data-dismiss="modal">Close</button>
			</div>
		</div>
		</div>
		</div>
	</div>
  </div>
</div>
<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<button type="submit" class="btn btn-default" name="submit_save" value="Save">Save</button> 
        <button type="submit" class="btn btn-default" name="submit_cancel" value="Cancel">Cancel</button>
	</div>
  </div>
</form>
</div>