<?php $this->headTitle('New Work'); ?>
<?php
		//fetch worktypes
		$table = new \App\Db\Table\WorkType($this->adapter);
		$paginator = $table->fetchAllWorkTypes();
		$itemsCount = $paginator->getTotalItemCount();
		$paginator->setItemCountPerPage($itemsCount);									
?>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script>
function bindPublisherAutocomplete(context) {
							
	//publisher enable/disable fields
	$("#pubLocation", context).prop("disabled", "disabled");
	
	//Publisher autocomplete
	$(function() {
		$( "#pubName", context).autocomplete({
			source: 'http://localhost<?=$this->url('get_work_details')?>?autofor=publisher',
			autoFocus:true,
			select: function(event, ui){
                $('#pubName', context).val(ui.item.label);
                $('#pubId', context).val(ui.item.id);
				$("#pubLocation", context).prop("disabled", false);
                return false;
            }
		});
	});	
	$('#pubName', context).on('autocompleteselect', function (e, ui) {
		var publisher_Id = ui.item.id;
		$.ajax({
        method: 'post',
        url: 'http://localhost<?=$this->url('get_work_details')?>',
		data: {
			publisher_Id: publisher_Id
		},
		dataType: "json", 
        cache: false,
        success: function(data)
        {
			$("#pubLocation", context).html('');
			$.each(data.publoc, function (key, val) {
                $("#pubLocation", context).append('<option id="' + val.id + '">' + val.label + '</option>');
            })
		},
		error: function () { 
            $("#pubLocation", context).html('<option id="-1">none available</option>');
        }
        });
    });	
}
//Agent Autocomplete
function bindAgentAutocomplete(context) 
{						
	//agent enable/disable fields
	$("#agent_FirstName", context).prop("disabled", "disabled");
	$("#agent_LastName", context).prop("disabled", "disabled");
	$("#agent_AlternateName", context).prop("disabled", "disabled");
	$("#agent_OrganizationName", context).prop("disabled", "disabled");
	
	$('#agent_type',context).on('change', function() {
		$("#agent_FirstName", context).prop("disabled", false);
		//agent first name autocomplete
		$(function() {
			$( "#agent_FirstName", context).autocomplete({
				source: 'http://localhost<?=$this->url('get_work_details')?>?autofor=agent',
				autoFocus:true,
				select: function(event, ui){
					$('#agent_FirstName', context).val(ui.item.label);
					$('#agentId', context).val(ui.item.id);				
					return false;
				}
			});
		});	
	});
	$('#agent_FirstName', context).on('autocompleteselect', function (e, ui) {
		if(ui.item.lname != '') {
			$("#agent_LastName", context).prop("disabled", false);
			$("#agent_LastName", context).val(ui.item.lname);
		}
		if(ui.item.alternate_name != '') {
			$("#agent_AlternateName", context).prop("disabled", false);
			$("#agent_AlternateName", context).val(ui.item.alternate_name);
		}
		if(ui.item.organization_name != '') {
			$("#agent_OrganizationName", context).prop("disabled", false);
			$("#agent_OrganizationName", context).val(ui.item.organization_name);
		}		
    });	
}
//WorkType Autocomplete
function bindWorkTypeAttributes(context)
{
	var worktype_Id = $('#work_type').val();
	$.ajax({
        method: 'post',
        url: 'http://localhost<?=$this->url('get_work_details')?>',
		data: {
			worktype_Id: worktype_Id
		},
		dataType: "json", 
        cache: false,
        success: function(data)
        {
			//var count = 1;
			//alert('heloo');
			$.each(data.worktype_attribute, function (key, val) {
				//alert(val.id + ' ' + val.field + ' ' + val.type);
                //$("#pubLocation", context).append('<option id="' + val.id + '">' + val.label + '</option>');
				$("<div>").attr("class","form-group optiondiv").attr("id","optiondiv").appendTo("#Citation");
				$("<label>").attr("class","col-xs-2 control-label").text(val.field).appendTo("#Citation");
				$("</label>").appendTo("#Citation");
				$("<div>").appendTo("#Citation");
				// append input control at end of form
				if(val.type == 'Textarea')
				{
					$("<textarea>")
						.attr("class","form-control autoc")
						.attr("id", val.field)
						.attr("name", val.field)
						.appendTo("#Citation");
					$("</textarea>").appendTo("#Citation");
				}
				if(val.type == 'Text')
				{
					$("<input />")
						.attr("type","text")
						.attr("class","form-control autoc")
						.attr("id", val.field)
						.attr("name", val.field)
						.appendTo("#Citation");

				}				
				if(val.type == 'Select')
				{
					var container = $('<div/>');
					$("<input />")
						.attr("type","text")
						.attr("class","form-control autoc Attributeoption")
						.attr("id", val.field + ':' +val.id)
						.attr("name", val.field)
						.appendTo(container);
					$("<button data-toggle='modal' data-target='#pubLookup'/>")
						.attr("class","btn btn-default optionLookupBtn")
						.attr("id","optionLookupBtn")
						.attr("data-toggle","modal")
						.attr("data-target","optionsLookup")
						.attr("value","Lookup")
						.text("Lookup")
						.appendTo(container);	
					container.appendTo('#Citation');
				}	
				$("</div>").appendTo("#Citation");
				$("</div>").appendTo("#Citation");
				//count = count + 1;
            })			
			$(".optionLookupBtn").on('click', function(e){
				//alert("hello");
				// show Modal
				var lookupBtn = this;
				$("#optionsLookup").modal('show');
				$('#optionsLookup').on('shown.bs.modal', function () {
					$('#lookupOption').focus()
					$('.option_search').on('click', function(e) {
						var attribute_Id = $(lookupBtn).prev().attr('id');
						var option = $('#lookupOption').val();
						$.ajax({
							method: 'post',
							url: 'http://localhost<?=$this->url('get_work_details')?>',
							data: {
								option: option,
								attribute_Id: attribute_Id
							},
							dataType: "json", 
							cache: false,
							success: function(data)
							{
								$(".option_results",context).html('');
								$(".option_results",context).append('<p>Search Results</p>');
								$.each(data.attribute_options, function (key, val) {
									$(".option_results",context).append('<p><a href="'+ val.title +'" class="link_options">' + val.title + '</a></p>');
									//alert(val.title);
								})
								//$("#pubLocation", context).html('');
								//$.each(data.publoc, function (key, val) {
								//$("#pubLocation", context).append('<option id="' + val.id + '">' + val.label + '</option>');
								//})
							},
							error: function () { 
								//$("#pubLocation", context).html('<option id="-1">none available</option>');
							}
						});	
						$(context).on("click", ".link_options", function(e) {
							//alert("log something");
							var linkval = $(this).attr('href');
							$(".Attributeoption").val() = linkval;
							console.log($(".Attributeoption").val());
							//console.log(linkval);
							return false;
						});
					});
				});
				return false;
			});
		},
		error: function (data) { 
            //$("#pubLocation", context).html('<option id="-1">none available</option>');
			alert('error');
        }
    });
	return false;
}
$(document).ready(function () {
	//Publisher
	bindPublisherAutocomplete(document);
	//add publisher rows
	$("#pub_add").click(function(){
		var pub_row = $('<tr><input type="hidden" name="pub_id" id="pubId" value="">'+
							'<td><input type="text" class="form-control" name="pub_name" id="pubName" placeholder="none" /></td>'+
							'<td><input type="text" class="form-control" name="pub_yrFrom" id="pubyrFrom"/></td>'+
							'<td><input type="text" class="form-control" name="pub_yrTo" id="pubyrTo" /></td>'+
							'<!--<td><input type="text" class="form-control" name="pub_location" id="pubLocation" /></td>-->'+
							'<td><select class="form-control pub_locations" name="pub_location" id="pubLocation"><option value=""></option></select></td>'+
							'<td><button type="submit" class="btn btn-default" name="pub_remove" id="pub_remove" value="Remove">Remove</button></td>'+
							'</tr>');				
							
        $("#pub_table").append(pub_row);
		bindPublisherAutocomplete(pub_row);
		return false;
    });
	//remove publisher rows
	$("#pub_table").on('click','#pub_remove',function(){
        $(this).parent().parent().remove();
    });
	//agent
	bindAgentAutocomplete(document);
	$("#agent_add").click(function(){
		var agent_row = $('<tr><td><input type="hidden" name="agent_id" id="agentId[]" value="">'+
						'<select class="form-control agent_type" name="agent_type" id="agent_type">'+
						'<option value=""></option>'+
						<?php
						foreach($paginator as $row) :
						?>
						'<option value="<?=$row['id']?>"><?php echo $row['type']; ?></option>'+						
						<?php endforeach; ?>
						'</select>'+
						'</td>'+
						'<td><input type="text" class="form-control" name="agent_FirstName" id="agent_FirstName" /></td>'+
						'<td><input type="text" class="form-control" name="agent_LastName" id="agent_LastName" /></td>'+
						'<td><input type="text" class="form-control" name="agent_AlternateName" id="agent_AlternateName" /></td>'+
						'<td><input type="text" class="form-control" name="agent_OrganizationName" id="agent_OrganizationName" /></td>'+
						'<td><button type="submit" class="btn btn-default" name="agent_remove" id="agent_remove" value="Remove">Remove</button></td>'+
						'</tr>');				
							
        $("#agent_table").append(agent_row);
		bindAgentAutocomplete(agent_row);
		return false;
    });
	//remove agent rows
	$("#agent_table").on('click','#agent_remove',function(){
        $(this).parent().parent().remove();
    });
	//get attributes for selected worktypes
	$('#work_type',document).on('change', function() {
		//var worktype_Id = ui.item.id;
		bindWorkTypeAttributes(document);
		
	});
	// Attach Button click event listener 
    
});
</script>
<div class="col-md-7">
    <form id="personal-data" class="form-horizontal" method="POST" action="<?=$this->url('manage_work')?>">
	<input type="hidden" name="action" value="work_new">
<div class="tabbable">
  <ul class="nav nav-tabs">
    <li class="active">
      <a href="#General" data-toggle="tab">General</a>
    </li>
    <li>
      <a href="#Classification" data-toggle="tab">Classification</a>
    </li>  
	<li>
      <a href="#Publisher" data-toggle="tab">Publisher</a>
    </li>
	<li>
      <a href="#Agents" data-toggle="tab">Agents</a>
    </li>
	<li>
      <a href="#Citation" data-toggle="tab">Citation</a>
    </li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="General">      
		<div class="form-group">
			<label class="col-xs-2 control-label">Title: </label>
			<div class="col-xs-10">
				<input type="text" class="form-control" name="new_worktitle" id="newworktitle" />
			</div>
		</div>
		<div class="form-group">
			<label class="col-xs-2 control-label">Sub Title: </label>
			<div class="col-xs-10">
				<input type="text" class="form-control" name="new_worksubtitle" id="newworksubtitle" />
			</div>
		</div>
		<div class="form-group">
			<label class="col-xs-2 control-label">Parallel Title: </label>
			<div class="col-xs-10">
				<input type="text" class="form-control" name="new_workparalleltitle" id="newworkparalleltitle" />
			</div>
		</div>
		<div class="form-group">
			<label class="col-xs-2 control-label">Description: </label>
			<div class="col-xs-10">
				<textarea class="form-control" placeholder="Message"></textarea>
			</div>
		</div>
		<div class="form-group">
			<label class="col-xs-2 control-label">Type: </label>
			<div class="col-xs-10">
				<select class="form-control" name="work_type" id="work_type">
				<option value="">Choose Work Type</option>					
				<?php
					foreach($paginator as $row) :
				?>
				<option value="<?=$row['id']?>"><?php echo $row['type']; ?></option>							
				<?php endforeach; ?>
				</select>
			</div>
		</div>
		<div class="form-group">
			<label class="col-xs-2 control-label">Parent Work: </label>
			<div class="col-xs-10">
				<button type="submit" class="btn btn-default" name="lookup_parent" value="parent_lookup">Lookup</button>
			</div>
		</div>		
		<div class="form-group">
			<label class="col-xs-2 control-label">Status: </label>
			<div class="col-xs-10">
				<div class="radio">
					<label class="radio"><input type="radio" id="selectworkstatus" name="select_workstatus" value="00">In Progress</label>
					<label class="radio"><input type="radio" id="selectworkstatus" name="select_workstatus" value="0">Pending Review</label>
					<label class="radio"><input type="radio" id="selectworkstatus" name="select_workstatus" value="2">Unseen Source Doc</label>
					<label class="radio"><input type="radio" id="selectworkstatus" name="select_workstatus" value="1">Complete</label>
				</div>
			</div>
		</div>		 
    </div>
    <div class="tab-pane" id="Classification">
		<div class="form-group" id="class_grp">
			<label class="col-xs-2 control-label">Subject Tree: </label>
			<div class="col-xs-5">
				<select class="form-control subject_tree" name="subject_tree">
				<option value=""></option>
				<?php
					//fetch worktypes
					$table = new \App\Db\Table\Folder($this->adapter);
					$paginator = $table->findParent();
					foreach($paginator as $row) :
				?>
				<option value="<?=$row['id']?>"><?php echo $row['text_fr']; ?></option>							
				<?php endforeach; ?>
				</select>
			</div>
		</div>		
    </div>  
	<div class="tab-pane" id="Publisher">
		<div class="form-group">
		<table class="table table-striped table-condensed" style="font-size:10pt;" id="pub_table">
        <thead>
			<th>Publisher</th>
			<th>Year From</th>
			<th>Year To</th>          
			<th>Location</th>
			<th>Remove</th>
		</thead>
		<tbody>
		<tr>
			<input type="hidden" name="pub_id" id="pubId[]" value="">
			<td><input type="text" class="form-control" name="pub_name" id="pubName" placeholder="none" /></td>
			<td><input type="text" class="form-control" name="pub_yrFrom" id="pubyrFrom"/></td>
			<td><input type="text" class="form-control" name="pub_yrTo" id="pubyrTo" /></td>
			<!--<td><input type="text" class="form-control" name="pub_location" id="pubLocation" /></td>-->
			<td>
				<select class="form-control pub_locations" name="pub_location" id="pubLocation">
				<option value=""></option>				
				</select>
			</td>
			<td><button type="submit" class="btn btn-default" name="pub_remove" id="pub_remove" value="Remove">Remove</button></td>
		</tr>
		</tbody>
		</table>
		<button type="submit" class="btn btn-default" name="pub_add" id="pub_add" value="Add">Add</button> 
		</div>
	</div>
	<div class="tab-pane" id="Agents">
		<div class="form-group">
		<table class="table table-striped table-condensed" style="font-size:10pt;" id="agent_table">
        <thead>
          <th>Agent Type</th>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Alternate Name</th>
		  <th>Organization Name</th>
          <th>Remove</th>
		</thead>
		<tbody>
		<tr>
			<td>
				<input type="hidden" name="agent_id" id="agentId[]" value="">
				<select class="form-control agent_type" name="agent_type" id="agent_type">
				<option value=""></option>
				<?php
					//fetch agenttypes
					$table = new \App\Db\Table\AgentType($this->adapter);
					$paginator = $table->fetchAgentTypes();
					foreach($paginator as $row) :
				?>
				<option value="<?=$row['id']?>"><?php echo $row['type']; ?></option>						
				<?php endforeach; ?>
				</select>
			</td>
			<td><input type="text" class="form-control" name="agent_FirstName" id="agent_FirstName" /></td>
			<td><input type="text" class="form-control" name="agent_LastName" id="agent_LastName" /></td>
			<td><input type="text" class="form-control" name="agent_AlternateName" id="agent_AlternateName" /></td>
			<td><input type="text" class="form-control" name="agent_OrganizationName" id="agent_OrganizationName" /></td>
			<td><button type="submit" class="btn btn-default" name="agent_remove" id="agent_remove" value="Remove">Remove</button></td>
		</tr>
		</tbody>
		</table>
		<button type="submit" class="btn btn-default" name="agent_add" id="agent_add" value="Add">Add</button> 
		</div>
		<!-- Agent Lookup -->
		<div class="modal fade" id="agentLookup" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Modal title</h4>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
		</div>
		</div>
	</div>
	<div class="tab-pane" id="Citation">
		<!-- Work Type Attribute Options Lookup -->
		<div class="modal fade" id="optionsLookup" role="dialog">
		<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title" id="myModalLabel">Lookup</h4>
			</div>
			<div class="modal-body">
				<div class="form-group">
				<label class="col-xs-2 control-label">Title: </label>
				<div class="col-xs-10">
					<input type="text" class="form-control" name="lookup_Option" id="lookupOption" />
				</div>
				</div>
				<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
				<button type="button" class="btn btn-primary option_search" id="option_search">Search</button>
				</div>
				</div>
				<div class="option_results">
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			</div>
		</div>
		</div>
		</div>
	</div>
  </div>
</div>
<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<button type="submit" class="btn btn-default" name="submit_save" value="Save">Save</button> 
        <button type="submit" class="btn btn-default" name="submit_cancel" value="Cancel">Cancel</button>
	</div>
  </div>
</form>
</div>