<?php $this->headTitle(($this->formAction == 'work_new' ? 'New' : 'Edit') . ' Work'); ?>
<?php
    $this->layout()->breadcrumbs .= '<a href="' . $this->url('manage_work') . '">Work</a> &gt; ' . ($this->formAction == 'work_new' ? 'New' : 'Edit');
    $this->layout()->page = 'Work/' . ($this->formAction == 'work_new' ? 'New' : 'Edit');
?>
<?php
    $this->headScript()->appendFile($this->url('home') . 'js/menu.js');
    $this->headScript()->appendFile($this->url('home') . 'js/work.js');

    //get user
    $user = $this->isUser()->getUser();
?>
<script type="text/template" id="template-agent-row">
    <tr>
        <td><input type="checkbox" name="removeAgent[]"></td>
        <td>
            <input type="hidden" name="agent_id[]" id="agentId" value="">
            <select class="form-control agent_type" name="agent_type[]" id="agent_type">
                <option value=""></option>
                <?php foreach ($this->agentTypes as $agentType): ?>
                    <option value="<?=$agentType['id'] ?>"><?=$agentType['type'] ?></option>
                <?php endforeach; ?>
            </select>
        </td>
        <td><input class="form-control" type="text" name="agent_LastName[]" /></td>
        <td><input class="form-control" type="text" name="agent_FirstName[]" /></td>
        <td><input class="form-control" type="text" name="agent_AlternateName[]" /></td>
        <td><input class="form-control" type="text" name="agent_OrganizationName[]" /></td>
    </tr>
</script>
<script type="text/template" id="template-fl-row">
    <tr name="source_fl_row[]">
        <td><input type="checkbox" name="removeFolder[]"></td>
        <td class="source_fl_col" name="source_fl_col" id="source_fl_col">
            <select class="form-control select_source_fl select2" name="select_source_fl[]">
                <option value=""></option>
                <?php foreach ($this->rootFolders as $folder) : ?>
                    <option value="<?=$folder['id'] ?>"><?=$folder['text_en'] ?></option>
                <?php endforeach; ?>
            </select>
        </td>
    </tr>
</script>
<script>
var ur = "";
var workURL = '<?=$this->url('get_work_details')?>';
var sattrURL = '<?=$this->url('edit_subattribute_values')?>';
// var sattrURL = '<?=$this->url('edit_option')?>';

$(document).ready(function() {
    function removeByName(name) {
        return function() {
            if ($('input[name="' + name + '[]"]:checked').length > 0) {
                $.each($('input[name="' + name + '[]"]:checked'), function () {
                    $('input[name="' + name + '[]"]:checked').closest("td").parent("tr").remove();
                });
                return false;
            } else {
                alert("No row(s) selected, Please select row(s) to remove.");
                return false;
            }
        }
    }
    // Publisher
    // make template
    var templatePubRow = $('[name="pub_row[]"]').eq(0).clone(true);
    templatePubRow.find("input, select").val("");
    templatePubRow.find(".pub-locations").html("");
    // bind autocomplete
    bindPublisherAutocomplete();
    // add publisher rows
    $("#pub_add").click(function() {
        var pub_row = templatePubRow.clone();
        $("#pub_table tbody").append(pub_row);
        bindPublisherAutocomplete();
        return false;
    });
    // remove publisher rows
    $("#pub_remove").on('click', removeByName("removePublisher"));

    // Agent
    // make template
    var templateAgentRow = $(".agent-row").eq(0).clone(true);
    templateAgentRow.find("input, select").val("");
    templateAgentRow.find(".agent-fname,.agent-alternate_name,.agent-organization_name").html("");
    // bind autocomplete
    bindAgentAutocomplete();
    //add agent rows
    $("#agent_add").click(function() {
        var agent_row = templateAgentRow.clone();
        $("#agent_table").append(agent_row);
        bindAgentAutocomplete();
        return false;
    });
    //remove agent rows
    $("#agent_remove").on('click', removeByName("removeAgent"));

    //get attributes for selected worktypes
    $('#work_type', document).on('change', function() {
        bindWorkTypeAttributes(document, workURL, sattrURL);
    });

    //classification
    //add classification rows
    $("#fl_add").on('click', function() {
        var fl_row = $($("#template-fl-row").html());
        $("#source_fl_table").append(fl_row);
        return false;
    });
    //remove classification rows
    $('#fl_remove').on('click', removeByName("removeFolder"));

    $('table[name="source_fl_table"]').on('change', ".select_source_fl", function() {
        mergeClassification(this, document, workURL, 'source');
        return false;
    });

   //Parent Lookup
   $('#parentLookup_modal').on('shown.bs.modal', function() {
       bindParentWork(document, workURL);
       return false;
   });

   //Remove Parent Lookup
   /*
   $('.pr_work_div').on('click', '#parent_removeBtn', function() {
       //alert("remove");
       $('#pr_work_lookup_id').val('');
       $('.pr_work_div').html('');
       $('.pr_work_div').append('<button type="button" class="btn btn-default parent_lookupBtn" name="parent_lookupBtn" id="parent_lookupBtn" data-toggle="modal" data-target="#parentLookup_modal">Lookup</button>');
       return false;
   });
   */

    $('.addNewPubLink').on('click', function() {
        var lnk = $('.addNewPubLink', document);
        addNewPublisher(document,workURL,lnk);
        return false;
    });

    $('.addNewAgLink').on('click', function() {
        var lnk = $('.addNewAgLink', document);
        addNewAgent(document,workURL,lnk);
        return false;
    });

    $('#submit_save').on('click', function() {
        $('#General').find('input:required').each(function() {
            // Find the tab-pane that this element is inside, and get the id
            var $closest = $(this).closest('.tab-pane');
            var id = $closest.attr('id');
            // Find the link that corresponds to the pane and have it show
            $('.nav a[href="#' + id + '"]').tab('show');

            // Only want to do it once
            return false;
        });

        $("tr", "#source_fl_table").each(function() {
            const values = $('.select_source_fl', this).map(function() {
                return $(this).val();
            }).get();
            var newInput = $('<input type="hidden" name="classification_row[]" value="">');
            newInput.val(values);
            $("#work-data-form").append(newInput);
        });
        return true;
    });
});
 </script>
<form id="work-data-form" class="form-horizontal" method="POST" action="<?= $this->url('manage_work') ?>">
    <input type="hidden" name="id" value="<?=$this->work['id'] ?? 'NEW' ?>">
    <input type="hidden" name="action" value="<?=$this->formAction ?>">
    <!--<input type="hidden" name="arr[]" id="arrs" value="frm jquery">-->
    <input type="hidden" name="user" id="user" value="<?=$user ?>">
    <ul class="nav nav-tabs">
        <li class="active">
            <a href="#General" data-toggle="tab">General</a>
        </li>
        <li>
            <a href="#Classification" data-toggle="tab">Classification</a>
        </li>
        <li>
            <a href="#Publisher" data-toggle="tab">Publisher</a>
        </li>
        <li>
            <a href="#Agents" data-toggle="tab">Agents</a>
        </li>
        <li>
            <a href="#Citation" data-toggle="tab">Citation</a>
        </li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="General">
            <div class="form-group required">
                <label class="col-sm-2 control-label">Title: </label>
                <div class="col-sm-10 col-md-8">
                    <input class="form-control" type="text" name="work_title" value="<?=$this->work['title'] ?? '' ?>" required="true" size="80"/>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Sub Title: </label>
                <div class="col-sm-10 col-md-8">
                    <input class="form-control" type="text" name="work_subtitle" value="<?=$this->work['subtitle'] ?? '' ?>" size="80"/>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Parallel Title: </label>
                <div class="col-sm-10 col-md-8">
                    <input class="form-control" type="text" name="work_paralleltitle" value="<?=$this->work['paralleltitle'] ?? '' ?>" size="80"/>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Description: </label>
                <div class="col-sm-10 col-md-8">
                    <textarea class="form-control" name="description" id="description" rows="3" placeholder="Message"><?=$this->work['description'] ?? '' ?></textarea>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Type: </label>
                <div class="col-sm-10 col-md-8">
                    <select class="form-control" name="work_type" id="work_type" required="true">
                        <option value="">Choose Work Type</option>
                        <?php foreach ($this->workTypes as $workType): ?>
                            <option value="<?=$workType['id'] ?>"<?=($workType['id'] == $this->work['type_id']) ? ' selected' : '' ?>><?=$workType['type'] ?></option>
                        <?php endforeach; ?>
                    </select>
                    <?php if (!empty($this->work['type_id'])): ?>
                        <script>bindWorkTypeAttributes(document, workURL, sattrURL);</script>
                    <?php endif; ?>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Parent Work: </label>
                <div class="col-sm-10 col-md-8">
                    <div id="parent-work-lookup">
                        <input type="hidden" class="acs-hidden" name="pr_work_lookup_id" id="pr_work_lookup_id" value="<?=$this->work['parent']['id'] ?? '' ?>">
                        <input class="acs-input form-control" type="text" placeholder="Type to search" value="<?=$this->work['parent']['title'] ?? '' ?>" />
                    </div>
                    <script>bindParentWorkAutocomplete()</script>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Status: </label>
                <div class="col-sm-10 col-md-8">
                    <label><input type="radio" name="work_status" value="00"<?=($this->work['status'] == '00') ? ' checked' : '' ?>> In Progress</label><br/>
                    <label><input type="radio" name="work_status" value="0" <?=($this->work['status'] == '0') ? ' checked' : '' ?>> Pending Review</label><br/>
                    <label><input type="radio" name="work_status" value="2" <?=($this->work['status'] == '2') ? ' checked' : '' ?>> Unseen Source Doc</label><br/>
                    <label><input type="radio" name="work_status" value="1" <?=($this->work['status'] == '1') ? ' checked' : '' ?>> Complete</label>
                </div>
            </div>
        </div>
        <div class="tab-pane" id="Classification">
            <nav>
                <button type="button" class="btn btn-outline-secondary btn-sm" id="fl_add" value="Add">Add</button>
                <button type="button" class="btn btn-outline-secondary btn-sm" id="fl_remove" value="Remove">Remove</button>
            </nav>
            <?php
                if (!isset($this->classifications)) {
                    $this->classifications = $this->rootFolders;
                }
            ?>
            <div id="class_grp">
                <label class="control-label">Subject Tree: </label>
                <table name="source_fl_table" id="source_fl_table">
                    <?php foreach ($this->classifications as $folderChain): ?>
                    <tr name="source_fl_row[]">
                        <td><input type="checkbox" name="removeFolder[]"></td>
                        <?php foreach ($folderChain as $folderSiblings): ?>
                        <td class="source_fl_col" name="source_fl_col" id="source_fl_col">
                            <select class="form-control select_source_fl select2" name="select_source_fl[]">
                                <?php foreach($folderSiblings as $folder): ?>
                                    <option value="<?=$folder['id'] ?>"<?=isset($folder['selected']) ? ' selected' : '' ?>><?=$folder['text_en'] ?></option>
                                <?php endforeach; ?>
                            </select>
                        </td>
                        <?php endforeach; ?>
                    </tr>
                    <?php endforeach; ?>
                </table>
            </div>
        </div>
        <div class="tab-pane" id="Publisher">
            <nav>
                <button type="button" class="btn btn-secondary btn-sm" id="pub_add" value="Add">Add</button>
                <button type="button" class="btn btn-secondary btn-sm" id="pub_remove" value="Remove">Remove</button>
            </nav>
            <?php
                if (!isset($this->publishers)) {
                    $this->publishers = [['locations' => []]]; // One empty publisher
                }
            ?>
            <table class="table table-condensed" name="pub_table" id="pub_table">
            <thead>
                <th></th>
                <th>Publisher</th>
                <th>Location</th>
                <th>Year From</th>
                <th>Year To</th>
            </thead>
            <tbody>
                <?php foreach ($this->publishers as $i=>$publisher): ?>
                    <tr name="pub_row[]">
                        <td><input type="checkbox" name="removePublisher[]"></td>
                        <td>
                            <div class="pub-name-acs acs-unset">
                                <input class="acs-hidden" type="hidden" name="pub_id[]" value="<?=$publisher['publisher_id'] ?? ''?>">
                                <input class="acs-input form-control" type="text" placeholder="Type to search publishers" value="<?=$publisher['name'] ?? ''?>"/>
                            </div>
                        </td>
                        <td>
                            <select class="form-control pub-locations" name="pub_location[]">
                                <?php foreach($publisher['locations'] as $location): ?>
                                    <option value="<?=$location['id'] ?? ''?>"<?=($location['id'] ?? '') == $publisher['location_id'] ? ' selected' : ''?>>
                                        <?=$location['location'] ?? ''; ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </td>
                        <td class="yrFrom">
                            <input class="form-control" name="pub_yrFrom[]" value="<?=empty($publisher['publish_year']) ? null : $publisher['publish_year'] ?>" size="4" maxlength="4"/>
                        </td>
                        <td class="yrTo">
                            <input class="form-control" name="pub_yrTo[]" value="<?=empty($publisher['publish_year_end']) ? null : $publisher['publish_year_end'] ?>" size="4" maxlength="4"/>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
            </table>
        </div>
        <div class="tab-pane" id="Agents">
            <nav>
                <button type="button" class="btn btn-secondary btn-sm" name="agent_add" id="agent_add" value="Add">Add</button>
                <button type="button" class="btn btn-secondary btn-sm" name="agent_remove" id="agent_remove" value="Remove">Remove</button>
            </nav>
            <?php
                if (!isset($this->agents) || empty($this->agents)) {
                    $this->agents = [[]];
                }
            ?>
            <table class="table table-condensed" id="agent_table">
            <thead>
                <th></th>
                <th>Agent Type</th>
                <th>Last Name</th>
                <th>First Name</th>
                <th>Alternate Name</th>
                <th>Organization Name</th>
            </thead>
            <tbody>
                <?php foreach ($this->agents as $agent): ?>
                <tr class="agent-row">
                    <td><input type="checkbox" name="removeAgent[]"></td>
                    <td>
                        <select class="form-control agent_type" name="agent_type[]" id="agent_type">
                            <option value=""></option>
                            <?php foreach ($this->agentTypes as $agentType): ?>
                                <option value="<?=$agentType['id'] ?>"<?=($agent['agenttype_id'] ?? -1) == $agentType['id'] ? ' selected' : '' ?>>
                                    <?=$agentType['type']; ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </td>
                    <td name="agLnCol">
                        <div class="agent-acs acs-unset">
                            <input class="acs-hidden" type="hidden" name="agent_id[]" id="agentId" value="">
                            <input class="acs-input form-control" type="text" placeholder="Type to search agents by last name" value="<?=$agent['lname'] ?? ''?>"/>
                        </div>
                    </td>
                    <td class="agent-fname"><?=$agent['fname'] ?? ''?></td>
                    <td class="agent-alternate_name"><?=$agent['alternate_name'] ?? ''?></td>
                    <td class="agent-organization_name"><?=$agent['organization_name'] ?? ''?></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
            </table>
        </div>
        <?php // Pass citations to JS
            foreach ($this->citationTypes as $type) {
                if (isset($this->citations[$type['id']])): ?>
                    <input type="hidden" id="work-citation-<?=$type['id'] ?>" value="<?=$this->citations[$type['id']] ?>"/>
                <?php endif;
            }
        ?>
        <div class="tab-pane" id="Citation">
            <p>Select a Work Type under General</p>
        </div>
    </div>
    <!-- Submit buttons -->
    <div class="form-group">
        <div class="col-sm-10 col-sm-offset-2">
            <button type="submit" class="btn btn-primary" name="submit_save" id="submit_save" value="Save">Save</button>
            <button type="submit" class="btn btn-link" name="submit_cancel" value="Cancel" formnovalidate>Cancel</button>
        </div>
    </div>
</form>
<div class="modal fade ig" id="addAttributeOption" role="dialog">
    <div class="modal-dialog ig">
        <div class="modal-content ig">
            <div class="modal-header ig">
                <button type="button" class="close ig" data-dismiss="modal">&times;</button>
                <h4 class="modal-title ig" id="newAttrOptionModalLabel">New Attribute Option</h4>
            </div>
            <div class="modal-body ig clearfix">
                <div class="alert alert-success hidden" id="addAttributeSuccess">
                    Option successfully added
                </div>
                <form class="form-horizontal" method="post" action="<?= $this->url('manage_publisher') ?>">
                    <div>
                        <label class="control-label"><span id="new-option-label">Option</span>: </label>
                        <input class="form-control" type="text" class="form-control" name="name_option" id="newoption" required="true" />
                    </div>
                    <button type="submit" class="btn btn-primary pull-right" id="addNewOpt" name="submitt" value="Save">Save</button>
                </form>
                <button type="button" class="btn btn-default add_new_opt_close ig pull-left" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
