<?php $this->headTitle('Manage Work'); ?>
<?php
    $this->layout()->breadcrumbs .= '<a href="' . $this->url('manage_work') . '">Work</a> &gt; Manage';
    $this->layout()->page = "Work/Manage";
?>
<style>
table {
    width: 100%;
}
td {
    max-width: 0;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}
td.title {
    width: 55%;
}
td.type {
    width: 10%;
}
td.created {
    width: 12.5%;
}
td.modified {
    width: 12.5%;
}
</style>
<script type='text/javascript'>
$(document).ready(function () {
    //Check if records are selected for delete
    $("#delWork").on('click', function () {
        if ($("#workListTable input:checkbox:checked").length > 0) {
            // any one is checked
            return true;
        } else {
            // none is checked
            alert("No work(s) selected, Please select work(s) to delete.");
            return false;
        }
    });
});
</script>
<div class="col-lg-12">
<p>
<?php foreach ($this->carat as $value) { ?>
    <a href="<?=$this->url('manage_work')?><?='?letter=' . $value['letter'] . '&action=alphasearch'?>">
    <?php echo ' ' . $value['letter'] . ' '; ?></a><?php echo '|';  ?>
<?php } ?>
<?php
$q_str = "";
//$sort_ord = isset($_GET['sort_ord'])?!$_GET['sort_ord']:1;
$sort_ord = isset($_GET['sort_ord'])?($_GET['sort_ord'] == "ASC"?"DESC":"ASC"):"ASC";
if ($request->getqueryParams() != null) {
    $params = $request->getqueryParams();
    $q_str = $_SERVER["QUERY_STRING"];
    if(preg_match('/(?P<pg>page=\d+&)?(?P<action>.*)(?P<ord>&orderBy=\w+&sort_ord=\w+)/', $q_str, $matches)) {
        $q_str = preg_replace('/(?P<pg>page=\d+&)?(?P<action>.*)(?P<ord>&orderBy=\w+&sort_ord=\w+)/', $matches['action'], $q_str);
    }
}
?>
<br> <a href="<?php echo $this->url('new_work') ?>"><b style="text-decoration: underline;">Add Work</b></a>
</p>
        <form action="<?=$this->url('delete_work')?><?='?action=delete'?>" method="post">
        <table class="table table-striped table-condensed" id="workListTable" style="font-size:10pt;">
        <thead>
        <tr>
          <?php if (isset($params['action'])) { ?>
                    <th>&nbsp;&nbsp;</th>
                    <th><a href="<?=$this->url('manage_work')?><?='?' . $q_str . '&orderBy=title&sort_ord=' . $sort_ord?>">Title</a></th>
                    <th><a href="<?=$this->url('manage_work')?><?='?' . $q_str . '&orderBy=type&sort_ord=' . $sort_ord?>">Type</a></th>
                    <th><a href="<?=$this->url('manage_work')?><?='?' . $q_str . '&orderBy=status&sort_ord=' . $sort_ord?>">Status</a></th>
                    <th><a href="<?=$this->url('manage_work')?><?='?' . $q_str . '&orderBy=created&sort_ord=' . $sort_ord?>">Created</th>
                    <th><a href="<?=$this->url('manage_work')?><?='?' . $q_str . '&orderBy=modified&sort_ord=' . $sort_ord?>">Modified</th>
          <?php } else { ?>
                    <th>&nbsp;&nbsp;</th>
                    <th><a href="<?=$this->url('manage_work')?><?='?orderBy=title&sort_ord=' . $sort_ord?>">Title</a></th>
                    <th><a href="<?=$this->url('manage_work')?><?='?orderBy=type&sort_ord=' . $sort_ord ?>">Type</a></th>
                    <th><a href="<?=$this->url('manage_work')?><?='?orderBy=status&sort_ord=' . $sort_ord ?>">Status</a></th>
                    <th><a href="<?=$this->url('manage_work')?><?='?orderBy=created&sort_ord=' . $sort_ord?>">Created</a></th>
                    <th><a href="<?=$this->url('manage_work')?><?='?orderBy=modified&sort_ord=' . $sort_ord?>">Modified</a></th>
          <?php } ?>
        </tr>
        </thead>
        <tbody>
        <?php $escaper = new Zend\Escaper\Escaper('utf-8'); ?>
        <?php foreach($this->rows as $row) :
        ?>
        <tr>
        <td>
            <input type="checkbox" id="selWork" name="selectWork[]" value=<?=$row['id']?>>
        </td>
        <td class="title">
            <a href="<?=$this->url('edit_work')?><?='?action=edit&id=' . $row['id']?>"><?php echo $escaper->escapeHtml($row['title']); ?></a>
        </td>
        <td class="type">
            <?php
                //fetch work type based on type_id
                $table = new \VuBib\Db\Table\WorkType($adapter);
                $work_type = $table->findRecordById($row['type_id']);
                $type = $work_type['type'];
                echo $escaper->escapeHtml($type);
            ?>
        </td>
        <td>
            <?php
                    if (null === $row['status']): ?>
                        <img src="../images/images_admin/inactive.gif" alt="In progress" title="Inactive">
            <?php    elseif ($row['status'] == 1): ?>
                        <img src="../images/images_admin/active.gif" alt="Complete" title="Active">
            <?php    elseif ($row['status'] == 0 || $row['status'] == 2): ?>
                        <img src="../images/images_admin/review.gif" alt="Needs Review" title="Needs Review">
            <?php    endif;
                    //echo $row['status'];
            ?>
        </td>
        <td class="created">
            <?php
                    //fetch created username based on create_user_id
                    $table = new \VuBib\Db\Table\User($adapter);
                    $cuser = $table->findRecordById($row['create_user_id']);
                    $c_user = $cuser['username'];
                    echo $c_user . " " . date("M d, y", strtotime($row['create_date']));
            ?>
        </td>
        <td class="modified">
            <?php

                if($row['modify_user_id'] != '')
                {
                    //fetch modified username based on modify_user_id
                    $table = new \VuBib\Db\Table\User($adapter);
                    $muser = $table->findRecordById($row['modify_user_id']);
                    $m_user = $muser['username'];
                    echo $m_user . " " . date("M d, y", strtotime($row['modify_date']));
                }
            ?>
        </td>
        </tr>
        <?php endforeach; ?>
        </tbody>
        </table>
        <!--<button type="submit" class="btn btn-secondary" name="work_delete" id="work_delete" value="Delete">Delete</button>-->
        <input class="btn btn-default" type="submit" name="delWork" id="delWork" value="Delete">
        </form>
        <?php if($this->countp > 1) {
        //echo "prev is $this->previous <br />";
        //echo "next is $this->next <br />";?>
        <form method="get" action="page">
            <?=$this->paginationControl($this->rows,
                'Sliding',
                'vubib::controls',
                [
                    'route' => 'manage_work',
                    'extraParams' => $searchParams,
                ]
            );?>
        </form>
        <?php } ?>
</div>