<?php $this->headTitle('View Work'); ?>
<?php
    $this->layout()->breadcrumbs .= '<a href="' . $this->url('manage_work') . '">Work</a> &gt; View';
    $this->layout()->page = "Work/View";
    $sanitize = new \VuBib\View\Helper\SanitizeHtml();
?>
<ul class="nav nav-tabs">
    <li class="active">
        <a href="#General" data-toggle="tab">General</a>
    </li>
    <li>
        <a href="#Classification" data-toggle="tab">Classification</a>
    </li>
    <li>
        <a href="#Publisher" data-toggle="tab">Publisher</a>
    </li>
    <li>
        <a href="#Agents" data-toggle="tab">Agents</a>
    </li>
    <li>
        <a href="#Citation" data-toggle="tab">Citation</a>
    </li>
</ul>
<div class="tab-content">
    <div class="tab-pane active" id="General">
        <table class="table table-striped table-condensed">
            <tr>
                <th>Title:</th>
                <td><?=$sanitize($this->work['title'] ?? '') ?></td>
            </tr>
            <tr>
                <th>Sub Title:</th>
                <td><?=$sanitize($this->work['subtitle'] ?? '') ?></td>
            </tr>
            <tr>
                <th>Parallel Title:</th>
                <td><?=$sanitize($this->work['paralleltitle'] ?? '') ?></td>
            </tr>
            <tr>
                <th>Description:</th>
                <td><?=$sanitize($this->work['description'] ?? '') ?></td>
            </tr>
            <tr>
                <th>Type:</th>
                <td>
                    <?php foreach ($this->workTypes as $workType): ?>
                        <?php if($workType['id'] == $this->work['type_id']) {
                            echo $sanitize($workType['text_fr']);
                            break;
                        } ?>
                    <?php endforeach; ?>
                </td>
            </tr>
            <tr>
                <th>Parent Work:</th>
                <td><?=$sanitize($this->work['parent']['title'] ?? '') ?></td>
            </tr>
            <tr>
                <th>Status:</th>
                <td>
                    <?=($this->work['status'] == '00') ? 'In Progress' : '' ?>
                    <?=($this->work['status'] == '0') ? 'Pending Review' : '' ?>
                    <?=($this->work['status'] == '2') ? 'Unseen Source Doc' : '' ?>
                    <?=($this->work['status'] == '1') ? 'Complete' : '' ?>
                </td>
            </tr>
        </table>
    </div>
    <div class="tab-pane" id="Classification">
        <h2>Subject Tree:</h2>
        <table class="table table-striped table-condensed">
            <?php foreach ($this->classifications as $folderChain): ?>
                <tr>
                    <?php foreach ($folderChain as $folderSiblings): ?>
                        <td>
                            <?php foreach($folderSiblings as $folder) {
                                if (isset($folder['selected'])) {
                                    echo $sanitize($folder['text_fr']);
                                    break;
                                }
                            } ?>
                        </td>
                    <?php endforeach; ?>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
    <div class="tab-pane" id="Publisher">
        <table class="table table-striped table-condensed">
            <thead>
                <th>Publisher</th>
                <th>Location</th>
                <th>Year From</th>
                <th>Year To</th>
            </thead>
            <tbody>
                <?php foreach ($this->publishers as $publisher): ?>
                    <tr>
                        <td><?=$sanitize($publisher['name'] ?? '')?></td>
                        <td>
                            <?php foreach($publisher['locations'] as $location) {
                                if ($location['id'] == $publisher['location_id']) {
                                    echo $sanitize($location['location']);
                                    break;
                                }
                            } ?>
                        </td>
                        <td><?=$publisher['publish_year'] == 0 ? '' : $publisher['publish_year'] ?></td>
                        <td><?=$publisher['publish_year_end'] == 0 ? '' : $publisher['publish_year_end'] ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <div class="tab-pane" id="Agents">
        <?php
            if (!isset($this->agents)) {
                $this->agents = [[]];
            }
        ?>
        <table class="table table-condensed" id="agent_table">
            <thead>
                <th>Agent Type</th>
                <th>Last Name</th>
                <th>First Name</th>
                <th>Alternate Name</th>
                <th>Organization Name</th>
            </thead>
            <tbody>
                <?php foreach ($this->agents as $agent): ?>
                    <tr>
                        <td>
                            <?php foreach ($this->agentTypes as $agentType) {
                                if ($agent['agenttype_id'] == $agentType['id']) {
                                    echo $sanitize($agentType['type']);
                                    break;
                                }
                            } ?>
                        </td>
                        <td><?=$sanitize($agent['lname'] ?? '') ?></td>
                        <td><?=$sanitize($agent['fname'] ?? '') ?></td>
                        <td><?=$sanitize($agent['alternate_name'] ?? '') ?></td>
                        <td><?=$sanitize($agent['organization_name'] ?? '') ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <div class="tab-pane" id="Citation">
        <?php
        ?>
        <table class="table table-striped table-condensed">
            <?php foreach ($this->citationTypes as $type): ?>
                <tr>
                    <th><?=$sanitize($type['field']); ?></th>
                    <td><?=$sanitize($this->citations[$type['id']] ?? '') ?></td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>
