<?php $this->headTitle('Manage Classification'); ?>
<?php
    $this->layout()->breadcrumbs .= '<a href="' . $this->url('manage_classification') . '">Classification</a> &gt; Manage';
    $this->layout()->page = "Classification/Manage";
 ?>
 <?php
if ($request->getqueryParams('id') !== null) {
    $params = $request->getqueryParams();
    $parent_id = $params['id'] ?? -1;
}
 ?>
<div class="col-md-9">
    <p style="font-weight:bold;" id="view_hierarchy">
        Viewing: <a href="<?= $this->url('manage_classification') ?>">Top</a>
        <?php $trailLen = count($this->trail); ?>
        <?php foreach ($this->trail as $i => $parent): ?>
            &gt;
            <?php if($i == $trailLen - 1): ?>
                <?=$this->escapeHtml($parent['text_fr']) ?>
            <?php else: ?>
                <a href="<?= $this->url('manage_classification') ?><?= '?id=' . $parent['id'] . '&fl=' . $parent['text_fr'] . '&action=get_children' ?>">
                    <?=$this->escapeHtml($parent['text_fr']) ?>
                </a>
            <?php endif; ?>
        <?php endforeach; ?>
    </p>
    <a href="<?php echo $this->url('new_classification') ?><?='?action=new' . '&parent_id=' . $parent_id . '&from=manage'?>">
    <b class="addEle" style="float:left; padding-left: 15px; text-decoration: underline;">Add Branch</b></a><br/>
    <table class="table table-striped table-condensed" style="font-size:10pt;">
        <thead>
            <tr>
                <th>Title</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
<?php $escaper = new Zend\Escaper\Escaper('utf-8'); ?>
<?php foreach ($this->rows as $row) : ?>
                <tr>
                    <td><a href="<?= $this->url('manage_classification') ?><?= '?id=' . $row['id'] . '&fl=' . $escaper->escapeHtml($row['text_fr']) . '&action=get_children' ?>" class="folder_name">
                <?php echo $escaper->escapeHtml($row['text_fr']); ?></a></td>
                    <td>
                        <a href="<?= $this->url('edit_classification') ?><?= '?id=' . $row['id'] . '&action=edit' ?>">Edit</a>
                        |
                        <a href="<?= $this->url('move_classification') ?><?= '?id=' . $row['id'] . '&action=move' ?>">Move</a>
                    </td>
                </tr>
<?php endforeach; ?>
        </tbody>
    </table>
            <?php if ($this->countp > 1) { ?>
        <form method="get" action="page">
        <?=
        $this->paginationControl($this->rows, 'Sliding', 'vubib::controls', [
            'route' => 'manage_classification',
            'extraParams' => $searchParams,
            ]
        );
        ?>
        </form>
        <?php } ?>
</div>
