<?php
    $this->headTitle('Move Classification');
    $this->layout()->breadcrumbs .= '<a href="' . $this->url('manage_classification') . '">Classification</a> &gt; Move';
    $this->layout()->page = "Classification/Move";
?>

<div class="row">
    <div class="col-xs-12 col-md-6">
        <p class="moveError alert alert-danger" style="display:none">Cannot move a classification into itself.</p>

        <form id="move-folder-data" name="form_mv_classification" method="POST" action="<?= $this->url('manage_classification') ?>?id=<?=$this->parent_id ?>&action=get_children">
            <input type="hidden" name="action" value="move"/>
            <input type="hidden" name="id" value="<?=$this->id ?>"/>
            <input type="hidden" name="new_parent" id="new_parent_id"/>

            <?=$this->render('vubib::classification/_folder-list'); ?>

            <div class="form-group">
                <button type="submit" class="btn btn-primary" name="submit_save" id="submit_save" value="Save">Save</button>
                <button type="submit" class="btn btn-default" name="submit" value="Cancel">Cancel</button>
            </div>
        </form>
    </div>
</div>

