<?php $this->headTitle('New Classification'); ?>
<?php
    $this->layout()->breadcrumbs .= '<a href="' . $this->url('manage_classification') . '">Classification</a> &gt; New';
    $this->layout()->page = "Classification/New";
 ?>
<?php
if ($request->getqueryParams('action') !== null) {
    $params = $request->getqueryParams();
    $action = $params['action'];
    $parent_name = '- root folder -';
    $parent_id = $params['parent_id'] ?? -1;
    if ($parent_id != -1) {
        $table = new \VuBib\Db\Table\Folder($this->adapter);
        $fl_row = $table->findRecordById($parent_id);
        $parent_name = $fl_row['text_fr'];
    }
}
$escaper = new Zend\Escaper\Escaper('utf-8');
?>
<h2>Add a Branch</h2>
<div class="row">
    <form class="col-sm-12 col-lg-6" method="post" action="<?= $this->url('manage_classification') ?>?id=<?=$parent_id ?>&action=get_children">
        <input type="hidden" name="action" value="<?=$action ?>">
        <input type="hidden" name="parent_id" value="<?=$parent_id ?>">
        <div class="form-group">
            <label class="control-label">Parent:</label>
            <input type="text" class="form-control" value="<?=$parent_name ?>" readonly />
        </div>
        <div class="form-group">
            <label class="control-label" for="newclassif_sortorder">Sort Order: </label>
            <input type="text" class="form-control" name="new_classif_sortorder" id="newclassif_sortorder" />
        </div>
        <div class="form-group">
            <label class="control-label" for="newclassif_frenchtitle">French Title: </label>
            <input type="text" class="form-control" name="new_classif_frenchtitle" id="newclassif_frenchtitle" />
        </div>
        <div class="form-group">
            <label class="control-label" for="newclassif_engtitle">English Title: </label>
            <input type="text" class="form-control" name="new_classif_engtitle" id="newclassif_engtitle" />
        </div>
        <div class="form-group">
            <label class="control-label" for="newclassif_germantitle">German Title: </label>
            <input type="text" class="form-control" name="new_classif_germantitle" id="newclassif_germantitle" />
        </div>
        <div class="form-group">
            <label class="control-label" for="newclassif_dutchtitle">Dutch Title: </label>
            <input type="text" class="form-control" name="new_classif_dutchtitle" id="newclassif_dutchtitle" />
        </div>
        <div class="form-group">
            <label class="control-label" for="newclassif_spanishtitle">Spanish Title: </label>
            <input type="text" class="form-control" name="new_classif_spanishtitle" id="newclassif_spanishtitle" />
        </div>
        <div class="form-group">
            <label class="control-label" for="newclassif_italiantitle">Italian Title: </label>
            <input type="text" class="form-control" name="new_classif_italiantitle" id="newclassif_italiantitle" />
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary" name="submit" value="Save">Save</button>
            <button type="submit" class="btn btn-default" name="submit" value="Cancel">Cancel</button>
        </div>
    </form>
</div>