<html>
<head>
  <title>Panta Rhei - Administration</title>
  <link rel="stylesheet" href="<?=$this->url('home')?>vendor/css/bootstrap-3.3.7.min.css" >
  <link rel="stylesheet" href="<?=$this->url('home')?>css/main.css" media="screen" />
  <link rel="stylesheet" href="<?=$this->url('home')?>css/main_admin.css" media="screen" />
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
</head>
<body>
<div class="banner">
  <h1>Administration</h1>
   <!--<div class="breadcrumb">
    <div class="item" style="float: left;"><a href="#home">Home / </a></div>
   <div style="float: left;">Home /</div>
    <div style="float: right;">
      [<a href="logout.php">Log Out</a>]
    </div>
  </div>-->
  

     <!--<div class="breadcrumb">
          <li><a href="#">Home /</a></li>
     </div>-->
  <?php if (!$this->layout()->hideNavigation):
			if ($this->isUser()->isLogged()): 				
  ?>
  <a href="<?=$this->url('login')?><?='?logout=y'?>" style="float:right;color:white;">Logout</a>
  <?php endif;
  endif; ?>
</div>

<!-- Fixed navbar -->
	<?php if (!$this->layout()->hideNavigation): ?>
    <div class="navbar navbar-default" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse">
			<ul class="nav navbar-nav navbar-right pull-left">
			<?php 
				$modules = $this->isUser()->hasPermission();
				if (in_array("Work", $modules)) { 
			?>
            <li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Work<b class="caret"></b></a>			  
				<ul class="dropdown-menu">
                <li><a href="<?php echo $this->url('new_work') ?>">New</a></li>
                <li><a href="<?php echo $this->url('search_work') ?>">Search</a></li>
				<li><a href="<?php echo $this->url('manage_work') ?>">Manage</a></li>
				<li><a href="<?php echo $this->url('manage_work') ?><?= '?action=review' ?>">Review</a></li>
				<li><a href="<?php echo $this->url('manage_work') ?><?= '?action=classify' ?>">Classify</a></li>
				</ul>
			</li>
			<?php } ?>
				<!--<li class="divider-vertical"></li>-->
			<?php if (in_array("Work Type", $modules)) { ?>
			<li class="dropdown">           
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Work Type<b class="caret"></b></a>
				<ul class="dropdown-menu">
                <li><a href="<?php echo $this->url('new_worktype') ?><?='?action=new'?>">New</a></li>
                <li><a href="<?php echo $this->url('manage_worktype') ?>">Manage</a></li>
				<li><a href="<?php echo $this->url('attributes_worktype') ?>">Attributes</a></li>
				</ul>
            </li>       
			<?php } ?>
			<?php if (in_array("Classification", $modules)) { ?>
            <li class="dropdown">           
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Classification<b class="caret"></b></a>
				 <ul class="dropdown-menu">
                <li><a href="<?php echo $this->url('new_classification') ?><?='?action=new'?>">New</a></li>
                <li><a href="<?php echo $this->url('manage_classification') ?>">Manage</a></li>
				<li><a href="<?php echo $this->url('merge_classification') ?><?= '?action=merge_classification' ?>">Merge</a></li>				
				<li><a href="<?php echo $this->url('exportlist_classification') ?><?='?action=export_classification'?>">Export List</a></li>
              </ul>
            </li>  			
            <?php } ?>
			<?php if (in_array("Agent", $modules)) { ?>
			<li class="dropdown">           
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Agent<b class="caret"></b></a>
				 <ul class="dropdown-menu">
                <li><a href="<?php echo $this->url('new_agent') ?><?='?action=new'?>">New</a></li>
                <li><a href="<?php echo $this->url('find_agent') ?>">Find</a></li>
				<li><a href="<?php echo $this->url('manage_agent') ?>">Manage</a></li>
				<li><a href="<?php echo $this->url('merge_agent') ?><?='?action=merge'?>">Merge</a></li>
              </ul>
            </li>  
			<?php } ?>
			<?php if (in_array("Agent Type", $modules)) { ?>
			<li class="dropdown">           
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Agent Type<b class="caret"></b></a>
				 <ul class="dropdown-menu">
                <li><a href="<?php echo $this->url('new_agenttype') ?><?='?action=new'?>">New</a></li>
				<li><a href="<?php echo $this->url('manage_agenttype') ?>">Manage</a></li>
              </ul>
            </li> 
			<?php } ?>
			<?php if (in_array("Publisher", $modules)) { ?>
			<li class="dropdown">           
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Publisher<b class="caret"></b></a>
				 <ul class="dropdown-menu">
                <li><a href="<?php echo $this->url('new_publisher') ?><?='?action=new'?>">New</a></li>
                <li><a href="<?php echo $this->url('find_publisher') ?>">Find</a></li>
				<li><a href="<?php echo $this->url('manage_publisher') ?>">Manage</a></li>
				<li><a href="<?php echo $this->url('merge_publisher') ?>">Merge</a></li>
              </ul>
            </li> 
			<?php } ?>
			<?php if (in_array("Language", $modules)) { ?>
			<li class="dropdown">           
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Language<b class="caret"></b></a>
				 <ul class="dropdown-menu">
                <li><a href="<?php echo $this->url('new_language') ?><?='?action=new'?>">New</a></li>
				<li><a href="<?php echo $this->url('manage_language') ?>">Manage</a></li>
              </ul>
            </li> 
			<?php } ?>
			<?php if (in_array("Users", $modules)) { ?>
			<li class="dropdown">           
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Users<b class="caret"></b></a>
				 <ul class="dropdown-menu">
                <li><a href="<?php echo $this->url('new_user') ?><?='?action=new'?>">New</a></li>
				<li><a href="<?php echo $this->url('manage_users') ?>">Manage</a></li>
				<li><a href="<?php echo $this->url('access_users') ?>">Access</a></li>
              </ul>
            </li> 
			<?php } ?>
			<?php if (in_array("Preferences", $modules)) { ?>
			<li class="dropdown">           
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Preferences<b class="caret"></b></a>
				 <ul class="dropdown-menu">
                <li><a href="<?php echo $this->url('changepassword_preferences') ?><?='?action=change_pwd'?>">Change Password</a></li>
              </ul>
            </li> 
			<?php } ?>
          </ul>
		  
        </div><!--/.nav-collapse -->
      </div>
    </div>
	<?php endif; ?>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
	<script src="//code.jquery.com/jquery-1.10.2.js"></script>
	<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script src="<?=$this->url('home')?>js/menu.js"></script>
	 <script src="<?=$this->url('home')?>vendor/js/bootstrap-3.3.7.min.js"></script>
	<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
 <div class="app-content" width="100%">
 <div style="width: 80%">
            <?php echo $this->content ?>
 </div> 

 <?php
			
			// Page Instructions Content
            include_once('instructions.inc');
			
			$str = "";
            $page = basename($this->url());
			$str = preg_replace('/^\/\w+\/\w+\//','',parse_url($this->url())['path']);
			if(isset($_SERVER['QUERY_STRING']))
			{
				if(preg_match('/action=(?<action_name>[A-Za-z]+)/', $_SERVER['QUERY_STRING'], $matches))
				{
					$str .= "?" . $_SERVER['QUERY_STRING'];
					//echo $str . "<br />";
				}
			}
				
			echo "$str <br />";
			
           if (isset($_POST['instructions'])) {   
			  //print_r($_POST['instructions']);
            $instructions[basename($this->url())] = $_POST['instructions'];
			
           }
	      // print_r($instructions);
	        $this->layout()->instructions = isset($instructions[$page])
                    ? $instructions[$page] : ''; 
?>
        <main class="container">  
				<div style="float: right; width: 20%;">
				<div class="tipbox">
				<div>Instructions</div>
				<form method="post" name="ins_box">
				<input type="hidden" name="action" value="ins">
				<textarea name="instructions" rows="5" cols="22"><?php echo $this->layout()->instructions; ?></textarea><br>
				<input type="submit" name="submit" value="Save">
				</form>
				</div>
			   </div>	
        </main>
</div>

</body>