<?php $this->headTitle('Delete AgentType'); ?>
<?php
      $this->layout()->breadcrumbs .= '<a href="' . $this->url('manage_agenttype') . '" style="float:left;color:white;"> Agenttype > </a>'
                                      . ' Delete';
 ?>

<div class="col-xs-4">
    <form method="post" action="<?= $this->url('manage_agenttype') ?>">
        <p>Are you sure you want to delete this?</p>        
        <?php
        $id;
        if ($request->getqueryParams('id') !== null) {
            $params = $request->getqueryParams();
            $action = $params['action'];
        }

        if ($request->getMethod() == 'POST') {
            $post = $request->getParsedBody();
        }
        $agType = [];
        if(count($post['selectAgentType']) > 0) {
            foreach($post['selectAgentType'] as $agentType):
                $agType['id'] = $agentType;

                //fetch name based on id
                $table = new \VuBib\Db\Table\AgentType($adapter);
                $row = $table->findRecordById($agType['id']);
                $type = $row['type'];
                echo "<li>$type</li>";
        ?>
        <ul>
        <input type="hidden" name="agType_id[]" value="<?=$agType['id']?>">                        
        <input type="hidden" name="action" value="<?=$action?>">
        </ul>                        
        <?php
            endforeach;
        }
        ?>
        <input type="submit" name="submitt" value="Delete"> 
        <input type="submit" name="submitt" value="Cancel">
    </form>
</div>