<?php
    $params = $request->getQueryParams();
    $post = $request->getParsedBody();
    $wkat_id = $params['wkat_id'];
    $action = $params['action'];

    $this->headTitle('Delete Option');
    $this->layout()->breadcrumbs .= '<a href="' . $this->url('attributes_worktype') . '">Attributes</a> &gt; <a href="' . $this->url('manage_attribute_options', ['id' => $wkat_id]) . '">Attribute Options</a> &gt; Delete';
    $this->layout()->page = "Attributes Options/Delete";
?>
<div class="col-xs-4">
    <form method="post" action="<?=$this->url('manage_attribute_options')?>?id=<?=$wkat_id ?>">
        <input type="hidden" name="action" value="<?=$action?>">
        <p>Are you sure you want to delete this?</p>
        <dl>
            <?php
                $wkAttr_Opt = [];
                if(count($post['selectWorkAttrOpt']) > 0) {
                    foreach($post['selectWorkAttrOpt'] as $workAttrOpt):
                        $wkAttr_Opt['id'] = $workAttrOpt;
                        //fetch name based on id
                        $table = new \VuBib\Db\Table\WorkAttribute_Option($adapter);
                        $row = $table->findRecordById($wkAttr_Opt['id']);
                        $title = $row['title'];
                        //fetch no of works associated
                        $table = new \VuBib\Db\Table\Work_WorkAttribute($this->adapter);
                        $paginator = $table->countRecordsByAttributeOption($wkat_id, $wkAttr_Opt['id']);
                        $cnt = $paginator->getTotalItemCount();
                        ?>
                        <input type="hidden" name="workattropt_id[]" value="<?=$wkAttr_Opt['id']?>">
                        <dt><?=$title ?></dt>
                        <dd>There are <?=$cnt ?> works associated with it.</dd>
                    <?php endforeach;
                }
            ?>
        </dl>
        <input class="btn btn-danger" type="submit" name="submitt" value="Delete">
        <input class="btn btn-default" type="submit" name="submitt" value="Cancel">
    </form>
</div>

