<?php $this->headTitle('Delete WorkType'); ?>
<?php
    $this->layout()->breadcrumbs .= '<a href="' . $this->url('manage_worktype') . '">Worktype</a> &gt; Delete';
    $this->layout()->page = "Worktype/Delete";
?>
<div class="col-xs-4">
    <form method="post" action="<?=$this->url('manage_worktype')?>">
        <p>Are you sure you want to delete this?</p>
        <?php
                if ($request->getqueryParams('action') !== null)
                {
                    $params = $request->getqueryParams();
                    $action = $params['action'];
                }

                if ($request->getMethod() == 'POST') {
                    $post = $request->getParsedBody();
                }

                $wk_type = [];
                if(count($post['selectWorkType']) > 0) {
                    foreach($post['selectWorkType'] as $work_type):
                        $wk_type['id'] = $work_type;
                        //fetch name based on id
                        $table = new \VuBib\Db\Table\WorkType($adapter);
                        $row = $table->findRecordById($wk_type['id']);
                        $type = $row['type'];
                        echo "<p>$type</p>"; ?>
                        <ul>
                        <input type="hidden" name="worktype_id[]" value="<?=$wk_type['id']?>">
                        <input type="hidden" name="action" value="<?=$action?>">
                        </ul>
                        <?php
                    endforeach;
                }
            ?>
        <input type="submit" name="submitt" value="Delete">
        <input type="submit" name="submitt" value="Cancel">
    </form>
</div>

