<?php $this->headTitle('Edit Option'); ?>
<?php //$this->layout()->instructions = ""; ?>
<?php
$id;
if ($request->getqueryParams('id') !== null) {
    $params = $request->getqueryParams();
    $action = $params['action'];
    $id = $params['id'];
    $wkat_id = $params['wkat_id'];
    $this->layout()->breadcrumbs .= '<a href="' . $this->url('attributes_worktype') . '">Attributes</a> &gt; <a href="' . $this->url('manage_subattributes', ['id' => $wkat_id]) . '">Sub Attributes</a> &gt; Edit';
    $this->layout()->page = "Sub Attributes/Edit";
    //fetch sub attribute name based on id
    $table = new \VuBib\Db\Table\WorkAttribute_SubAttribute($adapter);
    $subattr_row = $table->findRecordById($id);
    $subattribute = $subattr_row['subattribute'];
    //fetch attribute name based on id
    $table = new \VuBib\Db\Table\WorkAttribute($adapter);
    $attr_row = $table->findRecordById($wkat_id);
    $attribute = $attr_row['field'];
}
?>
<?php $escaper = new Zend\Escaper\Escaper('utf-8'); ?>
<div class="col-md-4">
<p><b style="font-size: 10pt; padding: 20px;">Attribute: <?php echo $attribute; ?></b></p>
<form class="form-horizontal" method="post" action="<?=$this->url('manage_subattributes')?>">
    <input type="hidden" name="action" value="<?= $action ?>">
    <input type="hidden" name="wkat_id" value="<?= $wkat_id ?>">
    <input type="hidden" name="id" value="<?= $id ?>">
    <div class="form-group">
        <label class="col-xs-4 control-label">Sub Attribute: </label>
        <div class="col-xs-7">
            <input type="text" class="form-control" name="edit_subattr" id="editsubattr" value="<?=$escaper->escapeHtml($subattribute)?>" />
        </div>
        <br /> <br />
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default" name="submitt" value="Save">Save</button>
            <button type="submit" class="btn btn-default" name="submitt" value="Cancel">Cancel</button>
        </div>
    </div>
</form>
</div>