<?php $this->headTitle('Edit WorkType'); ?>
<?php
    $this->layout()->breadcrumbs .= '<a href="' . $this->url('manage_worktype') . '">Worktype</a> &gt; Edit';
    $this->layout()->page = "Worktype/Edit";
?>
<?php
if ($request->getqueryParams('id') !== null) {
    $params = $request->getqueryParams();
    $action = $params['action'];
    $id = $params['id'];
    //fetch name based on id
    $table = new \VuBib\Db\Table\WorkType($adapter);
    $row = $table->findRecordById($id);
}

$langMap = ['text_en' => 'English', 'text_de' => 'German', 'text_es' => 'Spanish', 'text_fr' => 'French', 'text_it' => 'Italian', 'text_nl' => 'Dutch'];
?>
<?php $escaper = new Zend\Escaper\Escaper('utf-8'); ?>
<form class="form-horizontal" method="post" action="<?=$this->url('manage_worktype')?>">
    <input type="hidden" name="action" value="<?=trim($action)?>">
    <input type="hidden" name="id" value="<?=trim($id)?>">
    <? var_dump($row); ?>
    <?php foreach($row as $col => $val): ?>
        <?php if ($col == 'id' || $col == 'type') continue; ?>
        <div class="form-group">
            <label class="col-sm-3 control-label"><?=$langMap[$col] ?> Title:</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" name="<?=$col ?>" maxlength="200" value="<?=$escaper->escapeHtml(trim($val))?>" />
            </div>
        </div>
    <?php endforeach; ?>
    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-9">
            <button type="submit" class="btn btn-primary" name="submitt" value="Save">Save</button>
            <button type="submit" class="btn btn-default" name="submitt" value="Cancel">Cancel</button>
        </div>
    </div>
</form>

