<?php $this->headTitle('Manage Work Type'); ?>
<?php
    $this->layout()->breadcrumbs .= '<a href="' . $this->url('manage_worktype') . '">Worktype</a> &gt; Manage';
    $this->layout()->page = "Worktype/Manage";

    function collapseParams($params) {
        $pairs = [];
        foreach ($params as $key => $val) {
            $pairs[] = $key . '=' . $val;
        }
        return '?' . implode('&', $pairs);
    }

    function sortParams($col) {
        // Get parameters
        $params = [];
        $parts = explode('&', $_SERVER["QUERY_STRING"]);
        foreach ($parts as $part) {
            if (!$part) {
                continue;
            }
            list($key, $val) = explode('=', $part, 2);
            $params[$key] = $val;
        }

        // New order
        if (!isset($_GET['orderBy']) || $col != $_GET['orderBy']) {
            // Change order
            $params['orderBy'] = $col;
            $params['sort'] = 'ASC';
            return collapseParams($params);
        }

        // Change order
        $sortOrder = $_GET['sort'] ?? 'X';
        $nextSort = [
            'X' => 'ASC',
            'ASC' => 'DESC',
            'DESC' => 'X'
        ][$sortOrder];

        if ($nextSort == 'X') {
            // Remove order
            unset($params['orderBy']);
            unset($params['sort']);
        } else {
            // Change order
            $params['orderBy'] = $col;
            $params['sort'] = $nextSort;
        }

        return collapseParams($params);
    }
    function sortIcon($col) {
        $orderBy = $_GET['orderBy'] ?? null;
        if ($col != $orderBy) {
            return '';
        }
        $orderDir = $_GET['sort'] ?? 'ASC';
        if ($orderDir == 'X') {
            return '';
        }
        return $orderDir == 'ASC' ? '↓' : '↑';
    }
?>
<script type='text/javascript'>
$(document).ready(function () {
    //Check if records are selected for delete
    $("#delWorkType").on('click', function () {
        if ($("#workTypeListTable input:checkbox:checked").length > 0) {
            // any one is checked
            return true;
        } else {
            // none is checked
            alert("No work type(s) selected, Please select work type(s) to delete.");
            return false;
        }
    });
});
</script>
<div class="col-md-9">
    <a href="<?= $this->url('new_worktype') ?><?='?action=new'?>"><b style="text-decoration: underline;">Add WorkType</b></a>
    <form action="<?=$this->url('delete_worktype')?><?='?action=delete'?>" method="post">
    <table class="table table-striped table-condensed" id="workTypeListTable" style="font-size:10pt;">
        <thead>
            <tr>
                <th>&nbsp;&nbsp;</th>
                <th><a href="<?=$this->url('manage_worktype') ?><?=sortParams('type') ?>">Work Type <?=sortIcon('type') ?></a></th>
                <th>Attributes</th>
            </tr>
        </thead>
        <tbody>
        <?php $escaper = new Zend\Escaper\Escaper('utf-8'); ?>
        <?php foreach($this->rows as $row) :
                $output = (array)$row;
                $params = implode(', ', $output);
        ?>
        <tr>
        <td>
            <input type="checkbox" id="selWorkType" name="selectWorkType[]" value=<?=$row['id']?>>
        </td>
        <td>
            <a href="<?=$this->url('edit_worktype')?><?='?id=' . $row['id'] . '&action=edit'?>">
            <?php echo $escaper->escapeHtml($row['text_fr'] ?? $row['type']); ?></a>
        </td>
        <td>
            <a href="<?=$this->url('manage_worktypeattribute')?><?='?id=' . $row['id']?>">Manage Attributes</a>
        </td>
        </tr>
        <?php endforeach; ?>
        </tbody>
        </table>
        <input type="submit" name="delWorkType" id="delWorkType" value="Delete">
        </form>
        <?php if($this->countp > 1) { ?>
        <form method="get" action="page">
            <?=$this->paginationControl($this->rows,
                'Sliding',
                'vubib::controls',
                [
                    'route' => 'manage_worktype',
                    'extraParams' => $searchParams,
                ]
            );?>
        </form>
        <?php } ?>
</div>