<?php $this->headTitle('Manage Sub Attributes'); ?>
<?php
    $this->layout()->breadcrumbs .= '<a href="' . $this->url('attributes_worktype') . '">Attributes</a> &gt; Manage Sub Attributes';
    $this->layout()->page = "Attributes/Manage Sub Attributes";
?>
<?php
if ($request->getqueryParams('action') !== null) {
    $params = $request->getqueryParams();
    $attr_id = $params['wkat_id'] ?? $this->wkat_id;
    //fetch attribute name based on id
    $table = new \VuBib\Db\Table\WorkAttribute($adapter);
    $attr_row = $table->findRecordById($attr_id);
    $attribute = $attr_row['field'];

    $subattr_row = (array)$this->rows;
}
?>
<div class="col-md-9">
    <p><b style="font-size: 10pt; padding: 20px;">Attribute: <?php echo $attribute; ?></b></p>
    <?php
    if (count($subattr_row) > 0){
        $subattr_Id = $subattr_row['id'];
        $subattr = $subattr_row['subattribute'];
        $escaper = new Zend\Escaper\Escaper('utf-8');
    ?>
        <form action="<?=$this->url('delete_subattribute')?><?='?action=delete'?>" method="post">
            <input type="hidden" name="wkat_id" value="<?=$attr_id?>">
            <input type="hidden" name="subat_id" value="<?=$subattr_Id?>">
            <div class="form-group">
                <label class="col-xs-2 control-label">Sub Attribute: </label>
                <div class="col-xs-5">
                    <a href="<?=$this->url('edit_subattribute')?><?='?wkat_id=' . $attr_id . '&id=' . $subattr_Id . '&action=edit'?>">
                       <?php echo $escaper->escapeHtml($subattr); ?>
                    </a>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <input type="submit" name="delSubAttr" id="delSubAttr" value="Delete">
                </div>
            </div>
        </form>
    <?php
    } else {
    ?>
        <p><b style="font-size: 10pt; padding: 20px;">Sub Attribute: None</b></p>
        <a href="<?=$this->url('new_subattribute')?><?='?id=' . $attr_id . '&action=new'?>"><b style="text-decoration: underline;">Add Sub Attribute</b></a>
    <?php
    }
    ?>
</div>