<?php
$this->headTitle('Manage Options - Attributes');
?>
<?php
    $this->layout()->breadcrumbs .= '<a href="' . $this->url('attributes_worktype') . '">Attributes</a> &gt; Manage Options';
    $this->layout()->page = 'Attributes/Manage Options';
 ?>
<?php
if ($request->getqueryParams('action') !== null) {
    $params = $request->getqueryParams();
    if(isset($params['action']) && $params['action'] == 'search_option') {
        $matches = [];
        if (preg_match_all('/(.*)worktype_attr=(?<id>\d+)(.*)/', $searchParams, $matches)) {
            $id = $matches['id'][0];
        }
    } else {
        $id = $params['id'];
    }
    //fetch attribute name based on id
    $table = new \VuBib\Db\Table\WorkAttribute($adapter);
    $row = $table->findRecordById($id);
    $attribute = $row['field'];
    //fetch subattributes of attribute
    $table = new \VuBib\Db\Table\WorkAttribute_SubAttribute($this->adapter);
    $subattr = $table->findRecordsByWorkAttrId($id);
}
?>
<?php
  $q_params = $request->getQueryParams();

  // Set url for title sort toggle
  $nextOrder = 'ASC';
  if (isset($q_params['sort_ord']) && $q_params['sort_ord'] == 'ASC') {
    $nextOrder = 'DESC';
  }

  $newParams = array_merge($q_params, ['sort_ord' => $nextOrder]);
  $optionSortUrl = $this->url('manage_attribute_options', [], $newParams);

  // Set order parameters for pagination
  $paginationParamsStr = '';
  foreach ($q_params as $key=>$val) {
    if ($key == 'page') {
      continue;
    }
    if (strlen($paginationParamsStr) > 0) {
      $paginationParamsStr .= '&';
    }
    $paginationParamsStr .= $key . '=' . $val;
  }
?>
<script type='text/javascript'>
$(document).ready(function () {
    //Check if records are selected for delete
    $("#delWorkAttrOpt").on('click', function () {
        if ($("#workAttrOptListTable input:checkbox:checked").length > 0) {
            // any one is checked
            return true;
        } else {
            // none is checked
            alert("No attribute option(s) selected, Please select attribute option(s) to delete.");
            return false;
        }
    });
});
</script>
<div class="col-md-9">
    <p><b style="font-size: 10pt; padding: 20px;">Attribute: <?php echo $attribute; ?></b></p>
    <a href="<?=$this->url('new_option')?><?='?id=' . $id . '&action=new'?>"><b style="text-decoration: underline;">Add Option</b></a>
    &nbsp;&nbsp;&nbsp;
    <a href="<?=$this->url('merge_options')?><?='?id=' . $id . '&action=merge_options'?>"><b style="text-decoration: underline;">Merge Options</b></a>
    <form action="<?=$this->url('delete_option')?><?='?wkat_id=' . $id . '&action=delete'?>" method="post">
    <table class="table table-striped table-condensed" id="workAttrOptListTable" style="font-size:10pt;">
        <thead>
        <tr>
          <th>&nbsp;&nbsp;</th>
          <th><a href="<?=$optionSortUrl ?>">Option</a></th>
          <?php if (count($subattr) > 0){ ?>
            <th><?=$subattr['subattribute']?></th>
          <?php } ?>
        </tr>
        </thead>
        <tbody>
            <?php if($this->countp > 0) { ?>
            <?php
            $escaper = new Zend\Escaper\Escaper('utf-8');
            foreach($this->rows as $row) :
                $output = (array)$row;
                $params = implode(', ', $output);
            ?>
            <tr>
                <td>
                    <input type="checkbox" id="selWorkAttrOpt" name="selectWorkAttrOpt[]" value=<?=$row['id']?>>
                </td>
                <td>
                    <a href="<?=$this->url('edit_option')?><?='?wkat_id=' . $id . '&id=' . $row['id'] . '&action=edit'?>">
                    <?php echo $escaper->escapeHtml($row['title']); ?></a>
                </td>
                <?php
                if (count($subattr) > 0){
                    $subattr_value = "";
                    //fetch subattribute values for option
                    $table = new \VuBib\Db\Table\Attribute_Option_SubAttribute($this->adapter);
                    $opt_subattr_rows = $table->findRecordByOption($row['id'], $subattr['id']);
                    foreach($opt_subattr_rows as $subopt_row):
                        if ($subopt_row["subattr_value"] != "") {
                            $subattr_value .= $subopt_row['subattr_value'] . ", ";
                        }
                    endforeach;
                ?>
                <td><?=trim($subattr_value, ", ");?></td>
                <?php } ?>
            </tr>
            <?php endforeach; ?>
        <?php } ?>
        </tbody>
    </table>
    <input type="hidden" name="wkat_id" value="<?=$id?>">
    <input class="btn btn-default" type="submit" name="delWorkAttrOpt" id="delWorkAttrOpt" value="Delete">
    </form>
    <?php if($this->countp > 1) { ?>
        <form method="get" action="page">
            <?=$this->paginationControl($this->rows,
                'Sliding',
                'vubib::controls',
                [
                    'route' => 'manage_attribute_options',
                    'extraParams' => $paginationParamsStr,
                ]
            );?>
        </form>
    <?php } ?>
</div>
