<?php $this->headTitle('New Work Type'); ?>
<?php
    $this->layout()->breadcrumbs .= '<a href="' . $this->url('manage_worktype') . '">Worktype</a> &gt; New';
    $this->layout()->page = "Worktype/New";
?>
<?php
    if ($request->getqueryParams('action') !== null) {
        $params = $request->getqueryParams();
        $action = $params['action'];
    }
?>
<div class="col-md-4">
    <form class="form-horizontal" method="post" action="<?=$this->url('manage_worktype')?>">
        <input type="hidden" name="action" value="<?=$action?>">
        <div class="form-group">
            <label class="col-sm-3 control-label">text_en:</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" name="text_en" id="editworktype" maxlength="200" value="">
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">text_fr:</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" name="text_fr" id="editworktype" maxlength="200" value="">
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">text_de:</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" name="text_de" id="editworktype" maxlength="200" value="">
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">text_nl:</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" name="text_nl" id="editworktype" maxlength="200" value="">
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">text_es:</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" name="text_es" id="editworktype" maxlength="200" value="">
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">text_it:</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" name="text_it" id="editworktype" maxlength="200" value="">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-9">
                <button type="submit" class="btn btn-default" name="submitt" value="Save">Save</button>
                <button type="submit" class="btn btn-default" name="submitt" value="Cancel">Cancel</button>
            </div>
        </div>
    </form>
</div>
