<?php $this->headTitle('New Option'); ?>
<?php //$this->layout()->instructions = ""; ?>
<?php
if ($request->getqueryParams('action') !== null) {
    $params = $request->getqueryParams();
    $action = $params['action'];
    $wkat_id = $params['id'];

    //fetch attribute name based on id
    $table = new \VuBib\Db\Table\WorkAttribute($adapter);
    $attr_row = $table->findRecordById($wkat_id);
    $attribute = $attr_row['field'];
    //fetch subattributes of attribute
    $table = new \VuBib\Db\Table\WorkAttribute_SubAttribute($this->adapter);
    $subattr = $table->findRecordsByWorkAttrId($wkat_id);

    $this->layout()->breadcrumbs .= '<a href="' . $this->url('attributes_worktype') . '" style="float:left;color:white;"> Attributes > </a>' .
                '<a href="' . $this->url('manage_attribute_options') . '?id=' . $wkat_id . '" style="float:left;color:white;"> Attribute Options > </a>'
                . ' New';
}
?>
<script>
$(document).ready(function(){
    $('#subattrForm')
        // Add button click handler
        .on('click', '.addButton', function() {
            var $template = $('#optionTemplate'),
                $clone    = $template
                                .clone()
                                .removeClass('hide')
                                .removeAttr('id')
                                .insertBefore($template);
        })
        // Remove button click handler
        .on('click', '.removeButton', function() {
            var $row    = $(this).parents('.form-group');
            
            // Remove element containing the option
            $row.remove();
        });
});
</script>
<div class="col-md-4">
    <p><b style="font-size: 10pt; padding: 20px;">Attribute: <?php echo $attribute; ?></b></p>
    <form class="form-horizontal" id="subattrForm" method="post" action="<?=$this->url('manage_attribute_options')?><?= '?id=' . $wkat_id ?>">
        <input type="hidden" name="action" value="<?=$action?>">
        <input type="hidden" name="id" value="<?=$wkat_id?>">
        <div class="form-group">
            <label class="col-sm-3 control-label">Option</label>
            <div class="col-sm-5">
                <input type="text" class="form-control" name="new_option" required="true" size="100"/>
            </div>
        </div>

        <?php if (count($subattr) > 0){ ?>
        <input type="hidden" name="subattr_id" value="<?=$subattr['id']?>">
        <div class="form-group">
            <label class="col-sm-3 control-label"><?=$subattr['subattribute']?>:</label>
            <div class="col-sm-5">
                <input type="text" class="form-control" name="newsubattr[]" size="100"/>
            </div>
            <div class="col-sm-4">
                <button type="button" class="btn btn-default addButton"><i class="fa fa-plus">+</i></button>
            </div>
        </div>
        <?php } ?>

        <!-- The option field template containing an option field and a Remove button -->
        <div class="form-group hide" id="optionTemplate">
            <div class="col-sm-offset-3 col-sm-5">
                <input class="form-control" type="text" name="newsubattr[]" size="100"/>
            </div>
            <div class="col-sm-4">
                <button type="button" class="btn btn-default removeButton"><i class="fa fa-minus">-</i></button>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-5 col-sm-offset-3">
                <button type="submit" class="btn btn-default" name="submitt" value="Save">Save</button>
                <button type="submit" class="btn btn-default" name="submitt" value="Cancel">Cancel</button>
            </div>
        </div>
    </form>
</div>